### ISSUE TITLE
BootLoopAfterRunningCompareExampleOnGTX1080

### ISSUE THREAD

**Issue by billbak90** [davidsandberg/facenet#100]
After a few executions of  compare.py with tensorflow 0.11.0rc2 and bazel 0.4.3 on an gtx 1080 i had an issue with linux 16.04 LTS boot loop i tried all the other methods like restart lightdm and .Xauthority configurations but nothing happened .Could anybody help me with this ?
I also had  a message 
**E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 7.92G (8507162624 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY**
although everything was ok before the system restarted .

thanks

**Comment by davidsandberg** [comment]
Hi,
Have you tested your CUDA installation, by for example running any of the CUDA examples that are included in the CUDA toolkit? And if so, have you been running any other tensorflow code that uses the GPU?

**Comment by billbak90** [comment]
Hi,
Yes i tested CUDA  examples and i also run a gpu tensorflow examples before the crash

**Comment by davidsandberg** [comment]
Since the facenet implementation only uses the python API for tensorflow I don't think this problem is related to facenet. For best help I think you should post this question to https://devtalk.nvidia.com/ or maybe https://github.com/tensorflow/tensorflow/issues.
