### ISSUE TITLE
Using FaceNet for food classification

### ISSUE THREAD

**Issue by TimGeronimoLam** [davidsandberg/facenet#1017]
I have a food dataset that I want to train with triplet loss. In the dataset, each image corresponds to one dish and it is set up according to the data structure in the [wiki page](https://github.com/davidsandberg/facenet/wiki/Triplet-loss-training). The dataset contains about 20.000 images in total and the images per class vary from 20 to 900.

I already managed to train a classifier and classify images. However, I want the parameters to be optimal so that the classifier's accuracy becomes better. In particular, I was wondering how to choose:

- people_per_batch (default: 45)
- images_per_person (default: 40)

Can someone explain what they mean or if they are even relevant if there is ever only one class per image and it's not faces? And how should I set them? For the rest of the arguments I basically went with those from the wiki page except that I did not use the LFW validation dataset.

**Comment by thelastfunction** [comment]
They are used for calculating triplets(A,P,N) from samples for training on triplet loss.(see sample function in traintripletloss.py line 313).

-What triplet_loss does is that it doesn't go through each and every image in dataset to calculate triplet batches as it will be computationally expensive  to make triplet combinations for large datasets . (  from facenet paper it is  infeasible  to  compute  the argmin and argmax across the whole training set.   Additionally,  it might lead to  poor  training,  as  mislabelled  and  poorly  imaged  faces would dominate the hard positives and negatives). 

-nrof_images = people_per_batch * images_per_person (line 314)
-so first they select class and image_paths list from samples by randomizing (line 330) the class list and image paths
-Now using these classes and image path list they make triplet combinations
-And then find good triplets which satisfy the triplet condition by finding embedding.(so people_per_batch and images_per_person are used in this child batch to compute their embedding (line 224))

And finally train by triplet loss in the Main batch(line 254).

-It should work fine for just one image per class as it is based on one shot learning but I believe it will take more time to converge.Will be good if you use classes with atleast 10 images.
-Its totally applicable even if there are no faces
-please read facenet paper for more info (section 3.2 triplet selection)
-facenet paper link - https://arxiv.org/pdf/1503.03832.pdf

**Comment by TimGeronimoLam** [comment]
Thanks a lot for the clarification! Closing this ...

**Comment by hi-karan-here** [comment]
> I have a food dataset that I want to train with triplet loss. In the dataset, each image corresponds to one dish and it is set up according to the data structure in the [wiki page](https://github.com/davidsandberg/facenet/wiki/Triplet-loss-training). The dataset contains about 20.000 images in total and the images per class vary from 20 to 900.
> 
> I already managed to train a classifier and classify images. However, I want the parameters to be optimal so that the classifier's accuracy becomes better. In particular, I was wondering how to choose:
> 
> * people_per_batch (default: 45)
> * images_per_person (default: 40)
> 
> Can someone explain what they mean or if they are even relevant if there is ever only one class per image and it's not faces? And how should I set them? For the rest of the arguments I basically went with those from the wiki page except that I did not use the LFW validation dataset.

Hi Tim,

I found your work quite interesting. I am trying to do something similar with dataset of pets. I am very much at initial stage. I would be very keen to know the challenges that you faced while training from scratch?

I look forward to hear from you.
