### ISSUE TITLE
How to use multiGPU to run facenet?

### ISSUE THREAD

**Issue by tphyhFighting** [davidsandberg/facenet#103]
Hello,I have 4 1080pGPU,how do i use 4 GPU to run facennet_train_classifier?Waiting for your answer.

**Comment by Seanny123** [comment]
That's a TensorFlow problem that isn't specific to this repository.

**Comment by davidsandberg** [comment]
@tphyhFighting Multi-GPU training is not supported by facenet_train_classifier, and currently there is no plan to add this support either. If you really need to do it you can have a look at some example that implements this (like the CIFAR-10 example) and reuse the principles.

**Comment by tphyhFighting** [comment]
Thank you very much.I got it.

**Comment by apollo-time** [comment]
@tphyhFighting Did you implement multi-gpu training?
please share it for me, thanks.
