### ISSUE TITLE
如何製作.pb文件可以告訴我謝謝  about  freeze_graph.py  i want to  know access the code

### ISSUE THREAD

**Issue by hsm4703** [davidsandberg/facenet#1041]

**Comment by chen-bh** [comment]
python freeze_graph.py E:\facenet\facenet\models\facenet\20190708-161710 E:/facenet/mymodels/mymodel.pb
第一个参数，模型文件夹，第二个参数，pb文件全名

**Comment by hsm4703** [comment]
thank you  i solution the problem

**Comment by ucasiggcas** [comment]
请教下这个项目有提供训练好的模型用于测试吗？是我英语太差还是他们的确没有提供测试脚本啊。
大佬帮帮忙啊。
多谢
