### ISSUE TITLE
Facenet install

### ISSUE THREAD

**Issue by pankismart** [davidsandberg/facenet#106]
Hi,
I am facing a problem in installing facenet after cloning facenet library when I try running mtcnn alignment on some training images I get error no module named facenet.i tried python setup.py install inside facenet directory but there is no setup.py file. Did anyone tried installing facenet?

**Comment by ugtony** [comment]
You don't have to install it. You should add the FaceNet/src directory path to the environment variable PYTHONPATH before you run the scripts.

**Comment by CalabashBoy** [comment]
@ugtony  i get this error too, how did you make it? can you tell me?

**Comment by CalabashBoy** [comment]
@ugtony  mac os

**Comment by ugtony** [comment]
You can run the command below
```export PYTHONPATH=$PYTHONPATH:<your_path_to_facenet_src>```

**Comment by chenziwen23** [comment]
Set the environment variable PYTHONPATH to point to the src directory of the cloned repo. This is typically done something like this
export PYTHONPATH=[...]/facenet/src
where [...] should be replaced with the directory where the cloned facenet repo resides.
