### ISSUE TITLE
A typo in train_softmax.py

### ISSUE THREAD

**Issue by XuJianxing** [davidsandberg/facenet#1061]
It is in line 260:
                    for key, value in stat.iteritems():

Should it be " for key, value in stat.items(): " ?

**Comment by RubinXnibu** [comment]
No it's not a typo, it's python 2's version of Dictionary.items().   

From the top-page of Facenet:
The code is tested using Tensorflow r1.7 under Ubuntu 14.04 with Python 2.7 and Python 3.5. 

I haven't had any issues with Facenet itself, but some of its examples are in python 2, and you'll have to change them to python 3.  I've done this myself as well.

**Comment by XuJianxing** [comment]
Thanks!
