### ISSUE TITLE
facenet_train_classifier.py 

### ISSUE THREAD

**Issue by lightning0016** [davidsandberg/facenet#107]
the second, network.inference(eval_image_batch, 1.0, 
            phase_train=False, weight_decay=0.0,reuse=True),
but in nn4.py,it doesn't have the param (reuse=True) 
inference(images, keep_probability, phase_train=True, weight_decay=0.0),

**Comment by davidsandberg** [comment]
Yes, you're right.
I have never gotten the nn4-model to converge very well and that's the reason why I'm not using it that much. But I guess it would be nice to fix it so it works also with facenet_train_classifier.py.

**Comment by tengshaofeng** [comment]
@davidsandberg @lightning0016 
hi, have you experiment the deep net struct in paper 'A Discriminative Feature Learning Approach for Deep Face Recognition'.  accuracy of 99.28 is claimed on LFW in that paper.
