### ISSUE TITLE
Is the MTCNN model optimized for RGB or BGR image format?

### ISSUE THREAD

**Issue by tamerthamoqa** [davidsandberg/facenet#1077]
Hello everyone,

I am under the assumption the MTCNN model weights were imported from the original authors' [repository](https://github.com/kpzhang93/MTCNN_face_detection_alignment) and were not trained from scratch. If so, then the MTCNN was trained using the Caffe framework which reads images as BGR since it uses OpenCV ([evidence](https://github.com/BVLC/caffe/wiki/Image-Format:-BGR-not-RGB)).

Then why is the MTCNN performing well enough when having RGB images as input instead of BGR?

EDIT: 

The model should be optimized for RGB because the authors' [repository](https://github.com/kpzhang93/MTCNN_face_detection_alignment/blob/master/code/codes/MTCNNv2/demo.m#L42) uses the MATLAB imread() function which uses RGB instead of the caffe.io.load_image() function which uses BGR.

**Comment by amshaky-posidex** [comment]
Hi
https://github.com/ipazc/mtcnn/issues/36
The following link discussion shows that it will perform better on RGB images as authors trained the model using RGB chanel in matlab. From my experience RGB deefinitely performs better especially on tilted and dark backround faces, een though BGR images work fine most of the time.

**Comment by tamerthamoqa** [comment]
Thank you, much appreciated.
