### ISSUE TITLE
Where is calculate_roc

### ISSUE THREAD

**Issue by yawenSecond** [davidsandberg/facenet#1092]
I want to use **evaluate** function in **lfw.py**.  In **evaluate** function, there is 

`    tpr, fpr, accuracy = facenet.calculate_roc(thresholds, embeddings1, embeddings2,
        np.asarray(actual_issame), nrof_folds=nrof_folds, distance_metric=distance_metric, subtract_mean=subtract_mean)`

but the **calculate_roc** function is not in the **facenet.py**.

I wonder to know where **calculate_roc** function is ?

**Comment by HYL-Dave** [comment]
You should double check. See line 424 in facenet.py

**Comment by yawenSecond** [comment]
> You should double check. See line 424 in facenet.py

Thank you! I see.
