### ISSUE TITLE
Use pre-trained model with tensorflow

### ISSUE THREAD

**Issue by nerevar** [davidsandberg/facenet#112]
Hello, David!

I want to use facenet with tensorflow to calc embeddings in my dataset. 

You wrote in README about Python/Tensorflow implementation and made commit https://github.com/davidsandberg/facenet/commit/baae1cf0264ead6cb4303d1e50632ddf903e1fc4 about batch embeds calculating. 

Is it ready? Could you please share your model which you are using and tell how to use it?

Thanks,
Roman

**Comment by davidsandberg** [comment]
Hi @nerevar!
Currently there is no tool you can use for this out-of-the-box, but there are several examples, like validate_on_lfw.py, that you can use to put together your own piece of code.
And you can then use the model [20161116-234200](https://drive.google.com/file/d/0B5MzpY9kBtDVSTgxX25ZQzNTMGc/view?usp=sharing) as described on the [Validate on LFW](https://github.com/davidsandberg/facenet/wiki/Validate-on-LFW) page.

**Comment by nerevar** [comment]
Thanks for your reply, seems that is what I need :)
