### ISSUE TITLE
ValueError: Outputs of true_fn and false_fn must have the same type: float32, uint8

### ISSUE THREAD

**Issue by KowsalyaR97** [davidsandberg/facenet#1126]
While running train_softmax.py python file i receive the value error as,
 Outputs of true_fn and false_fn must have the same type: float32, uint8

**Comment by KowsalyaR97** [comment]
While running main( ) in train_softmax.py code i am getting following error,
Model directory: /content/drive/My Drive/Validate_on_LFW/src/models/facenet/20200106-121259
Log directory: /content/drive/My Drive/Validate_on_LFW/src/logs/facenet/20200106-121259
LFW directory: /content/drive/My Drive/Validate_on_LFW/src/align/datasets/lfw/lfw_aligned_faces
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-64-263240bbee7e> in <module>()
----> 1 main()

3 frames
<ipython-input-48-a5afe3f09f8f> in main()
     80                                     shared_name=None, name=None)
     81         enqueue_op = input_queue.enqueue_many([image_paths_placeholder, labels_placeholder, control_placeholder], name='enqueue_op')
---> 82         image_batch, label_batch = facenet.create_input_pipeline(input_queue, image_size, nrof_preprocess_threads, batch_size_placeholder)
     83 
     84         image_batch = tf.identity(image_batch, 'image_batch')

/content/drive/My Drive/Validate_on_LFW/src/facenet.py in create_input_pipeline(input_queue, image_size, nrof_preprocess_threads, batch_size_placeholder)
    120             image = tf.cond(get_control_flag(control[0], FIXED_STANDARDIZATION),
    121                             lambda:(tf.cast(image, tf.float32) - 127.5)/128.0,
--> 122                             lambda:tf.image.per_image_standardization(image))
    123             image = tf.cond(get_control_flag(control[0], FLIP),
    124                             lambda:tf.image.flip_left_right(image),

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py in new_func(*args, **kwargs)
    505                 'in a future version' if date is None else ('after %s' % date),
    506                 instructions)
--> 507       return func(*args, **kwargs)
    508 
    509     doc = _add_deprecated_arg_notice_to_docstring(

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/control_flow_ops.py in cond(pred, true_fn, false_fn, strict, name, fn1, fn2)
   1272         raise ValueError(
   1273             "Outputs of true_fn and false_fn must have the same type: "
-> 1274             "%s, %s" % (x.dtype.name, y.dtype.name))
   1275 
   1276     merges = [merge(pair)[0] for pair in zip(res_f_flat, res_t_flat)]

ValueError: Outputs of true_fn and false_fn must have the same type: float32, uint8

**Comment by pasa13142** [comment]
any solution ?

**Comment by KowsalyaR97** [comment]
Changing the version by !pip install tensorflow==1.4 works for me.
Read requirement.txt file to know about the tensor flow version.

**Comment by pasa13142** [comment]
Are u sure that it is 1.4 ? req says that it is 1.7 , I have 1.15

**Comment by KowsalyaR97** [comment]
Both 1.4 and 1.7 are working
