### ISSUE TITLE
Classifier training of inception resnet v1 page error

### ISSUE THREAD

**Issue by tphyhFighting** [davidsandberg/facenet#114]
This page decribes If no evaluation on LFW is desired during training it is fine to leave the lfw_dir parameter empty.But when leave the parameter empty .There is an error ：
UnboundLocalError: local variable 'lfw_paths' referenced before assignment
Maybe you should update the page.

**Comment by davidsandberg** [comment]
This problem has been fixed in c9d047496a29c229002bcac7444e1ac621b7dd18. Closing...
