### ISSUE TITLE
Error in running with tf 0.12.0

### ISSUE THREAD

**Issue by mrphoenix13** [davidsandberg/facenet#116]
Hi.
When I'm trying to run facenet_train on tensorflow 0.12 it gives me this error:

```Caused by op u'phase_train', defined at:
  File "~/Git/facenet/src/facenet_train.py", line 496, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "~/Git/facenet/src/facenet_train.py", line 86, in main
    phase_train_placeholder = tf.placeholder(tf.bool, name='phase_train')
```

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'phase_train' with dtype bool  [[Node: phase_train = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by davidsandberg** [comment]
Thanks! This should have been fixed in 54800f22cfcad14643c7f0cba4772024aec3e08a.
