### ISSUE TITLE
freezing_graph.py checkpoint not loading and calculate_embeddings.py short mat file.

### ISSUE THREAD

**Issue by OverFlow7** [davidsandberg/facenet#121]
Hello,
first of all  thank you davidsandberg for this awesome facenet implementation.

i have had two issues (they might be related), first one with freezing.py.

I get the error "Unable to get element from the feed as bytes." from line 43
`saver.restore(sess, tf.train.latest_checkpoint(os.path.expanduser(args.model_dir)))`
The problem seems to come from the  tf.train.latest_checkpoint( ) function because when i replace`saver.restore(sess, tf.train.latest_checkpoint(os.path.expanduser(args.model_dir)))) `by 
`saver.restore(sess, '~models/20161116-234200/model-20161116-234200.ckpt-80000')`
it seemingly works  fine, but i can't tell if the protobuf is correct 

the second issue is with calculate_embeddings.py,  i am trying to get  embeddings from the lfw/lfw_mtcnnpy_160 dataset

i get the warning : 
`W tensorflow/core/kernels/queue_base.cc:294] _1_input_producer/input_producer/fraction_of_32_full/fraction_of_32_full: Skipping cancelled enqueue attempt with queue not closed`

And here is what the mat file looks like.

```
{'__globals__': [],
 '__header__': 'MATLAB 5.0 MAT-file Platform: posix, Created on: Wed Jan 18 19:51:07 2017',
 '__version__': '1.0',
 'embeddings': array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]]),
 'image_list': array([ u'/home/florian/lfw/lfw_mtcnnpy_160/AJ_Cook/AJ_Cook_0001.png                ',
        u'/home/florian/lfw/lfw_mtcnnpy_160/AJ_Lamas/AJ_Lamas_0001.png              ',
        u'/home/florian/lfw/lfw_mtcnnpy_160/Aaron_Eckhart/Aaron_Eckhart_0001.png    ',
        u'/home/florian/lfw/lfw_mtcnnpy_160/Aaron_Guiel/Aaron_Guiel_0001.png        ',
        u'/home/florian/lfw/lfw_mtcnnpy_160/Aaron_Patterson/Aaron_Patterson_0001.png',
        u'/home/florian/lfw/lfw_mtcnnpy_160/Aaron_Peirsol/Aaron_Peirsol_0001.png    ',
        u'/home/florian/lfw/lfw_mtcnnpy_160/Aaron_Peirsol/Aaron_Peirsol_0002.png    ',
        u'/home/florian/lfw/lfw_mtcnnpy_160/Aaron_Peirsol/Aaron_Peirsol_0004.png    ',
        u'/home/florian/lfw/lfw_mtcnnpy_160/Aaron_Peirsol/Aaron_Peirsol_0003.png    ',
        u'/home/florian/lfw/lfw_mtcnnpy_160/Aaron_Pena/Aaron_Pena_0001.png          ',
        u'/home/florian/lfw/lfw_mtcnnpy_160/Aaron_Sorkin/Aaron_Sorkin_0001.png      ',
        u'/home/florian/lfw/lfw_mtcnnpy_160/Aaron_Sorkin/Aaron_Sorkin_0002.png      ',
        u'/home/florian/lfw/lfw_mtcnnpy_160/Aaron_Tippin/Aaron_Tippin_0001.png      ',
        u'/home/florian/lfw/lfw_mtcnnpy_160/Abba_Eban/Abba_Eban_0001.png            '], 
       dtype='<U74'),
 'label_list': array([[0, 1, 2, 3, 4, 5, 5, 5, 5, 6, 7, 7, 8, 9]])}
```
Only the first 14 images out of 13k are 'embedded' and the embeddings are all zeroes of length 1792, when length should be 128.  (128*14=1792 so i guess each embedding actually come from 14 images)

**Comment by davidsandberg** [comment]
I think your first problem is related to the change in checkpoint format that was introduced in TF r0.12. Your fix should be ok.
Regarding calculate_embeddings.py it is just experimental code and is not expected to work. However, there is a line 
```
train_set = train_set[0:10]
```
that is probably a part of your problem. Remove that and try again.
And the size of the embedding is actually 1792 for the model you are using (since it's training using facenet_train_classifier.py and not facenet_train.py).

**Comment by OverFlow7** [comment]
Oh it was that simple ,shame on me.

Thank you! it's working fine now.
