### ISSUE TITLE
cannot find align in align_dataset_mtcnn.py

### ISSUE THREAD

**Issue by cttsp** [davidsandberg/facenet#123]
Hi.

I read your code and want to train with my data.
But I can't find align in your code.
just like this: 
cropped = img[bb[1]:bb[3],bb[0]:bb[2],:]
scaled = misc.imresize(cropped, (args.image_size, args.image_size), interp='bilinear')
misc.imsave(output_filename, scaled)

Did you do align in your project?

**Comment by davidsandberg** [comment]
It just uses the bounding box.
