### ISSUE TITLE
facenet_train.py does not work with larger image size

### ISSUE THREAD

**Issue by rezabaktash** [davidsandberg/facenet#127]
I tried to run facenet_train.py using 150*150 images for both train and validation and set --image_size to 150, but i faced an error.  Any Idea?
Error log:
File "src/facenet_train.py", line 234, in train
    emb_array[lab,:] = emb
ValueError: shape mismatch: value array of shape (810,128) could not be broadcast to indexing result of shape (90,128)

**Comment by davidsandberg** [comment]
I assume you are using the NN4 model and I don't think that one is designed for that large images. Try another model, like the NN3 or maybe inception_resnet_v1 and it should work better.
