### ISSUE TITLE
dateset overlapping

### ISSUE THREAD

**Issue by tengshaofeng** [davidsandberg/facenet#130]
hi,
    i feel so  excited when i saw your code. you really did a great job.  
but i get 2 questions when i came to the fifth part  Start classifier training in  https://github.com/davidsandberg/facenet/wiki/Classifier-training-of-inception-resnet-v1.

1.  i have not seen the code which transform the dataset  from casia/casia_maxpy_mtcnnpy_182 to casia_maxpy_mtcnnalign_182_160.  did it random crop 160-160 from 182-182 images? and how many 160-160 patches should i crop from one 182-182 image.
2.  you trained the net with facescrub(530 persons)  and CASIA(10575 persons ),  does the two data set  overlap? that means whether exists the same person in 2 datasets.

look forward to your reply.
thank you very much.

**Comment by davidsandberg** [comment]
1. Random cropping is done in the input pipeline so you don't have to worry about that. Just feed the aligned image pathces when you train the model.
2. There are some overlap between the datasets and those overlapping classes will appear as label noise during training.

**Comment by tengshaofeng** [comment]
so i also don't have to worry about the overlapping? just consider it as noise? 
thank you for your reply

**Comment by tengshaofeng** [comment]
hi, 
   sorry to bother you again. Have you cleaned the wrong face detections manually after align_dataset_mtcnn.py?

**Comment by davidsandberg** [comment]
Lately I have trained on casia only and I get roughly the same performance. So this there could be some gains in doing the merge correctly.
However, I did not do any manual cleaning of the training set.

**Comment by ntvy95** [comment]
@davidsandberg 

I'm sorry but can you please clarify what did you mean by "appear as label noise during training"? Did you mean that you will remove all overlapping classes or...? I'm sorry if this question is ridiculous as I'm new to this.

By the way, I have looked at the identity lists of LFW and MS-Celeb-1M and find that they do have mutual identities such as Charlotte Rampling, so my question is: Did you exclude the identities in LFW from MS-Celeb-1M subset that you trained on?

Thank you very much!
