### ISSUE TITLE
model_checkpoint_path is None

### ISSUE THREAD

**Issue by skrew** [davidsandberg/facenet#133]
Hi,

In `facenet.py`, line 381, 

```ckpt_file = tf.train.get_checkpoint_state(model_dir).model_checkpoint_path```

`AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'`

**Comment by lodemo** [comment]
See #40

the get_checkpoint_state(mode_dir) function needs a checkpoint file, by default 'checkpoint' in the model directory, with the in #40 described content.

**Comment by davidsandberg** [comment]
Thanks @lodemo!
I will probably remove the use of get_checkpoint_state in the future since it requires this annoying little file.
