### ISSUE TITLE
'Wrong labels used for evaluation, possibly caused by training examples left in the input pipeline

### ISSUE THREAD

**Issue by liorshk** [davidsandberg/facenet#136]
I get Assertion error:
'Wrong labels used for evaluation, possibly caused by training examples left in the input pipeline'
I am playing with 
```
epoch_size and batch_size
```
But I can't seem to trace down why it happens.
Any tip?

**Comment by davidsandberg** [comment]
Closing this. Reopen if it's still a problem.

**Comment by uzair789** [comment]
ANy updates on why this error tends to occur? I am trying to do LFW evaluation after certain batches and not after every epoch. SO I moved the save and evaluate functions into the train() function.  I can post a more detailed question in a separate post. Should I open a new issue?
