### ISSUE TITLE
Working on batch represent script

### ISSUE THREAD

**Issue by RakshakTalwar** [davidsandberg/facenet#137]
I am working on a batch represent script so that one can generate embeddings given a directory of images and by passing in a model file and output directory.

The script will not automatically pre-process images.

I'm essentially recreating the functionality found in [OpenFace's batch-represent](http://cmusatyalab.github.io/openface/visualizations/#3-generate-representations).

**Comment by RakshakTalwar** [comment]
@davidsandberg 
I've completed the work for the batch-represent script.

How may I obtain permission to push my local branch as a remote one so we can do a pull request?

Thank you

**Comment by hermitman** [comment]
Hi, @RakshakTalwar: could you share your batch-represent script? Thanks,

**Comment by RakshakTalwar** [comment]
@hermitman Sure I'll just fork the project and submit a pull request

**Comment by RakshakTalwar** [comment]
I've submitted a PR

https://github.com/davidsandberg/facenet/pull/184

Here's the code on my account for the meantime.

https://github.com/RakshakTalwar/facenet/blob/master/util/batch_represent.py

**Comment by hermitman** [comment]
@RakshakTalwar Awesome, thanks!!

**Comment by RakshakTalwar** [comment]
Has been merged.

batch-represent.py can be found in tmp/

**Comment by sidgan** [comment]
Hi @RakshakTalwar 

Thanks for your batch_represent.py file that can be used at inference. Any thoughts on how to use Openface-like batching while using the training scripts of @davidsandberg 's Facenet?
