### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by capital-G** [davidsandberg/facenet#145]
Currently you have a couple of problems if you want to run this on Python 3, par example:

`(facereg) *@lenovo:~/facereg/facenet/src$ python align/align_dataset_mtcnn.py ~/facereg/faces/cannes/ ~/facereg/faces/align_cannes/
/home/*/anaconda3/envs/facereg/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Creating networks and loading parameters
Traceback (most recent call last):
  File "align/align_dataset_mtcnn.py", line 142, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "align/align_dataset_mtcnn.py", line 54, in main
    pnet, rnet, onet = align.detect_face.create_mtcnn(sess, '../../data/')
  File "/home/*/facereg/facenet/src/align/detect_face.py", line 277, in create_mtcnn
    pnet = PNet({'data':data})
  File "/home/*/facereg/facenet/src/align/detect_face.py", line 72, in __init__
    self.setup()
  File "/home/*/facereg/facenet/src/align/detect_face.py", line 216, in setup
    (self.feed('data') #pylint: disable=no-value-for-parameter, no-member
  File "/home/*/facereg/facenet/src/align/detect_face.py", line 102, in feed
    if isinstance(fed_layer, basestring):
NameError: name 'basestring' is not defined
(facereg) *@lenovo:~/facereg/facenet/src$ 
`

Maybe it's possible to have Python3 Support as well, would be happy to contribute!

**Comment by davidsandberg** [comment]
Hi @capital-G,
I have been a bit lazy merging PRs but I think this will be fixed by both #128 and 129. Please check back later.
