### ISSUE TITLE
the purpose of using identity operation

### ISSUE THREAD

**Issue by ugtony** [davidsandberg/facenet#147]
Hi @davidsandberg ,
    
The identify operations are used several times in your code, 
for example, in facenet_train_classifier.py:
```python
image_batch = tf.identity(image_batch, 'image_batch')
image_batch = tf.identity(image_batch, 'input')
label_batch = tf.identity(label_batch, 'label_batch')
```
I don't understand why the identity operations are needed. 
The program goes well(in terms of executability) without those three lines.

This stackoverflow [webpage](http://stackoverflow.com/questions/34877523/in-tensorflow-what-is-tf-identity-used-for) discuss some cases of using identity, but seems irrelevant to the case here.

**Comment by davidsandberg** [comment]
Hi @ugtony,
The reason for using it in this case is to be able to name the tensors that can later be used to feed data at that point, if you for example would like to bypass the input pipeline.
Then you can do something like 
`tf.get_default_graph().get_tensor_by_name("image_batch:0")`

**Comment by ugtony** [comment]
I see, thanks.
