### ISSUE TITLE
Error using the model provided in readme

### ISSUE THREAD

**Issue by lilac** [davidsandberg/facenet#15]
I tried using the model as shared on the readme via google drive link, but encountered an error when verify the model with lfw dataset.

```
tensorflow.python.framework.errors.NotFoundError: Tensor name "incept5b/in4_conv1x1_55/weights/ExponentialMovingAverage" not found in checkpoint files model/20160306-500000/model.ckpt
```

I ran the verify command as `python ./src/validate_on_lfw.py --model_dir model/20160306-500000/ --lfw_pairs data/pairs.txt --lfw_dir data/lfw\:dlib-affine-sz\:96/`

**Comment by davidsandberg** [comment]
Hi,
Yes, I have noticed the problem but I haven't looked closer at why it happens. I uploaded a new model that is more or less equivalent to the 20160306 but trained using a much more up-to-date version of the code. It can be found on:
https://drive.google.com/file/d/0B5MzpY9kBtDVVFRyU2JCVmZXUEk/view?usp=sharing
I hope it works for you!

**Comment by lilac** [comment]
@davidsandberg Thanks for the quick response. The new model works. Thank you so much.

Also, the readme does not mention the model dir needs to contain a file named `checkpoint`, which contains text format of a proto buffer file. I inferred this by reading through the code. I think it's really helpful to add this instruction on readme, besides providing the model file.

**Comment by davidsandberg** [comment]
Great that it worked! I will add some more info regarding the checkpoint file next time up update the README.

**Comment by rob-rowe** [comment]
Would it be possible to provide the checkpoint text proto buffer file mentioned by lilac? That would be very helpful.

**Comment by davidsandberg** [comment]
For me the checkpoint file looks like this:
model_checkpoint_path: "/home/david/models/facenet/model-20160506.ckpt-500000"
all_model_checkpoint_paths: "/home/david/models/facenet/model-20160506.ckpt-500000"

**Comment by rob-rowe** [comment]
@davidsandberg Perfect. That was all I needed to make the validate_on_lfw.py work (with appropriate changes to the file path). Thank you for your quick response and for making this code public!
