### ISSUE TITLE
load pretrained model cost so much time

### ISSUE THREAD

**Issue by tengshaofeng** [davidsandberg/facenet#150]
hi,
   " Metagraph file: model-20170131-234652.meta
     Checkpoint file: model-20170131-234652.ckpt-250000"
when i load the model above, it takes me nearly half an hour to finish it. 
and you ?
i am looking forward your reply.
thanks

**Comment by tengshaofeng** [comment]
@davidsandberg

**Comment by davidsandberg** [comment]
Hi @tengshaofeng!
It takes quite long time for me as well, but not as long as 30 minutes. Maybe 5 minutes or something like that.
If you are not going to continue training the model and want to reduce the loading time you can experiment with [freeze_graph.py](https://github.com/davidsandberg/facenet/blob/master/src/freeze_graph.py). I know that the frozen graph is much quicker to import but it requires some changes in how the model is loaded.

**Comment by mhaghighat** [comment]
Hi @davidsandberg,

I tried freezing the graph with [freeze_graph.py](https://github.com/davidsandberg/facenet/blob/master/src/freeze_graph.py), but it gives this error:

tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value InceptionResnetV1/Repeat_1/block17_4/Branch_1/Conv2d_0b_1x7/BatchNorm/moving_variance/ExponentialMovingAverage

**Comment by RyanLiuNtust** [comment]
Can someone explain why loading this model need take more than one mins?
and I also used freeze_graph.py but it seems some error here.

**Comment by mhaghighat** [comment]
Thank you, @davidsandberg, for your suggestion to use .pb models and updating the freeze_graph.py.
Both CASIA-WebFace and MS-Celeb-1M models' size reduce significantly to 92.3MB.

**Comment by mhaghighat** [comment]
As a side note, should the line 53 of the  [freeze_graph.py](https://github.com/davidsandberg/facenet/blob/master/src/freeze_graph.py) be:
`output_node_names = 'embeddings'`
or
`output_node_names = 'embeddings:0'`
?

**Comment by mhaghighat** [comment]
The resulted frozen graph cannot be loaded later. I opened a new [issue](https://github.com/davidsandberg/facenet/issues/161) about it if you please take a look at.

Thanks

**Comment by tengshaofeng** [comment]
Hi @davidsandberg, thanks for your reply so much.  you said that  it requires some changes in how the model is loaded, do you mean that restoring  directly from model-20170131-234652.ckpt-250000.ckpt without 'tf.train.import_meta_graph'. And I should construct a graph include all the variables in code?

**Comment by davidsandberg** [comment]
@tengshaofeng: How to do this is described in #161 (using tf.import_graph_def).

**Comment by NeamahAlskeini** [comment]
Hi all
I know how to upload FacNet and extract features from  classification layer, but I want to extract features from a specific layer, like max-pooling layer.
Could you please advice how to do that?
Thank you a lot..
