### ISSUE TITLE
align_dataset_mtcnn.py  too slow

### ISSUE THREAD

**Issue by mgy89** [davidsandberg/facenet#151]
hi, @davidsandberg 
I follow your tutorial, use `align_dataset_mtcnn.py` to face_detection
But, the speed is very slow, around 8 images / second, the average image size is 40K.

I read your code `detect_face.py`, find that:
-  it only process **one image each time**, (pnet, onet, rnet)

and the intermediate calculation is quiet complex, I can not modify it to a batch process version..

Could you give me some advice?
- How to modify the code to batch version?
- Or other speed up methods?

Thank you very much

**Comment by davidsandberg** [comment]
Hi @mgy89!
I agree that creating a batch version is not very simple.
Have you tried running the alignment using separate subprocesses (as described on this [page](https://github.com/davidsandberg/facenet/wiki/Classifier-training-of-inception-resnet-v1))?
It would be something like this:
```
for N in {1..4}; do python align_dataset_mtcnn.py ~/datasets/casia/CASIA-maxpy-clean/ ~/datasets/casia/casia_maxpy_mtcnnpy_182 --image_size 182 --margin 44 --random_order --gpu_memory_fraction 0.25 & done
```
If that doesn't work for you another option would be run multiple instances of [detect_face.py](https://github.com/davidsandberg/facenet/blob/master/src/align/detect_face.py) using python's multithreading functionality, e.g.:
`thread.start_new_thread ( function, args[, kwargs] )`

**Comment by artur-trzesiok** [comment]
I tried to implement bulk processing in mtcnn. Indeed the problem is not easy. Please look at the pull request: https://github.com/davidsandberg/facenet/pull/154

**Comment by pribadihcr** [comment]
Hi @artur-trzesiok,

How to use the bulk_detect_face. I got None result in ret.

**Comment by mgy89** [comment]
@davidsandberg  
Of course I tried using multi processes.
And I found that the main bottleneck is **CPU**!
Using tensorflow(CPU) version, the speed is (6-7) images / second  each process.

Because the code use too much numpy etc matrix calculation.
I am try to implement a pure GPU calculation version.

**Comment by artur-trzesiok** [comment]
I agree. My improvement is only a first step. The most important thing right now is to do rescale images on GPU.

**Comment by Cospel** [comment]
Hello I have save issue as @pribadihcr , none result from batch processing :(.

Any update from @mgy89  with GPU calculation?

**Comment by pribadihcr** [comment]
@Cospel,

Did you solved the none problem?

**Comment by Cospel** [comment]
I think the problem is that method:

    def bulk_detect_face(images, detection_window_size_ratio, pnet, rnet, onet, threshold, factor):

takes param 'detection_window_size_ratio', so it is size ratio and not window size as it is in the 

    def detect_face(img, minsize, pnet, rnet, onet, threshold, factor):

**Comment by pribadihcr** [comment]
@Cospel,

Could you give the example ?.

**Comment by taewookim** [comment]
@davidsandberg  

I tried multi-threading... almost ZERO performance gain

**Comment by taewookim** [comment]
align.detect_face.bulk_detect_face() seems to do the trick

FYI: First value in return tuple values is bounding box
