### ISSUE TITLE
Subset of MS-Celeb-1M

### ISSUE THREAD

**Issue by Wzz798** [davidsandberg/facenet#157]
Hi, the results on LFW seems very promising, and I am very interested in reproducing and improving the result. It's mentioned that training involved a subset of MS-Celeb-1M. Is there a download link for this subset?  

Many thanks!

**Comment by davidsandberg** [comment]
Hi @Wzz798!
There is no plan to make this subset available for download, but instead the plan is to write a wiki page on the training. Not sure when this will happen though.
