### ISSUE TITLE
About the parameter of "epoch_size"

### ISSUE THREAD

**Issue by puppet101** [davidsandberg/facenet#158]
Hi, @davidsandberg 
Thanks for your excellent work. I am training the "CASIA_maxpy_clean" dataset according to your instruction of "Classifier training of inception resnet v1" step by step. But I find that in the facenet_train_classifier.py there is a parameter "epoch_size", which means number of batches per epoch.
Its value is 1000 by default. As the default batch size is 90 and the total number of images is more than 400k.
So do you use this default value for your training on CASIA dataset?  If yes, does it mean that only 90k images will be used in each epoch?
Thank you~

**Comment by davidsandberg** [comment]
Hi @puppet101,
The naming of this parameter is a bit sloppy and currently it mainly dictates how often validation on LFW is conducted. I have had this set to 1000 for all my runs and indeed the whole dataset will be used.

**Comment by puppet101** [comment]
Ok, thanks for your kindly reply~ It does solve my problem!
