### ISSUE TITLE
What is the signature_name of provided models?

### ISSUE THREAD

**Issue by qmaruf** [davidsandberg/facenet#163]
What is the[ signature_name](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/mnist_client.py#L147) for these pretrained models? I've figured out that the [name](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/mnist_client.py#L146) is `facenet`. Not sure about the `signature_name` though.

Used the following code to extract `signature_name`. [Source](http://www.nqbao.com/blog/2017/01/tensorflow-retrieving-serving-signatures-from-an-exported-model/)

```
 with tf.Session() as sess:
        print (sess)
        new_saver = tf.train.import_meta_graph('/home/ml2/maruf/tf_server/serving/facenet-export/001575852/export.meta')
        graph = tf.get_default_graph()
        print (graph.get_all_collection_keys())
        pb = graph.get_collection("serving_signatures")
        print (pb)
        signatures = manifest_pb2.Signatures()
        print (signatures)
```

```
<tensorflow.python.client.session.Session object at 0x7f6f80411110>
[u'cond_context', u'trainable_variables', u'variables', u'losses', u'regularization_losses', u'train_op', u'queue_runners', u'moving_average_variables', u'summaries', u'model_variables']
[]
```

It seems, I am not using the correct API.
Any suggestion?

**Comment by davidsandberg** [comment]
I don't have any experience with Tensorflow Serving but all the code for training the models are in the repo so based on that it should be possible to figure out.

**Comment by qmaruf** [comment]
Thanks
