### ISSUE TITLE
about the result

### ISSUE THREAD

**Issue by sunjia2015** [davidsandberg/facenet#17]
Hi!
I have use a small dataset, which has 600 different people, to train the network.
I have not change any code and parameters as given by you. 
I test the result after 150 epoch on LFW and accuary is only 0.66.
I used the code from OpenFace to do face aligment and I have not change the image to bgr image.
Instead , I feed the network with rgb images. (Have you done the same thing?)
Do you think the accuray is alright? In order to get good performance, do you have any advice?
Thank you for sharing the code.

**Comment by davidsandberg** [comment]
I have tried to use facescrub with ~500 different people and ~80000 images in total. I'm not sure how well this model performed on LFW, but a link to the model can be found on the readme page. But perhaps you need to use an older version of facenet to be able to load the model. I don't think the model performed much better than 0.66, so my feeling is that your performance is alright.
There is nothing in the model that requires a certain ordering of the color channels, but of course the same ordering has to be used for both training and testing. 
To improve performance i think the best way forward is to try with a larger dataset. For example it would be interesting to try the VGG Face dataset (http://www.robots.ox.ac.uk/~vgg/data/vgg_face/).

**Comment by sunjia2015** [comment]
Thank you for your quick reply.
I will try to use an bigger dataset to train the network and let you konw the result.
