### ISSUE TITLE
ImportError: No module named facenet

### ISSUE THREAD

**Issue by Mikebarson** [davidsandberg/facenet#170]
Hi! I'm following this article right [here](https://github.com/davidsandberg/facenet/wiki/Validate-on-lfw) about validating the lfw. I'm getting an import error 

`ImportError: No module named facenet`

I've installed the requirements.txt and I have also installed the setup.py, but I'm still getting this error. Any ideas on how to fix this? 
Thanks.

**Comment by Mikebarson** [comment]
Alright, I've actually found the answer here:

https://github.com/davidsandberg/facenet/issues/106

Just a side note for simplicity sake...the src for the facenet.py is under 

`facenet/build/src`

the file in is actually `facenet.py`

**Comment by KanchanIIT** [comment]
set your python home path as
"export $PYTHONHOME=the location of the facenet.py"
