### ISSUE TITLE
AttributeError: 'module' object has no attribute 'unpack'

### ISSUE THREAD

**Issue by Mikebarson** [davidsandberg/facenet#174]
Hi! I'm getting the same error [here](https://github.com/davidsandberg/facenet/issues/165).

I've already pulled the changes for the compatibility with Tensorflow r1.0. But I'm getting this error:

`Traceback (most recent call last):
  File "facenet_train_classifier.py", line 461, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "facenet_train_classifier.py", line 122, in main
    for filename in tf.unpack(filenames):
AttributeError: 'module' object has no attribute 'unpack'`

Any ideas to fix this? Thanks!

**Comment by stringmoon** [comment]
tf.pack and tf.unpack are deprecated in favor of tf.stack and tf.unstack.

**Comment by Mikebarson** [comment]
@stringmoon Should I just change the tf.unpack to unstack then?

**Comment by Mikebarson** [comment]
If you're still encountering this error please clone the new version of facenet.
