### ISSUE TITLE
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

### ISSUE THREAD

**Issue by Mikebarson** [davidsandberg/facenet#175]
Hi! I'm still following this wiki [here](https://github.com/davidsandberg/facenet/wiki/Classifier-training-of-inception-resnet-v1). I had an issue with running the ` facenet_train_classifier.py `
command. First it was about unpack found [here](https://github.com/davidsandberg/facenet/issues/174). According to @stringmoon the unpack was replaced in favor of unstack. So changed that line to unpack. 

It worked but now I'm getting this error message.

`TypeError: Expected int32, got list containing Tensors of type '_Message' instead.`

Any fixes?

**Comment by davidsandberg** [comment]
It looks very much like your on an old revision. Can you please check that again. Thanks!

**Comment by Mikebarson** [comment]
@davidsandberg Thanks! Strange that git pull wasn't able to get all your changes. I had to clone the whole for it to work. Thanks for the quick reply!
