### ISSUE TITLE
facenet_train_classifier.py takes so long to train

### ISSUE THREAD

**Issue by Mikebarson** [davidsandberg/facenet#177]
Hi! I was just wondering why it takes super long to train a classifier in facenet. 

Is it because of my machine? My machine is a Macbook Air. If so, where can I do this that may be in a server online so that i could leave it there while it's running? It's affecting the performance of my machine you see. Right now 1 epoch took around 2 days to complete. It's that slow. Can I do this in an online server so that it would be much faster and will not affect the performance of my machine? 

Thanks!

**Comment by davidsandberg** [comment]
Yes, it's a big model and unless you can run on a GPU it will take some time. I know that it's possible to setup so that you can run tensorflow on e.g. Amazon cloud, but I haven't tried it.

**Comment by Mikebarson** [comment]
@davidsandberg I'm actually using my own dataset to train the model. I'm following this [one](https://github.com/davidsandberg/facenet/wiki/Classifier-training-of-inception-resnet-v1) with the Classifier Traininf of Inception.

**Comment by Mikebarson** [comment]
@davidsandberg Hi! I think Google Cloud ML can be used to deploy facenet. I'm currently trying to follow [this article](https://cloud.google.com/blog/big-data/2016/12/how-to-train-and-classify-images-using-google-cloud-machine-learning-and-cloud-dataflow) but I'm a bit confused on how to pass the args. Can you help?

**Comment by Mikebarson** [comment]
Hi @davidsandberg Can you please check my post on stackoverflow [here](http://stackoverflow.com/questions/42603427/error-when-submitting-job-training-in-google-cloud-ml/42612041#42612041). I was able to successfully submit a training job on Google Cloud ML but there was an import error. 

This import error did not occur while I was training locally...but when training on Google Cloud ML there was an error. Can you check it out? Thanks!
