### ISSUE TITLE
import error！

### ISSUE THREAD

**Issue by gudandenanhaier** [davidsandberg/facenet#178]
hi, @davidsandberg
I follow your tutorial, use align_dataset_mtcnn.py to face_detection， but encounted problems:
import facenet
ImportError: No module named facenet
the reason is?

**Comment by awyl** [comment]
I guess you are new to python as I am.

Try adding the following after import sys
sys.path.append("../")

See also #170

**Comment by gudandenanhaier** [comment]
thank you! I solved the problem.
