### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by kaishijeng** [davidsandberg/facenet#18]
I have used facescrub dataset and dlib to align them before running facenet_train.py
After 1st epoch of training and it has the following error at validation below. Do you know what is wrong?

Traceback (most recent call last):
  File "./facenet_train.py", line 274, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py                                                                   ", line 30, in run
    sys.exit(main(sys.argv))
  File "./facenet_train.py", line 144, in main
    global_step, embeddings, loss, 'validation', summary_writer)
  File "./facenet_train.py", line 212, in validate
    image_paths, num_per_class = facenet.sample_people(dataset, nrof_people, FLA                                                                   GS.images_per_person)
  File "/mnt/2TB/src/facenet/facenet/src/facenet.py", line 606, in sample_people
    class_index = class_indices[i]
IndexError: index 52 is out of bounds for axis 0 with size 52

**Comment by davidsandberg** [comment]
Hi,
It looks like there are too few images in the validation set.
The function "sample_people" tries to sample 45 persons with 40 images per person. But if some of the classes in the dataset contains less than 40 images more classes will be used to get 45*40 images.
One way to solve it would be to use a smaller "train_set_fraction", e.g. 0.8 or something. Then the validation set will be larger. Another (ugly) way could be to change the seed. Then a different set of classes will be included in the validation set, and perhaps these classes together will have enough images for validation.

**Comment by kaishijeng** [comment]
Can I reduce 40 images/person? What is the impact of doing this?
Thanks

**Comment by davidsandberg** [comment]
Yes, reducing either the number of images per person or the number of people would help to solve the problem. But i'm not sure how it will affect the training. Also, you need to make sure that you can get a whole number of batches, i.e. that people_per_batch*images_per_person = batch_size * n, where n is an integer.

**Comment by Shubhamcl** [comment]
Also making sure the batch_size and people_per_batch are multiples of 3 helps.

**Comment by PoonamZ** [comment]
@davidsandberg I put --lfw_dir place empty as i don't want to see the validation accuracy. Then also I am getting the error as below, 

Traceback (most recent call last):
  File "src/train_tripletloss.py", line 486, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/train_tripletloss.py", line 186, in main
    args.embedding_size, anchor, positive, negative, triplet_loss)
  File "src/train_tripletloss.py", line 212, in train
    image_paths, num_per_class = sample_people(dataset, args.people_per_batch, args.images_per_person)
  File "src/train_tripletloss.py", line 327, in sample_people
    class_index = class_indices[i]
IndexError: index 4 is out of bounds for axis 0 with size 4

**Comment by KumailHussain** [comment]
@PoonamZ @davidsandberg  any findings for the above error, I am getting the same error, Thanks in advance. I have training set of 21 images each class

**Comment by PoonamZ** [comment]
@KumailHussain I didn't get any solution for this.

**Comment by sassiaicha** [comment]
Hi, I am using "train_tripletloss.py" as training algorithm, but every time I try to run it, I get the error below and 
 I can't find any solution for that, please help me. Thank you in advance.

Restoring pretrained model: ./models/20170512-110547/model-20170512-110547.ckpt-250000
Traceback (most recent call last):
  File "train_tripletloss.py", line 493, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "train_tripletloss.py", line 192, in main
    args.embedding_size, anchor, positive, negative, triplet_loss)
  File "train_tripletloss.py", line 218, in train
    image_paths, num_per_class = sample_people(dataset, args.people_per_batch, args.images_per_person)
  File "train_tripletloss.py", line 333, in sample_people
    class_index = class_indices[i]
IndexError: index 2 is out of bounds for axis 0 with size 2

**Comment by RohanMathur17** [comment]
@sassiaicha  , was facing the same error during training. Same Index error. Looks like you have chosen only 2 classes which is causing the problem.
I myself was using only 10 custom classes with 3 images for each. But when I increased my dataset (used LFW dataset for training), the code ran for training. Maybe try increasing your dataset.
