### ISSUE TITLE
How to deploy face recognization service?

### ISSUE THREAD

**Issue by hardfish82** [davidsandberg/facenet#181]
Hi, @davidsandberg 
I'd like to deploy a face recognization service as a test by tensorflow serving. The service will accept a face image as the input and output the recognization result. But I found it's a little difficult to export a tensorflow serving model because the face detection and alignment can't work with the tensor inputs. davidsandberg, do you have some plans about this? Or can you give some advice about how to deploy the service?
Thanks.

**Comment by davidsandberg** [comment]
Hi @hardfish82!
Currently I don't have a plan to do this. To make a full implementation of MTCNN in Tensorflow would probably take some time. But maybe it can be ran using tf.py_func(...) which can run python functions in tensorflow. I have for example used that function to perform random rotations in `facenet_train_classifier.py`.

**Comment by YouZengLi** [comment]
help !when i prepare to deploy the MTCNN model,I find that to  translating the dectect process in to tensorflow graph is difficult ,because of many python op and serving it make some key python middle value freeze and the serving output all the same.    hope to get slutions,Thanks

**Comment by mohammaduzair9** [comment]
@hardfish82  i want to deploy facenet on serving too. Can you please guide me how do i export this model for serving. It will be very helpful if you can give your code. I will be giving it a cropped image containing only face and it should give me its embeddings. Thanks
