### ISSUE TITLE
doubt about "Align the LFW dataset"

### ISSUE THREAD

**Issue by chenghaozheng** [davidsandberg/facenet#183]
When I follow the tutorial to run the alignment, 
    for N in {1..4}; do python align_dataset_mtcnn.py ~/datasets/lfw/raw ~/datasets/lfw/lfw_mtcnnpy_160 --image_size 160 --margin 32 --random_order --gpu_memory_fraction 0.25 & done
I got the final result as follows:
    Total number of images: 13233
    Number of successfully aligned images: 3463
I am doubt that it is the right result. If wrong, what is the right result?

**Comment by chenghaozheng** [comment]
thank you, it works! @dkozlov

**Comment by caocuong0306** [comment]
Hi guys,

I wonder could you align whole 13233 images? In my case, there are a lot of images unable to be aligned, causing missing pairs when evaluation. I obtain 12784/13233 images.
