### ISSUE TITLE
Facial clustering/verification

### ISSUE THREAD

**Issue by kevinlu1211** [davidsandberg/facenet#187]
I'm trying to develop a pipeline that groups photos with the same faces, similar to the one that Apple and Android has developed. I have taken a brief look over the Facenet code, and unless I have missed it, there doesn't seem to be a module which can be used for facial clustering/verification.

I was wondering if someone more familiar with the codebase could provide me with some advice as to how I should go forwards with this project.

So I was wondering what would be the steps to take, right now here are mine:

1. Write an extension to the Face Alignment module align_dataset_mtcnn.py for it to detect multiple faces in an image. I tested the module, and it seems that it is not able to extract multiple faces (although I may be wrong please correct me if I am).

2. Using the 20170216-091149 model, get rid of the classification layer and use the pre-trained embedding layer to cluster the faces.

3. Use some form of distance measure to classify whether an individual is in a photo.

**Comment by hkhatri241** [comment]
Simply use the emeddings that facenet gives you to cluster the images.

**Comment by kevinlu1211** [comment]
I'm under the impression that facenet although facenet does give the embedding, it only does it for one face at a time. Therefore, wouldn't I still have the problem of having to detect the faces during the face alignment phase prior to getting the embedding using facenet?

**Comment by lodemo** [comment]
Face detection and feature extraction are different things, and not perfomed with a single model. 
As in _align_dataset_mtcnn.py,_ face detection and alignment is done with the MTCNN network model, after this feature extraction is performed on the detected faces, with use of the Facenet model.

Face detection(MTCNN) > feature extraction(Facenet) > feature clustering

**Comment by kevinlu1211** [comment]
I understand that, the thing is that right now the MTCNN model is only able to detect one face in an image with multiple faces, so this is the problem that I am currently facing.

**Comment by lodemo** [comment]
Not quite, when you look at the page of the MTCNN model https://kpzhang93.github.io/MTCNN_face_detection_alignment/index.html
 you can see its actually able to detect a big number of faces in an image, your problem is probably that the current facenet code is not extracting every face individually. You can change that in the condition handling nrof_faces bigger than 1.

**Comment by kevinlu1211** [comment]
Oh I will try that I've spent the past week trying to read the code thank you for your tip!

**Comment by shivamms** [comment]
Where do I get the feature extraction model model-20170216-091149.pb?
