### ISSUE TITLE
validate_on_lfw.py error

### ISSUE THREAD

**Issue by MiloAnthony** [davidsandberg/facenet#188]
when I run validate_on_lfw.py (I don't modify the code),it turns out : 
Traceback (most recent call last):
  File "validate_on_lfw.py", line 115, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "validate_on_lfw.py", line 82, in main
    images = facenet.load_data(paths_batch, False, False, image_size)
  File "/home/anthony/facenet/src/facenet.py", line 264, in load_data
    img = crop(img, do_random_crop, image_size)
  File "/home/anthony/facenet/src/facenet.py", line 241, in crop
    image = image[(sz1-sz2+v):(sz1+sz2+v),(sz1-sz2+h):(sz1+sz2+h),:]
TypeError: unsupported operand type(s) for -: 'int' and 'Dimension'

and here is the code:
def crop(image, random_crop, image_size):
    if image.shape[1]>image_size:
        sz1 = image.shape[1]//2
        sz2 = image_size//2
        print(sz1)
        if random_crop:
            diff = sz1-sz2
            (h, v) = (np.random.randint(-diff, diff+1), np.random.randint(-diff, diff+1))
        else:
            (h, v) = (0,0)
        image = image[(sz1-sz2+v):(sz1+sz2+v),(sz1-sz2+h):(sz1+sz2+h),:]
    return image
how could I solve it ?

**Comment by RakshakTalwar** [comment]
@MiloAnthony Try pulling the repository. I resolved this issue in my commit.

**Comment by MiloAnthony** [comment]
@RakshakTalwar Thanks! But here comes another one:
Traceback (most recent call last):
    far = float(false_accept) / float(n_diff)
ZeroDivisionError: float division by zero

So I add a judgement:
if n_diff == 0:
     far = 0.0
else:
     far = float(false_accept) / float(n_diff)

and then the problem changed:
File "validate_on_lfw.py", line 94, in main
    eer = brentq(lambda x: 1. - x - interpolate.interp1d(fpr, tpr)(x), 0., 1.)
ValueError: A value in x_new is above the interpolation range.

After I deleted the code above,I got the accuracy except validation rate ,AUC .

Accuracy: 0.950+-0.150
Validation rate: 0.00000+-0.00000 @ FAR=0.00000
Area Under Curve (AUC): 0.000

**Comment by eustcPL** [comment]
@MiloAnthony  my problem is
 Accuracy: 1.000+-0.001
Validation rate: 0.00000+-0.00000 @ FAR=0.00000
Area Under Curve (AUC): 0.000
...
ValueError: A value in x_new is above the interpolation range.
How did you solve the problem?
Thank you in advance

**Comment by ZxqSoftWare** [comment]
So...have you solved this issue? I'm trying to validate my own dataset, but I met "float division by zero" too......wanna cry.

**Comment by MiloAnthony** [comment]
@eustcPL Sorry, I did not pay attention to the issue for a long time.  @ZxqSoftWare you can check my comment above or the pulling made by RakshakTalwar.

**Comment by hungnv21292** [comment]
hi @zxq-creations 

Have you solved the problem yet?

I have same problem and I shuffle the order list in my pairs.txt

**Comment by Rasoul20sh** [comment]
> @MiloAnthony Try pulling the repository. I resolved this issue in my commit.
Hi @MiloAnthony 
I have the same problem and I can not find your solution! How I can solve it?
thanks a lot

**Comment by MiloAnthony** [comment]
@Rasoul20sh Thanks very much.

**Comment by MiaNguyen26** [comment]
> @RakshakTalwar Thanks! But here comes another one: Traceback (most recent call last): far = float(false_accept) / float(n_diff) ZeroDivisionError: float division by zero
> 
> So I add a judgement: if n_diff == 0: far = 0.0 else: far = float(false_accept) / float(n_diff)
> 
> and then the problem changed: File "validate_on_lfw.py", line 94, in main eer = brentq(lambda x: 1. - x - interpolate.interp1d(fpr, tpr)(x), 0., 1.) ValueError: A value in x_new is above the interpolation range.
> 
> After I deleted the code above,I got the accuracy except validation rate ,AUC .
> 
> Accuracy: 0.950+-0.150 Validation rate: 0.00000+-0.00000 @ FAR=0.00000 Area Under Curve (AUC): 0.000

Hi, Have you solved this problem? 
I did like this but still got "ZeroDivison Error" after have deleted the code you had mentioned
