### ISSUE TITLE
Import Error when Training on Google Cloud ML

### ISSUE THREAD

**Issue by Mikebarson** [davidsandberg/facenet#193]
Hi @davidsandberg Can you please check my post on stackoverflow [here](http://stackoverflow.com/questions/42603427/error-when-submitting-job-training-in-google-cloud-ml/42612041#42612041). I was able to successfully submit a training job on Google Cloud ML but there was an import error.

This import error did not occur while I was training locally...but when training on Google Cloud ML there was an error. Can you check it out? Thanks!

**Comment by davidsandberg** [comment]
Closing for now. Reopen if needed.
