### ISSUE TITLE
run python download_vgg_face_dataset.py 

### ISSUE THREAD

**Issue by molyswu** [davidsandberg/facenet#194]
python download_vgg_face_dataset.py 

~/tensorflow/tf-notebooks/facenet/src# python download_vgg_face_dataset.py 
usage: download_vgg_face_dataset.py [-h] [--output_format {png,jpg}]
                                    [--image_size IMAGE_SIZE]
                                    dataset_descriptor
download_vgg_face_dataset.py: error: too few arguments

Thanks for your help!

**Comment by davidsandberg** [comment]
Did you try to give some parameters to the script?
According to the help text in the script:
`dataset_descriptor`: Directory containing the text files with the image URLs. Image files will also be placed in this directory.
