### ISSUE TITLE
Check failed: 1 == NumElements() (1 vs. 1792)Must have a one element tensor in Tensorflow C++

### ISSUE THREAD

**Issue by hipitt** [davidsandberg/facenet#197]
Part of the code:
```python
image_data = misc.imread(image_path)

image_batch = graph.get_tensor_by_name("input:0")
phase_train_placeholder = graph.get_tensor_by_name("phase_train:0")
embeddings = graph.get_tensor_by_name("embeddings:0")

feed_dict = {image_batch: np.expand_dims(image_data, 0), phase_train_placeholder: False}
rep = sess.run(embeddings, feed_dict=feed_dict)
```

C++ code:
model: model-20170131-234652.ckpt-250000.pb

```c++
cv::Mat image = cv::imread("0002.png", CV_LOAD_IMAGE_COLOR);
const float * source_data = (float*) image.data;
Tensor image_batch(DT_FLOAT, TensorShape({1, 160, 160, 3}));
auto input = image_batch.tensor<float, 4>();
for (int y = 0; y < height; ++y) {
    const float* source_row = source_data + (y * width * depth);
    for (int x = 0; x < width; ++x) {
        const float* source_pixel = source_row + (x * depth);
        for (int c = 0; c < depth; ++c) {
            const float* source_value = source_pixel + c;
            //std::cout << *source_value << std::endl;
            input(0, y, x, c) = *source_value;
        }
    }
}
Tensor phase_train(DT_BOOL, TensorShape());
phase_train.scalar<bool>()() = false;

std::vector<std::pair<string, tensorflow::Tensor>> inputs = {
    { "input:0", image_batch },
    { "phase_train:0", phase_train },
};    
std::vector<Tensor> outputs;
Status run_status = session->Run(inputs, {"embeddings:0"}, {}, &outputs);
```

**Error:**

F tensorflow/core/framework/tensor.cc:493] Check failed: 1 == NumElements() (1 vs. 1792)Must have a one element tensor

Process finished with exit code 6

What is the reason for err?

**Comment by hipitt** [comment]
@davidsandberg 
@mhaghighat

**Comment by hipitt** [comment]
@mhaghighat 
@davidsandberg 
Please ....

**Comment by mhaghighat** [comment]
@hipitt:
Just remove the ":0"s from the node names. Please try:

```
std::vector<std::pair<std::string, tensorflow::Tensor>> inputs = {
	{ "input", image_batch },
	{ "phase_train", phase_train },
};
std::vector<tensorflow::Tensor> outputs;
tensorflow::Status runStatus = session->Run(inputs, {"embeddings"}, {}, &outputs);
```

BTW, do not forget to resize the input image to 160x160 and to convert it to float (e.g., CV_32FC3), before copying its data into the Tensor:

`image.convertTo(image, CV_32FC3);`

**Comment by davidsandberg** [comment]
Hi @hipitt,
It's also important to do prewhitening of the image and also having the correct scaling of the face before cropping the image.

**Comment by mhaghighat** [comment]
Thanks, @davidsandberg.
I was doing the alignment using Dlib and OpenCV, similar to the one in [align_dlib.py](https://github.com/davidsandberg/facenet/blob/master/src/align/align_dlib.py). After I saw your comment, I looked at the differences. Will it work if I just add the margins of 22 pixels to the bounding box detected by dlib? Then I will apply the affine transformation and pre-whitening.

**Comment by hipitt** [comment]
Hi @mhaghighat @davidsandberg , 
Thank you very much for the answer, I made a stupid mistake, did not find the wrong key code, and did not stick out.
```c++
    auto output_c = outputs[0].scalar<float>(); // Error herr
    std::cout << outputs[0].DebugString() << "\n";
    std::cout << output_c() << "\n"; 
```

**Comment by AnshanTJU** [comment]
@hipitt , I use the code you published. However, the features extracted are  not same with python code. Do you have same problem?
