### ISSUE TITLE
Load Frozen module on validate_on_lfw.py, 'input', does not exist in the graph

### ISSUE THREAD

**Issue by solderzzc** [davidsandberg/facenet#198]
I frozen the 20170216-091149 module/checkpoint by src/freeze_graph.py, then modified validate_on_lfw.py to load it. It threw the following error message:

> Traceback (most recent call last):
  File "src/validate_on_lfw.py", line 132, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/validate_on_lfw.py", line 82, in main
    images_placeholder = tf.get_default_graph().get_tensor_by_name("input:0")
  File "/Users/simba/Projects/MachineLearning/venv-1.0/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2622, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/Users/simba/Projects/MachineLearning/venv-1.0/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2473, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/Users/simba/Projects/MachineLearning/venv-1.0/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2515, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'input:0' refers to a Tensor which does not exist. The operation, 'input', does not exist in the graph."

The facenet code is the latest.

My modification is:

        def load_graph(frozen_graph_filename):
            with tf.gfile.GFile(frozen_graph_filename, "rb") as f:
                graph_def = tf.GraphDef()
                graph_def.ParseFromString(f.read())

            with tf.Graph().as_default() as graph:
                tf.import_graph_def(
                    graph_def,
                    input_map=None,
                    return_elements=None,
                    op_dict=None,
                    producer_op_list=None
                )

            return graph
.......

            # Load the model
            #print('Model directory: %s' % args.model_dir)
            #meta_file, ckpt_file = facenet.get_model_filenames(os.path.expanduser(args.model_dir))

            #print('Metagraph file: %s' % meta_file)
            #print('Checkpoint file: %s' % ckpt_file)
            #facenet.load_model(args.model_dir, meta_file, ckpt_file)

            graph = load_graph('../models/20170216-091149/model-20170216-091149.pb')

            # Get input and output tensors
            images_placeholder = tf.get_default_graph().get_tensor_by_name("input:0")`

**Comment by solderzzc** [comment]
... it added a 'import' prefix by the tf.import_graph_def.

**Comment by lolz0r** [comment]
@solderzzc What do you mean "it" added a "import prefix"? I am seeing the same problem.

**Comment by solderzzc** [comment]
By printing out the op name, you will see the prefix something like
'prefix/input', the you need change the code to use the new input name.

lolz0r <notifications@github.com>于2017年3月14日 周二下午3:57写道：

**Comment by lolz0r** [comment]
@thanks!

**Comment by HaoXiedo** [comment]
@solderzzc @lolz0r  I'm sorry to bother you, but I meet the same problem. there is nothing when I run [m.values() for m in tf.get_default_graph().get_operations()]. what should I do?

**Comment by testings2017** [comment]
any ideas! I have the same problem with:
images_placeholder = tf.get_default_graph().get_tensor_by_name("input:0")
