### ISSUE TITLE
compare.py fails loading from the prebuilt checkpoint

### ISSUE THREAD

**Issue by delip** [davidsandberg/facenet#20]
This is my invocation
`$ python compare.py --model_dir ~/facenet/ --dlib_face_predictor ~/dlib-18.18/shape_predictor_68_face_landmarks.dat --image1 ~/s1 --image2 ~/s2`

The directory (~/facenet) has the prebuilt checkpoint file `model-20160506.ckpt-500000`. Upon running this, I see this:

```
Traceback (most recent call last):
  File "compare.py", line 73, in <module>
    main()
  File "compare.py", line 53, in main
    raise ValueError('Checkpoint not found')
ValueError: Checkpoint not found
```

**Comment by davidsandberg** [comment]
I think the problem is that a text file named "checkpoint" should reside in the ~/facenet directory, and this file should "point" to the model file. I tried to discribe this, including the contents of the checkpoint file, in the readme file. Please try that and get back to me with the result.

**Comment by delip** [comment]
That fixed the problem. Thanks!
