### ISSUE TITLE
Does anyone have the lfw training set that is already aligned?

### ISSUE THREAD

**Issue by kevinlu1211** [davidsandberg/facenet#202]
Hello, I was wondering if anyone had the lfw training set that is already aligned using `align_dataset_mtcnn.py`? If you do would you be kind enough to upload it somewhere so I could download it? I don't know why but it has taken my laptop over 14 hours to align the faces and it just crashed :(

**Comment by yanmenglu** [comment]
yes,I have done it.

**Comment by kevinlu1211** [comment]
Would you be able to upload it online to Google Drive or something so that I could download it ?

**Comment by yanmenglu** [comment]
I download it from http://vis-www.cs.umass.edu/lfw/lfw.tgz,you can try.And then you use align_datasets_mtcnn.py align that.

**Comment by kevinlu1211** [comment]
I mean could I get the images that have already been aligned? I have the lfw dataset, but I want the dataset that was created by running `python src/align/align_dataset_mtcnn.py ...`

**Comment by yanmenglu** [comment]
Oh,I don't know that.
