### ISSUE TITLE
origin face rectangle

### ISSUE THREAD

**Issue by mickeyandkaka** [davidsandberg/facenet#203]
New here, I wonder how to get the face box position of the origin image?

**Comment by davidsandberg** [comment]
Have you looked at for example compare.py and the call to 
`bounding_boxes, _ = align.detect_face.detect_face(img, minsize, pnet, rnet, onet, threshold, factor)`?
This will give you the bounding boxes for detected faces.

**Comment by mickeyandkaka** [comment]
I will check that, thank you!
