### ISSUE TITLE
Error After Training

### ISSUE THREAD

**Issue by ekarem** [davidsandberg/facenet#204]
I experience an error when training as classifier process is finished: 

tensorflow/core/kernels/queue_base.cc:294] _0_input_producer/fraction_of_32_full/fraction_of_32_full: Skipping cancelled enqueue attempt with queue not closed
W tensorflow/core/kernels/queue_base.cc:302] _2_FIFOQueueV2: Skipping cancelled dequeue attempt with queue not closed
W tensorflow/core/kernels/queue_base.cc:302] _2_FIFOQueueV2: Skipping cancelled dequeue attempt with queue not closed
W tensorflow/core/kernels/queue_base.cc:302] _2_FIFOQueueV2: Skipping cancelled dequeue attempt with queue not closed
W tensorflow/core/kernels/queue_base.cc:302] _2_FIFOQueueV2: Skipping cancelled dequeue attempt with queue not closed

Is there anyone who has the error?

**Comment by davidsandberg** [comment]
Hi,
These are warnings that are harmless but a bit annoying. They come from closing the session (which was not done before) but I didn't find a way to make them disappear. I think you can safely ignore them for now.

**Comment by Bananajia** [comment]
I have the same problem! And the program stopped, it seems to be an error not warning

**Comment by andyhx** [comment]
HI,I got the same issue,any way to solved it?the program stopped

**Comment by Bananajia** [comment]
@andyhx because of your paras that " --max_nrof_epochs 80" so your program ended up in epoch[80]

**Comment by andyhx** [comment]
@Bananajia ,thank your ,I will modify it to check  that

**Comment by kay-max** [comment]
@andyhx did fixing the " --max_nrof_epochs 80" value solve the issue for you?
