### ISSUE TITLE
confused about the input size

### ISSUE THREAD

**Issue by jinglingzhua** [davidsandberg/facenet#206]
Hi, it seems that inception_resnet_v1.py is identical to the model(X) as mentioned in the paper. But X's input size is (299,299,3), and in the guide of training inception_resnet_v1, the input size is (160,160,3). Did the accuracy 99.3 come from Inception-Resnet-v1.py, or modified version?

**Comment by Rivrr** [comment]
@jinglingzhua hey , is nn4.py the corresponding code to the _NN2_ model described in the paper?  if so , what are the other _nn3.py/nn2.py_ codes used for?
thanks!

**Comment by davidsandberg** [comment]
@jinglingzhua: The accuracy 99.3% was achieved using the inception_resnet_v1.py as it is.
@Rivrr: nn4.py is NN4 and nn2.py is NN2. ;-)
