### ISSUE TITLE
Which clustering algorithm to use for clustering face embeddings

### ISSUE THREAD

**Issue by kevinlu1211** [davidsandberg/facenet#209]
Hello all, 
I was able to extract the facial features which are the face embeddings in 128 dimension space. I was wondering which kind of clustering algorithm would you suggest to cluster similar faces?

**Comment by vaxin** [comment]
I also have the same question!
I saw someone used KNN to classify specified number of persons.
I think that there should exist one unsupervised method to auto cluster faces.
Assume that we have a camera in your office, everyday there are many familiar faces appears meanwhile there are some strange faces appears. What we expect is that the watcher can easily recall familiar faces, and will notice there is a new face appears today.

**Comment by kevinlu1211** [comment]
I've been reading up on rank order clustering you can have a look at that, although I think the deep features that the MTCNN -> Facenet pipeline produces aren't useful for clustering. Right now I'm trying to align the faces prior to feeding them into the network to see if that helps

**Comment by xf4fresh** [comment]
I think that you can try t-sne. I found in the experiment that embeddings of the training set does happen in the case of clustering. This can be observed with tensorboard, using t-sne.

**Comment by kevinlu1211** [comment]
Hmm okay I will try reducing the dimensions then clustering them, thanks for the advice!

**Comment by xf4fresh** [comment]
@kevinlu1211 
Is there a good explanation about the dimensions of the embedding? I am currently doing the speaker verification.  Reference to a paper, he used a 16-dimensional. I used here with 32 dimensions.

**Comment by kevinlu1211** [comment]
If it isn't too much trouble could you post a screenshot of your clusterings? Thanks!

**Comment by kevinlu1211** [comment]
@xf4fresh which embeddings are you referring to? If you are talking about the face embeddings from facenet then iirc I believe that using 128 dimensions is arbitrary. In [this paper](https://arxiv.org/pdf/1604.00989.pdf) they use 300 dimensions for the embeddings. And also, what is speaker verification?

**Comment by davidsandberg** [comment]
Closing this for now. Reopen if needed.
