### ISSUE TITLE
the accuracy is 81.3% which is much lower than 91%

### ISSUE THREAD

**Issue by twinsyssy1018** [davidsandberg/facenet#21]
hi, i  used the model you given and ran the validate_on_lfw.py directly  , but the result is not as good as yours, is  there something wrong?  thank you

**Comment by davidsandberg** [comment]
Hi,
My guess would be that this has something to do with face alignment of the test set.
Did you align the LFW dataset using the [Openface](https://cmusatyalab.github.io/openface/models-and-accuracies/) approach?

**Comment by twinsyssy1018** [comment]
i had not do alignment like that.i will try.thank you
