### ISSUE TITLE
Problem  when batch processing face detection

### ISSUE THREAD

**Issue by Cospel** [davidsandberg/facenet#211]
Hi, thank you for this great project.

When I am playing with face detecetion from:
src/align/detect_face.py

i can successfully use detect_face method to detect all faces in picture.

However when i am trying bulk method what I am getting is always list of None.

Any idea where can be problem?

**Comment by davidsandberg** [comment]
Maybe @artur-trzesiok can help out with this one?

**Comment by davidsandberg** [comment]
Closing this one since it's discussed in #151.
