### ISSUE TITLE
what is difference between facenet_train.py and facenet_train_classifier.py?

### ISSUE THREAD

**Issue by SeanGuoXuan** [davidsandberg/facenet#213]
I am new to facenet. I don't fully understand both architectures. By default, both architectures use nn4 model. They both generate embeddings. It seems they both used to classify faces by giving 128-d outcome per face.  Can we say facenet_train_classifier.py applies center loss vs facenet_train.py applies triplet loss? They serve the same purpose but difference approach?

**Comment by davidsandberg** [comment]
Hi @SeanGuoXuan,
That's exsctly how I would describe how it as well.

**Comment by fedyunin** [comment]
Hello! Just started learn your project. There is question:

Is it correct: 
1. I run facenet train (facenet_train.py or facenet_train_classifier.py) on known dataset. As result I will have classifier which can be used for recognize faces. 
2. I get new image of person and then evaluate it in this classifier for recognize image and decide is person known or not. 

Thanks!

**Comment by pavankumarkatakam** [comment]
Hi @fedyunin, I'm also thinking like you. is that correct @davidsandberg. I'm also just learning tensorflow.

**Comment by davidsandberg** [comment]
Yed, I couldn't have said it better myself.
