### ISSUE TITLE
KeyError: "The name 'embeddings:0' refers to a Tensor which does not exist. The operation, 'embeddings', does not exist in the graph."

### ISSUE THREAD

**Issue by tigerhaolu727** [davidsandberg/facenet#216]
Hi David,

Thanks for your hard work on this facenet project. I got a problem. I trained my own model without providing LFW_dir. When I try to restore the model and run validation on lfw, I got the an error "KeyError: "The name 'embeddings:0' refers to a Tensor which does not exist. The operation, 'embeddings', does not exist in the graph."" Do you have any idea why this is happening? In the classifier, if the lfw_dir is not provide it doesn't calculate the embedding, is that reason? Do I have to alway provide lfw_dir?

**Comment by davidsandberg** [comment]
Hi,
If you have the line
```
        embeddings = tf.nn.l2_normalize(bottleneck, 1, 1e-10, name='embeddings')
```
in your training script you should get the embeddings tensor as well.
