### ISSUE TITLE
align_dataset_mtcnn.py the detect_face always get bounding_boxes shape is 0,9? 

### ISSUE THREAD

**Issue by zhly0** [davidsandberg/facenet#217]
why align_dataset_mtcnn.py the detect_face always get bounding_boxes shape is 0,9? the data set is celebv1

**Comment by davidsandberg** [comment]
It looks like detect_face does not find any faces. I have used align_dataset_mtcnn successfully on that dataset so it should work. Have you tried aligning some other dataset, like LFW?

**Comment by zhly0** [comment]
@davidsandberg ,thanks for reply,It is my fault lead to this,I change the function:align.detect_face.imresample,the original is use cv2,but I already have skimage in my ubuntu,so I use skimage's resize instead,but skimage's resize function automatic normalize the data into 0.0-1.0,but cv2 normalize the data into 0-255,after I process the data,it runs well.thanks again
