### ISSUE TITLE
futex block 

### ISSUE THREAD

**Issue by FangJianHust** [davidsandberg/facenet#219]
during my training, tensorflow is block ,and user strace -f to find it block at   futex(0x7ffc0d7e34ec, FUTEX_WAIT_PRIVATE, 1, NULL ,how to solve it?

**Comment by davidsandberg** [comment]
I don't think this is related to facenet.
It looks like you are experiencing [this problem](https://github.com/tensorflow/tensorflow/issues/5882).

**Comment by FangJianHust** [comment]
during training, one thread exit because `decode_png` cause to exception, so I think whether this thread hold some lock and not release it, cause others wait forever?
