### ISSUE TITLE
Why the same face get different embedding?

### ISSUE THREAD

**Issue by LeoMiter** [davidsandberg/facenet#224]
.
├── 0
│   ├── a
│   │   └── AP_0001.png
│   ├── gallery.npy
│   └── signatures.npy
├── 1
│   ├── a
│   │   ├── AP_0001.png
│   │   └── BA_0001.png
│   ├── gallery.npy
│   └── signatures.npy
├── 2
│   ├── a
│   │   ├── AP_0001.png
│   │   └── BB_0003.png
│   ├── gallery.npy
│   └── signatures.npy
├── 3
│   ├── a
│   │   ├── AP_0001.png
│   │   └── BC_0007.png
│   ├── gallery.npy
│   └── signatures.npy
├── 4
│   ├── a
│   │   ├── AP_0001.png
│   │   └── BD_0006.png
│   ├── gallery.npy
│   └── signatures.npy
└── c.py

The directory like above, then run tmp/batch_represent.py in each directory.

python program like this
```python
import numpy as np

if __name__ == "__main__":

    l0 = np.load("./0/gallery.npy")
    l1 = np.load("./1/gallery.npy")
    l2 = np.load("./2/gallery.npy")
    l3 = np.load("./3/gallery.npy")
    l4 = np.load("./4/gallery.npy")

    e0 = np.load("./0/signatures.npy")
    e1 = np.load("./1/signatures.npy")
    e2 = np.load("./2/signatures.npy")
    e3 = np.load("./3/signatures.npy")
    e4 = np.load("./4/signatures.npy")

    print(l0)
    print('-')
    print(l1)
    print('-')
    print(l2)
    print('-')
    print(l3)
    print('-')
    print(l4)

    print("e0[0] - e1[0] = {}".format(np.linalg.norm(e0[0] - e1[0])))
    print("e1[0] - e1[0] = {}".format(np.linalg.norm(e1[0] - e1[0])))
    print("e1[0] - e2[0] = {}".format(np.linalg.norm(e1[0] - e2[0])))
    print("e1[0] - e3[0] = {}".format(np.linalg.norm(e1[0] - e3[0])))
    print("e1[0] - e4[0] = {}".format(np.linalg.norm(e1[0] - e4[0])))
```
The output result is:
```
['AP_0001.png']
-
['AP_0001.png'
 'BA_0001.png']
-
['AP_0001.png'
 'BB_0003.png']
-
['AP_0001.png'
 'BC_0007.png']
-
['AP_0001.png'
 'BD_0006.png']

e0[0] - e1[0] = 2.8998083190657884e-07
e1[0] - e1[0] = 0.0
e1[0] - e2[0] = 0.0
e1[0] - e3[0] = 0.0
e1[0] - e4[0] = 0.0
```

Why the same face (AP_0001.png)  get different embedding?

**Comment by nizhib** [comment]
Don't ever expect total equality of floating point numbers calculations results.

0.0000003-different embeddings as in your example are meant to be equal obviously.

**Comment by LeoMiter** [comment]
@nizhib Thank you so much.
