### ISSUE TITLE
Total number of images: 0 Number of successfully aligned images: 0

### ISSUE THREAD

**Issue by mrhajbabaei** [davidsandberg/facenet#229]
Hi,

I ran the align_dataset_mtcnn.py with this instruction: python align_dataset_mtcnn.py AlGore AlGore-aligned/
and this message appeared:
Total number of images: 0
Number of successfully aligned images: 0
my database is LFW and I use 8 jpg files of Al_Gore folder. can you guide me what makes this result?

best,

**Comment by Ayiruss** [comment]
I think you need to provide folders containing images inside AlGore folder. You can't have the images directly inside the folder.

**Comment by mukesh8101997** [comment]
hi
i m getting same error.i have compiled 
python src/align/align_dataset_mtcnn.py ~/datasets/lfw/raw ~/datasets/lfw/lfw_mtcnnpy_160 --image_size 160 --margin 32
and getting error -- 
/home/mukesh/datasets/lfw/raw/lfw/Paul_Kagame: [Errno 21] Is a directory: '/home/mukesh/datasets/lfw/raw/lfw/Paul_Kagame'
Total number of images: 5749
Number of successfully aligned images: 0
please help.
thanks

**Comment by Ayiruss** [comment]
you have the directory Paul_Kagame in the path /home/mukesh/datasets/lfw/raw/lfw/,  delete it and try again

**Comment by mukesh8101997** [comment]
thanks but in directory Paul_kagame and all other directories, only images are there.

**Comment by Ayiruss** [comment]
then you have to change the code to handle the subfolders that contains images otherwise it won't work

**Comment by mukesh8101997** [comment]
okay, thanks
