### ISSUE TITLE
i have two images,how do i know they are the same person

### ISSUE THREAD

**Issue by zhuchangjiang** [davidsandberg/facenet#230]

**Comment by qisanyijiu** [comment]
应该认识汉字吧，src目录下由个compare.py文件，运行它就可以了，你需要在命令行中指定保存模型文件的文件夹和你的两张图片，或者你可以修改这两个参数的默认值，直接运行

**Comment by qisanyijiu** [comment]
不过你是九天之前就问的，现在应该已经解决了问题了吧

**Comment by zhuchangjiang** [comment]
@qisanyijiu compare.py 出来的结果都是批量规范化的。输入 A B 两个人的照片运行 和输入三个人的照片运行出来的结果是不一样的

**Comment by qisanyijiu** [comment]
compare.py出来的结果是抽出这些人脸的特征之后，计算每两张人脸之间的欧式距离，根据论文，相同人脸的阀值为1.1左右，如果欧式距离小于1.1，就是同一个人，但是根据我的实验，如果用欧式距离区分，效果并不是很好，对于一些很相似的人，他们之间的欧式距离在0.95到1.1之间。

**Comment by qisanyijiu** [comment]
还有一个方法在测试lfw的那个python代码中，他会直接根据文本文件中给定图片对来返回是否是同一个人，然后计算平均正确率（在lfw测试得到的正确率大概在99%左右），你可以更改一下那份代码，直接输出bool值来判断是否是同一个人，因为代码我没有阅读，所以不能给你更详细的解决方法，请见谅。

**Comment by qisanyijiu** [comment]
或者，可以用训练好的模型抽出模型，然后一个小的数据集来训练联合贝叶斯作为分类器，参考deepid的方法，如果你有更好的想法，我们可以一起讨论

**Comment by zhuchangjiang** [comment]
+542741650 q

**Comment by MiloAnthony** [comment]
@qisanyijiu 我按照你的那个方法计算欧式距离 但不过准确率还是不那么高，用分类器学习错误率比欧氏距离更高。可以留个联系方式 讨论一下嘛?

**Comment by qisanyijiu** [comment]
415143407

**Comment by qisanyijiu** [comment]
我在lfw测试的正确率在98%

**Comment by zhuchangjiang** [comment]
@MiloAnthony  @qisanyijiu
