### ISSUE TITLE
error when I run validate_on_lfw.py

### ISSUE THREAD

**Issue by lizhiyuanUSTC** [davidsandberg/facenet#233]
Hey, guys. When I trying to run  validate_on_lfw.py, it returns an error 

The name 'input:0' refers to a Tensor whick does not exist. The operation, 'input', does not exist in the graph.

How to fix this?

**Comment by xf4fresh** [comment]
This is  because the tensor name has changed. You can try this
`images_placeholder = tf.get_default_graph().get_tensor_by_name("batch_join:0")`
