### ISSUE TITLE
compute center loss should be divided by the batch size? 

### ISSUE THREAD

**Issue by facerless** [davidsandberg/facenet#237]
You code did not divided  batch size when compute center loss, and did not set weight decay for center loss layer.

**Comment by davidsandberg** [comment]
Yes, you're right that the center loss should be divided by the batch size. But this only affect the value of the parameter so I haven't bothered to change it.
Not sure if weight decay should be used for the estimates of the centers though.

**Comment by davidsandberg** [comment]
Fixed in 1a9461ee113568d799ca8c43c66f3cf1cb46b353.
