### ISSUE TITLE
No OpKernel was registered to support Op 'FIFOQueueV2' with these attrs.

### ISSUE THREAD

**Issue by apollo-time** [davidsandberg/facenet#238]
I had freeze the pre-traind model 20170216-091149 using by freeze_graph.py and got facenet.pb.
And I'm trying to load it on Android but I got error "No OpKernel was registered to support Op 'FIFOQueueV2' with these attrs."
`"No OpKernel was registered to support Op 'FIFOQueueV2' with these attrs.  Registered devices: [CPU], Registered kernels:\n  <no registered kernels>\n\n\t [[Node: batch_join/fifo_queue = FIFOQueueV2[capacity=1440, component_types=[DT_FLOAT, DT_INT64], container=\"\", shapes=[[160,160,3], []], shared_name=\"\"]()]]"`
How can I use this model on Android?

**Comment by apollo-time** [comment]
I already freeze without phase_train. Thanks.

**Comment by lciruelo** [comment]
did you fix `No OpKernel was registered to support Op 'FIFOQueueV2' with these attrs` ?

**Comment by frizk123** [comment]
Hi, @apollo-time ! How did you freeze the model without phase_train? Thanks!

**Comment by mourice** [comment]
How did you freeze the model without phase_train?
