### ISSUE TITLE
Restoring pre-trained model error

### ISSUE THREAD

**Issue by yobibyte** [davidsandberg/facenet#24]
Hi! I'm trying to use pre-trained model, but I get the following error during restoring:

```bash
NotFoundError: Tensor name "incept4a/in1_conv1x1_75/batch_norm/cond/incept4a/in1_conv1x1_75/batch_norm/moments/moments_1/mean/ExponentialMovingAverage" not found in checkpoint files model-20160506.ckpt-500000
```

Can you help me with this?

**Comment by davidsandberg** [comment]
Hi!
Sorry for the delayed response...
Which revision of the facenet repository are you running?
From the error message it looks like a tensor name between the stored model and the creation of the network differs.
I just tried with the [latest](https://github.com/davidsandberg/facenet/commit/ed8f39714412cc325ec8655f61b42478d607c478) and that one seems to work fine.

**Comment by yobibyte** [comment]
Hi, David!

Thank you, it works now. I would also like to ask some questions about the implementation details. Do you have time? Should I do it here in the comments? Or email/skype/facebook is better?

**Comment by davidsandberg** [comment]
Hi,
Great that it works!
Feel free to ask questions in this thread.

**Comment by yobibyte** [comment]
The main question is about training loop [here](https://github.com/davidsandberg/facenet/blob/master/facenet/src/facenet_train.py). 

* On line 147 you start iterating over the epochs and for every epoch you call train() function. 
* On line 175 you start iterating over the batches
* but for some reason from line 202 you iterate over batches again.

Why do you need to iterate over batches inside every batch iteration?

**Comment by davidsandberg** [comment]
This is a little confusing in the code and has to do with the fact that the facenet paper uses a batch size of 40*45 examples. But this requires quite a bit of GPU memory and to still be able to train using 40*45 examples the batch is split into fragments and processed sequentially in the code.

**Comment by yobibyte** [comment]
Got it. Thanks. Have you tried smaller batches? Does it dramatically affect the performance?

**Comment by yobibyte** [comment]
Okay. Thanks for all the comments.
