### ISSUE TITLE
An Error in validate_on_lfw.py

### ISSUE THREAD

**Issue by HappyLuffy** [davidsandberg/facenet#242]
Hi, when I run validate_on_lfw.py ,I meet an error:
       KeyError: u'VariableV2'
I don't know how to solve the problem now

**Comment by davidsandberg** [comment]
Hi,
Which version of tensorflow are you running?
This problem was reported in #195 but was fixed when using TF 1.0.

**Comment by HappyLuffy** [comment]
Yes, the problem is solved. Thank you very much.
