### ISSUE TITLE
Incompatible shapes caused by tf.reshape

### ISSUE THREAD

**Issue by sun9700** [davidsandberg/facenet#244]
In model graph definition, like nn4.py, the output is flattened by tf.reshape with hard-code dimension 
however, it causes error for arbitrary size input images:
InvalidArgumentError (see above for traceback): Incompatible shapes: [750,896] vs. [30,896]
	 [[Node: sub_29 = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](dropout/mul, Gather)]]
	 [[Node: total_loss/_591 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_37166_total_loss", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]

the  hard-code dimension 
 net = tf.reshape(net, [-1, 896])
may be replaced with:
 net = tf.contrib.layers.flatten(net)

**Comment by davidsandberg** [comment]
Hi,
Since I don't have time to support this model it will most likely be removed soon. It should really be rewritten using slm but I don't have time for that.

**Comment by sun9700** [comment]
@davidsandberg  You really did a good job! 3x
