### ISSUE TITLE
run on osx

### ISSUE THREAD

**Issue by hanbim520** [davidsandberg/facenet#245]
1,I have do "sudo pip install -r requirement.txt" 
and run "python setup.py install"

2.error: 
abcdeMacBook-Pro:facenet abc$ python setup.py build
running build
running build_py
package init file 'test/__init__.py' not found (or not a regular file)
package init file 'test/__init__.py' not found (or not a regular file)

3.I copy __init__.py to test/
abcdeMacBook-Pro:facenet abc$ python setup.py build
running build
running build_py
copying test/__init__.py -> build/lib/test
4.Error:
abcdeMacBook-Pro:facenet abc$ python test/train_test.py 
Traceback (most recent call last):
  File "test/train_test.py", line 30, in <module>
    import facenet_train
ImportError: No module named facenet_train
abcdeMacBook-Pro:facenet abc$ 

I don't know why.

**Comment by davidsandberg** [comment]
Hi,
Have you tried foillowing the tutorial in e.g. [Validate on LFW](https://github.com/davidsandberg/facenet/wiki/Validate-on-LFW)?

**Comment by hanbim520** [comment]
Sorry, did not see this article before, and now it can work properly. thank you very much.

**Comment by hanbim520** [comment]
closed #245
