### ISSUE TITLE
how can compare.py use frozen model

### ISSUE THREAD

**Issue by dianesong** [davidsandberg/facenet#248]
hi, i have frozen model 20170216-091149 with freeze_graph.py, and get the frozen model facenet.pb. I want to load facenet.pb in the compare.py. how can i integrate the facenet.pb into the code of compare.py?

the code in the  compare.py is as follows:
```
          # Load the model
            #print('Model directory: %s' % args.model_dir)
           # meta_file, ckpt_file = facenet.get_model_filenames(os.path.expanduser(args.model_dir))
           # print('Metagraph file: %s' % meta_file)
           # print('Checkpoint file: %s' % ckpt_file)
            #facenet.load_model(args.model_dir, meta_file, ckpt_file)
            graph = load_graph(args.model_dir)
            print('end of loading model')

            # Get input and output tensors
            #images_placeholder = tf.get_default_graph().get_tensor_by_name("input:0")
            #embeddings = tf.get_default_graph().get_tensor_by_name("embeddings:0")
            #phase_train_placeholder = tf.get_default_graph().get_tensor_by_name("phase_train:0")
            images_placeholder = graph.get_tensor_by_name("input:0")
            embeddings = graph.get_tensor_by_name("embeddings:0")
            phase_train_placeholder = graph.get_tensor_by_name("phase_train:0")
```

the load_graph() is:
```
def load_graph(frozen_model_filename):
# We load the protobuf file from the disk and parse it to retrieve the
# unserialized graph_def
    with tf.gfile.GFile(frozen_model_filename, "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
    # Then, we can use again a convenient built-in function to import a graph_def into the
    # current default Graph
    with tf.Graph().as_default() as graph:
        tf.import_graph_def(
            graph_def,
            input_map = None,
            return_elements = None,
            #name = "prefix",
            op_dict = None,
            producer_op_list = None
        )
    return graph
```

it errors.
```
Traceback (most recent call last):
  File "src/compare.py", line 165, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/compare.py", line 58, in main
    images_placeholder = graph.get_tensor_by_name("input:0")
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework
\ops.py", line 2563, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)

  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework
\ops.py", line 2414, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework
\ops.py", line 2456, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'input:0' refers to a Tensor which does not exist. The opera
tion, 'input', does not exist in the graph."
```

**Comment by MaartenBloemen** [comment]
I did it the following way which works for me
```python
# Unpersists graph from file
    with tf.gfile.FastGFile("/home/maarten/Documents/facenet/data/20170216-091149/frozen_graph.pb", 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        _ = tf.import_graph_def(graph_def, name='')

    with tf.Session() as sess:
        # Get input and output tensors
        images_placeholder = sess.graph.get_tensor_by_name("input:0")
        embeddings = sess.graph.get_tensor_by_name("embeddings:0")
        phase_train_placeholder = sess.graph.get_tensor_by_name("phase_train:0")

        # Run forward pass to calculate embeddings
        feed_dict = {images_placeholder: images, phase_train_placeholder: False}
        emb = sess.run(embeddings, feed_dict=feed_dict)
...
```
I hope this can be of any help to you.

**Comment by dianesong** [comment]
thank you very much! it's work!

**Comment by kmonachopoulos** [comment]
When I inference an image ('image shape', (1, 128, 128, 3)), I get (0, 128) embeddings, but when i print I get [ ]. Does anyone facing this??

**Comment by bilalahmed381** [comment]
I have train model with embedding size 256 and now I freeze the model and try to run inference on it but it giving me this error.

my code:
```
import tensorflow as tf
import numpy as np


with tf.gfile.FastGFile("models/facenet/20200224-145059_freeze/facenet.pb", 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        _ = tf.import_graph_def(graph_def, name='')

image = np.array(np.random.random_sample((160,160,3)))
print("Input image shape:",image.shape)

with tf.Session() as sess:
    # Get input and output tensors
    images_placeholder = sess.graph.get_tensor_by_name("input:0")
    embeddings = sess.graph.get_tensor_by_name("embeddings:0")
    phase_train_placeholder = sess.graph.get_tensor_by_name("phase_train:0")

    # Run forward pass to calculate embeddings
    feed_dict = {images_placeholder: [image], phase_train_placeholder: False}
    emb = sess.run(embeddings, feed_dict=feed_dict)
    print(emb.shape)
```
Error:
```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
~/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

~/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320 

~/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408 

InvalidArgumentError: Matrix size-incompatible: In[0]: [1,0], In[1]: [1792,256]
	 [[{{node InceptionResnetV1/Bottleneck/MatMul}} = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](InceptionResnetV1/Logits/Dropout/cond/Merge, InceptionResnetV1/Bottleneck/weights/read)]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-6-20fb5e919f3a> in <module>
     10     # Run forward pass to calculate embeddings
     11     feed_dict = {images_placeholder: [image], phase_train_placeholder: False}
---> 12     emb = sess.run(embeddings, feed_dict=feed_dict)
     13     print(emb.shape)

~/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    927     try:
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:
    931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1150     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1151       results = self._do_run(handle, final_targets, final_fetches,
-> 1152                              feed_dict_tensor, options, run_metadata)
   1153     else:
   1154       results = []

~/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1326     if handle is None:
   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1328                            run_metadata)
   1329     else:
   1330       return self._do_call(_prun_fn, handle, feeds, fetches)

~/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1346           pass
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 
   1350   def _extend_graph(self):

InvalidArgumentError: Matrix size-incompatible: In[0]: [1,0], In[1]: [1792,256]
	 [[node InceptionResnetV1/Bottleneck/MatMul (defined at <ipython-input-2-0d4b6ab0cb3a>:9)  = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](InceptionResnetV1/Logits/Dropout/cond/Merge, InceptionResnetV1/Bottleneck/weights/read)]]

Caused by op 'InceptionResnetV1/Bottleneck/MatMul', defined at:
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/asyncio/base_events.py", line 427, in run_forever
    self._run_once()
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/asyncio/base_events.py", line 1440, in _run_once
    handle._run()
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tornado/ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tornado/gen.py", line 787, in inner
    self.run()
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2855, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2881, in _run_cell
    return runner(coro)
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3058, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3249, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-0d4b6ab0cb3a>", line 9, in <module>
    _ = tf.import_graph_def(graph_def, name='')
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 234, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3440, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3440, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3299, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Matrix size-incompatible: In[0]: [1,0], In[1]: [1792,256]
	 [[node InceptionResnetV1/Bottleneck/MatMul (defined at <ipython-input-2-0d4b6ab0cb3a>:9)  = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](InceptionResnetV1/Logits/Dropout/cond/Merge, InceptionResnetV1/Bottleneck/weights/read)]]
```
Anybody knows the solution kindly share it with me

**Comment by kmonachopoulos** [comment]
> I have train model with embedding size 256 and now I freeze the model and try to run inference on it but it giving me this error.
> 
> my code:
> 
> ```
> import tensorflow as tf
> import numpy as np
> 
> 
> with tf.gfile.FastGFile("models/facenet/20200224-145059_freeze/facenet.pb", 'rb') as f:
>         graph_def = tf.GraphDef()
>         graph_def.ParseFromString(f.read())
>         _ = tf.import_graph_def(graph_def, name='')
> 
> image = np.array(np.random.random_sample((128,128,3)))
> print("Input image shape:",image.shape)
> 
> with tf.Session() as sess:
>     # Get input and output tensors
>     images_placeholder = sess.graph.get_tensor_by_name("input:0")
>     embeddings = sess.graph.get_tensor_by_name("embeddings:0")
>     phase_train_placeholder = sess.graph.get_tensor_by_name("phase_train:0")
> 
>     # Run forward pass to calculate embeddings
>     feed_dict = {images_placeholder: [image], phase_train_placeholder: False}
>     emb = sess.run(embeddings, feed_dict=feed_dict)
>     print(emb.shape)
> ```
> 
> Error:
> 
> ```
> ---------------------------------------------------------------------------
> InvalidArgumentError                      Traceback (most recent call last)
> ~/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
>    1333     try:
> -> 1334       return fn(*args)
>    1335     except errors.OpError as e:
> 
> ~/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
>    1318       return self._call_tf_sessionrun(
> -> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
>    1320 
> 
> ~/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
>    1406         self._session, options, feed_dict, fetch_list, target_list,
> -> 1407         run_metadata)
>    1408 
> 
> InvalidArgumentError: Matrix size-incompatible: In[0]: [1,0], In[1]: [1792,256]
> 	 [[{{node InceptionResnetV1/Bottleneck/MatMul}} = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](InceptionResnetV1/Logits/Dropout/cond/Merge, InceptionResnetV1/Bottleneck/weights/read)]]
> 
> During handling of the above exception, another exception occurred:
> 
> InvalidArgumentError                      Traceback (most recent call last)
> <ipython-input-6-20fb5e919f3a> in <module>
>      10     # Run forward pass to calculate embeddings
>      11     feed_dict = {images_placeholder: [image], phase_train_placeholder: False}
> ---> 12     emb = sess.run(embeddings, feed_dict=feed_dict)
>      13     print(emb.shape)
> 
> ~/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
>     927     try:
>     928       result = self._run(None, fetches, feed_dict, options_ptr,
> --> 929                          run_metadata_ptr)
>     930       if run_metadata:
>     931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)
> 
> ~/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
>    1150     if final_fetches or final_targets or (handle and feed_dict_tensor):
>    1151       results = self._do_run(handle, final_targets, final_fetches,
> -> 1152                              feed_dict_tensor, options, run_metadata)
>    1153     else:
>    1154       results = []
> 
> ~/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
>    1326     if handle is None:
>    1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
> -> 1328                            run_metadata)
>    1329     else:
>    1330       return self._do_call(_prun_fn, handle, feeds, fetches)
> 
> ~/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
>    1346           pass
>    1347       message = error_interpolation.interpolate(message, self._graph)
> -> 1348       raise type(e)(node_def, op, message)
>    1349 
>    1350   def _extend_graph(self):
> 
> InvalidArgumentError: Matrix size-incompatible: In[0]: [1,0], In[1]: [1792,256]
> 	 [[node InceptionResnetV1/Bottleneck/MatMul (defined at <ipython-input-2-0d4b6ab0cb3a>:9)  = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](InceptionResnetV1/Logits/Dropout/cond/Merge, InceptionResnetV1/Bottleneck/weights/read)]]
> 
> Caused by op 'InceptionResnetV1/Bottleneck/MatMul', defined at:
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
>     app.launch_new_instance()
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
>     app.start()
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 505, in start
>     self.io_loop.start()
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 148, in start
>     self.asyncio_loop.run_forever()
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/asyncio/base_events.py", line 427, in run_forever
>     self._run_once()
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/asyncio/base_events.py", line 1440, in _run_once
>     handle._run()
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/asyncio/events.py", line 145, in _run
>     self._callback(*self._args)
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tornado/ioloop.py", line 690, in <lambda>
>     lambda f: self._run_callback(functools.partial(callback, future))
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
>     ret = callback()
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tornado/gen.py", line 787, in inner
>     self.run()
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tornado/gen.py", line 748, in run
>     yielded = self.gen.send(value)
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 365, in process_one
>     yield gen.maybe_future(dispatch(*args))
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
>     yielded = next(result)
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 272, in dispatch_shell
>     yield gen.maybe_future(handler(stream, idents, msg))
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
>     yielded = next(result)
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 542, in execute_request
>     user_expressions, allow_stdin,
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
>     yielded = next(result)
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
>     res = shell.run_cell(code, store_history=store_history, silent=silent)
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
>     return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2855, in run_cell
>     raw_cell, store_history, silent, shell_futures)
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2881, in _run_cell
>     return runner(coro)
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
>     coro.send(None)
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3058, in run_cell_async
>     interactivity=interactivity, compiler=compiler, result=result)
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3249, in run_ast_nodes
>     if (await self.run_code(code, result,  async_=asy)):
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-2-0d4b6ab0cb3a>", line 9, in <module>
>     _ = tf.import_graph_def(graph_def, name='')
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
>     return func(*args, **kwargs)
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 442, in import_graph_def
>     _ProcessNewOps(graph)
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 234, in _ProcessNewOps
>     for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3440, in _add_new_tf_operations
>     for c_op in c_api_util.new_tf_operations(self)
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3440, in <listcomp>
>     for c_op in c_api_util.new_tf_operations(self)
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3299, in _create_op_from_tf_operation
>     ret = Operation(c_op, self)
>   File "/root/anaconda3/envs/mrcnn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
>     self._traceback = tf_stack.extract_stack()
> 
> InvalidArgumentError (see above for traceback): Matrix size-incompatible: In[0]: [1,0], In[1]: [1792,256]
> 	 [[node InceptionResnetV1/Bottleneck/MatMul (defined at <ipython-input-2-0d4b6ab0cb3a>:9)  = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](InceptionResnetV1/Logits/Dropout/cond/Merge, InceptionResnetV1/Bottleneck/weights/read)]]
> ```
> 
> Anybody knows the solution kindly share it with me

Is it possible that you trained on GPU and trying to inference on CPU? or it could be the case that you are using wrong tenor names on inference?

**Comment by bilalahmed381** [comment]
Yes it is possible to train on GPU and test on CPU, I think model input is (160, 160, 3) and you are using (128, 128, 3).
