### ISSUE TITLE
2 questions about compare.py

### ISSUE THREAD

**Issue by MaartenBloemen** [davidsandberg/facenet#250]
Hello,
I have 2 questions about compare.py.
**First:** I know the output is an Euclidean distance matrix, but when is it safe to assume that the distance between two photos is small enough that they are the same person? For example is a distance less than 1 the same person?

**Second:** is there a way to instead of getting the distance matrix as output getting a confidence (percent from 0-100) as output. Does anyone know how to do this?

Thanks in advance for any help!

**Comment by CrowbarKZ** [comment]
1st: You should experiment and come up with some value you are comfortable with, there is no universal threshold. The distance for the same person can vary greatly depending on lighting conditions, photo quality etc. 

2nd: distance matrix consists of float values between 0 and 2 for each pair of pictures. You can remap them to 0-100 by multiplying values by 50.

**Comment by MaartenBloemen** [comment]
@CrowbarKZ Thanks couldn't have wished for a better answer! I have done a bit of experimenting but I didn't realy know what the max distance was so thank you for clearing that up.

**Comment by dianesong** [comment]
the paper of facenet suggests 1.1 for the threshold
