### ISSUE TITLE
process of facenet_train_classifier.py  block when Epoch: [0][999/1000]

### ISSUE THREAD

**Issue by tengshaofeng** [davidsandberg/facenet#252]
hi, @davidsandberg ,
   so sorry to bother you.
I remember I can run facenet_train_classifier.py successfully days ago. But when i try to run it again today, it 
block when batch number is 999. like:
![7 n40qe yxl_dh2 8z 7s](https://cloud.githubusercontent.com/assets/9246739/25266498/e821c0b4-26a3-11e7-97c5-f3fefa297094.png)
It has not reached the breakpoint:

![xg a 7vdt0x1tx z lo 5](https://cloud.githubusercontent.com/assets/9246739/25266642/7476e45e-26a4-11e7-8ef0-5e77ba258635.png)

and this status keep same after several hours. I really can not figure out the problem.
can you help me. thanks.

**Comment by wangzzdeepir** [comment]
I have tried to add some tf.summary.image and tf.summary.histogram into facenet_train_classifier.py and met the exact same problem, I can not locate the issue but it did not hang any more when I remove those summary ops.

**Comment by davidsandberg** [comment]
Hi @tengshaofeng,
Did you solve this one? 
If you don't have anything else to try you can always try to change the line
```
if (batch_number % 100 == 0):
```
to something like
```
if (batch_number % 100 == 10000):
```
This will avoid writing the summaries and then you can see if the problem is related to that.
