### ISSUE TITLE
how can i reduce the time of calculating embeddings in the compare.py

### ISSUE THREAD

**Issue by dianesong** [davidsandberg/facenet#253]
i run the code in compare.py and find that the process of getting emb using sess.run needs 6.5s. How can i do something to reduce the time？

```
    # Run forward pass to calculate embeddings
    feed_dict = {images_placeholder: images, phase_train_placeholder: False}
    emb = sess.run(embeddings, feed_dict=feed_dict)
```
I use the multiprocssing, it also doesn't work.  Can the function sess.run be parallelled? 

```
     pool = multiprocessing.Pool(processes=4)
     pool.apply_async(  emb = sess.run(embeddings, feed_dict=feed_dict)）
```

**Comment by dianesong** [comment]
the time of running function sess.run is 6.5s when I use the frozen model of 20170216-091149. but if i use the model of 20170216-091149, the time of running function sess.run needs 0.9s.

**Comment by anhhoangta** [comment]
could you tell more details about your system and how long do you load the model?

**Comment by anhhoangta** [comment]
I got same problem with you, decreasing time to load model by frozen it by increase time to run sess.run :(

**Comment by dianesong** [comment]
@anhhoangta My system is windows 7 64bit, Intel Xeon CPU E5, RAM 7,99G. the time of loading model is 150s.  and the time of loading frozen model is 12s.

**Comment by anhhoangta** [comment]
@dianesong I think the solution is that we have to training a small model such as in src/models/nn4_small2_v1.py, but we need to change more parameters.
