### ISSUE TITLE
 Where can I get the lfw raw images?

### ISSUE THREAD

**Issue by dianesong** [davidsandberg/facenet#254]
i download the LFW dataset from http://vis-www.cs.umass.edu/lfw/,  the extracted file is not the set of images. where can i get the lfw raw images?

**Comment by davidsandberg** [comment]
Have you tried following the guide on [Validate on LFW](https://github.com/davidsandberg/facenet/wiki/Validate-on-LFW)?

**Comment by dianesong** [comment]
i try the guide on Validate on LFW and get the images, thank you.
