### ISSUE TITLE
Where can I use GPU in facenet?

### ISSUE THREAD

**Issue by anhhoangta** [davidsandberg/facenet#255]
First, thanks for your work, I appreciate it.
Second, I want to make a faces search system so I used your pre-trained model to compare images. But I got problem with the time to load your model, it was too slow. I loaded it on my Macbook pro with 8cores and 16GB RAM, Amazon p2.xlarge with 1 Nvidia Tesla K80 - 12GB RAM, Jetson TX2 with 256 CUDA cores and 8GB RAM. And it was surprisingly that load and predict in my Macbook was fastest. So I have some questions:

1. Where can I use GPU in facenet? Although I tried your recommended in this issues [#208](https://github.com/davidsandberg/facenet/issues/208) with this code in compare.py:
`os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="0"`
but I got same result.

2. Can I train a small model to make it possible to load in NVIDIA Jetson Tx2? Now It cost ~340s to load your pre-trained model and 4s to compare 2 images. It's impossible, in example, to make an identify realtime system. Or do you have any suggestion for realtime recognition on Jetson machine, such as: Openface?

Many thanks.

**Comment by anhhoangta** [comment]
Update: I just frozen model and time to load it decreasing from 104s to 6.9s on amazon p2.xlarge with Nvidia K80.

**Comment by davidsandberg** [comment]
Hi,
For practical applications I would just guess that you would have to have the model resident in memory to be able to run forward passes within a reasonable time.
To use the GPU you should just have to set CUDA_VISIBLE_DEVICES, but my feeling is that if you just have one or a few images the forward pass should be quick compared to loading the model.
