### ISSUE TITLE
图片对比问题

### ISSUE THREAD

**Issue by zhuchangjiang** [davidsandberg/facenet#256]
为什么我对比两张图片的时候距离总是1.9，
compare.py

**Comment by hanbim520** [comment]
abcdeMacBook-Pro:facenet abc$ ls models/
model-20170216-091149.ckpt-250000.data-00000-of-00001
model-20170216-091149.ckpt-250000.index
model-20170216-091149.meta

Images:
0: testData/Anthony_Hopkins_0001.jpg
1: testData/Anthony_Hopkins_0002.jpg

Distance matrix
        0         1     
0    0.0000    0.6463  
1    0.6463    0.0000  

这个是自带的图片进行的对比结果。
