### ISSUE TITLE
Import facenet and detect_face by myself while running align_dataset_mecnn.py?

### ISSUE THREAD

**Issue by XhedvaH** [davidsandberg/facenet#258]
when I run align_dataset_mecnn.py,I found facenet and detect_face are not under the folder.Should I import them by myself?

**Comment by davidsandberg** [comment]
Hi,
Have you added the src folder the your PYTHON_PATH?
Are you running align_dataset_mtcnn.py as described on the wiki, i.e. something like this?
`python src/align/align_dataset_mtcnn.py ~/datasets/lfw/raw ~/datasets/lfw/lfw_mtcnnpy_160 --image_size 160 --margin 32`
You shouldn't have to modify the source code to run this.
