### ISSUE TITLE
when i consfer the 20170216-091149model to a frozen model,i have a problem ,please help

### ISSUE THREAD

**Issue by xidian-xuchen** [davidsandberg/facenet#261]
below is my transfer code:

import os
import tensorflow as tf  
import re
from tensorflow.python.framework import graph_util  

def get_model_filenames(model_dir):
   .....................
def freeze_graph(model_folder):  
    meta_file, ckpt_file = get_model_filenames(model_folder)
    output_graph = "./frozen_model.pb"  
    output_node_names = "embeddings"  
    clear_devices = True       
    saver = tf.train.import_meta_graph(meta_file, clear_devices=clear_devices)  
    graph = tf.get_default_graph()  
    input_graph_def = graph.as_graph_def()  
    with tf.Session() as sess:  
        saver.restore(sess, ckpt_file)  
        output_graph_def = graph_util.convert_variables_to_constants(  sess,   input_graph_def,   
            output_node_names.split(","))   
        with tf.gfile.GFile(output_graph, "wb") as f:  
            f.write(output_graph_def.SerializeToString())  
if __name__ == '__main__':  
    freeze_graph('./models/20170216-091149') 

it did work,i ot the file frozen_model.pb,but when i use this file,igot some errors:
below are my code and error:

    with tf.gfile.FastGFile('./frozen_model.pb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        _ = tf.import_graph_def(graph_def, name='')
    images_placeholder = tf.get_default_graph().get_tensor_by_name("input:0")
    embeddings = tf.get_default_graph().get_tensor_by_name("embeddings:0")
    phase_train_placeholder = tf.get_default_graph().get_tensor_by_name("phase_train:0")     
    ...

error: 
Traceback (most recent call last):
  File "test_frozen.py", line 54, in <module>
    _ = tf.import_graph_def(graph_def, name='')
  File "/home/flyvideo/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 388, in import_graph_def
    node, 'Input tensor %r %s' % (input_name, te)))
ValueError: graph_def is invalid at node u'InceptionResnetV1/Conv2d_1a_3x3/BatchNorm/cond/AssignMovingAvg/Switch': Input tensor 'InceptionResnetV1/Conv2d_1a_3x3/BatchNorm/moving_mean:0' Cannot convert a tensor of type float32 to an input of type float32_ref.

who can help me please,i dont know how to fix it.........

**Comment by davidsandberg** [comment]
Hi,
This should have been fixed in the freeze_graph in this repo. You should be able to figure out how it's used.

**Comment by xidian-xuchen** [comment]
thanks for  your reply，i have found  and solved this problem.
