### ISSUE TITLE
Basic Start for face identification

### ISSUE THREAD

**Issue by andrewsueg** [davidsandberg/facenet#263]
First, sorry for starting this topic, it's not an issue. I'm really new to convnets, so I don't understand many concepts.
Basically what I'm trying to do is given 2 face images determine if they are the same person.

I already found the 'compare.py' inside the 'src' folder. Could someone give me an example of how to use it?

I already installed tensor flow and all the dependencies.

**Comment by se7oluti0n** [comment]
What `compare.py` do is calculating the distance between images. If you want to determine if two images are the same person, you need to choose a threshold for this distance. If distance smaller than threshold, you determine images are the same person, if not they are images of difference person.

You can check out the code in file `validate_on_lfw.py`. This code do exactly what you want

**Comment by andrewsueg** [comment]
Thanks se7oluti0n. Could you give me an example of how to call script? I have no clue for the parameters like meta_file and ckpt_file.

**Comment by davidsandberg** [comment]
Have you seen the guide [Validate on LFW](https://github.com/davidsandberg/facenet/wiki/Validate-on-LFW)? There it's described how to use `validate_on_lfw.py`.

**Comment by Leedonggeon** [comment]
hi. I'm university student who major in computer science. First of all, thanks for your these great contribution. I worked in Window environment.
So its method is different from method using linux terminal.
will i do my work in Linux environment?
If not, how can i do the work in Window environment.
