### ISSUE TITLE
calculate_filtering_metrics.py error

### ISSUE THREAD

**Issue by Roysky** [davidsandberg/facenet#271]
hi, everyone
I run calculate_filtering_metrics.py to calculate the distence_to_center. I get the error.

raceback (most recent call last):
  File "calculate_filtering_metrics.py", line 127, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "calculate_filtering_metrics.py", line 54, in main
    False, False, False, nrof_preprocess_threads=4, shuffle=False)
  File "/root/linshq/facenet-master/src/facenet.py", line 124, in read_and_augument_data
    labels = ops.convert_to_tensor(label_list, dtype=tf.int32)

TypeError: Expected int32, got range(0, 123) of type 'range' instead.

I trace the code. The error is in facenet.py 
`def read_and_augument_data(image_list, label_list, image_size, batch_size, max_nrof_epochs, 
        random_crop, random_flip, random_rotate, nrof_preprocess_threads, shuffle=True):
        
    images = ops.convert_to_tensor(image_list, dtype=tf.string)
    labels = ops.convert_to_tensor(label_list, dtype=tf.int32)`

the label is an range,  convert range to int32 occured errors.
TypeError: Expected int32, got range(0, 123) of type 'range' instead.

Is anyone  have this problem？ Thanks

**Comment by davidsandberg** [comment]
What command did you run?
I have been running it like this
`python src/calculate_filtering_metrics.py ~/datasets/msceleb/msceleb_mtcnnalign_182_160 ~/models/export/20170511-185253/20170511-185253.pb ~/filtering_metrics_msceleb_20170511-185253.hdf`
and it works fine.

**Comment by Roysky** [comment]
thanks for  reply.
This is my command:
`python  calculate_filtering_metrics.py  ../datasets/lfw/lfw_mtcnnpy_160  models.inception_resnet_v1     ./20170509-142912.pb  testcalc`

**Comment by davidsandberg** [comment]
If you remove the `models.inception_resnet_v1` it should work better.

**Comment by Roysky** [comment]
when I remove the models.inception_resnet_v1, It occus this problem.  Is the "model_def" argument can remove ?
`
root@ailab-All-Series:~/linshq/facenet-master/src# python  calculate_filtering_metrics.py  ../datasets/lfw/lfw_mtcnnpy_160       ./20170509-142912.pb  sdfa
usage: calculate_filtering_metrics.py [-h] [--image_size IMAGE_SIZE]
                                      [--batch_size BATCH_SIZE]
                                      dataset_dir model_def model_file
                                      data_file_name
calculate_filtering_metrics.py: error: the following arguments are required: data_file_name`

**Comment by davidsandberg** [comment]
Yes, this has been changed. The latest revision takes arguments like this:
```
def parse_arguments(argv):
    parser = argparse.ArgumentParser()
    
    parser.add_argument('dataset_dir', type=str,
        help='Path to the directory containing aligned dataset.')
    parser.add_argument('model_file', type=str,
        help='File containing the frozen model in protobuf (.pb) format to use for feature extraction.')
    parser.add_argument('data_file_name', type=str,
        help='The name of the file to store filtering data in.')
    parser.add_argument('--image_size', type=int,
        help='Image size.', default=160)
    parser.add_argument('--batch_size', type=int,
        help='Number of images to process in a batch.', default=90)
    return parser.parse_args(argv)
```

**Comment by Roysky** [comment]
I update to the latest revision . but the error also exsits.
TypeError: Expected int32, got range(0, 123) of type 'range' instead.

and  my python version is 3.5.2

**Comment by dnaq** [comment]
Try it with python2 instead, the script isn't compatible with python3.

**Comment by Bahramudin** [comment]
@dnaq Python 2 and 3 are the same, I have tried both have the same problem. How to solve?

**Comment by EmiPark** [comment]
@Roysky  I have met same problem and solved,you can change function 'read_and_augment_data' in facenet.py like this:
    labels = ops.convert_to_tensor(list(label_list), dtype=tf.int32)

while I'm using python3

**Comment by Letdreamfly** [comment]
@davidsandberg i did not find the function "read_and_augment_data" in facenet.py, could you please share it with me?

**Comment by KowsalyaR97** [comment]
@Letdreamfly  Try the below code,

    def read_and_augment_data(image_list, label_list, image_size, batch_size, max_nrof_epochs,
        random_crop, random_flip, random_rotate, nrof_preprocess_threads, shuffle=True):
 
        images = ops.convert_to_tensor(image_list, dtype=tf.string)
        labels = ops.convert_to_tensor(label_list, dtype=tf.int32)
 
        # Makes an input queue
        input_queue = tf.train.slice_input_producer([images, labels],
        num_epochs=max_nrof_epochs, shuffle=shuffle)
 
       images_and_labels = []
       for _ in range(nrof_preprocess_threads):
          image, label = read_images_from_disk(input_queue)
          if random_rotate:
              image = tf.py_func(random_rotate_image, [image], tf.uint8)
          if random_crop:
              image = tf.random_crop(image, [image_size, image_size, 3])
          else:
              image = tf.image.resize_image_with_crop_or_pad(image, image_size, image_size)
          if random_flip:
              image = tf.image.random_flip_left_right(image)
             #pylint: disable=no-member
              image.set_shape((image_size, image_size, 3))
              image = tf.image.per_image_standardization(image)
              images_and_labels.append([image, label])
 
          image_batch, label_batch = tf.train.batch_join(
            images_and_labels, batch_size=batch_size,
            capacity=4 * nrof_preprocess_threads * batch_size,
            allow_smaller_final_batch=True)
 
        return image_batch, label_batch
