### ISSUE TITLE
Factors that influence distance between face embeddings

### ISSUE THREAD

**Issue by Dagalaki** [davidsandberg/facenet#276]
Hi, 

I am using the facenet project in order to calculate the distances between two faces in images in order to evaluate if the two persons depicted are the same or not according to the compare.py file.

normally it is claimed that if the distance < =1 the faces depicted are the same person.

However, after making a lot of tests, the distance threshold can differ for different cases.

I was wondering what can influence this difference in the distance threshold? The reason is that I want to come up with a number for the distance threshold to use as a metric that produces correct results in good percent.

Is there smth I can improve in the code, or is there some criteria to have in mind when selecting tha images to be compared?For example, lightness of the image, or if the face is turned slighly to the side, etc. What prereseuites should an image have in  order to give it as input to the comparison?
Thanks in asdvance!

**Comment by sun9700** [comment]
In LFW evaluation, the best threshold is determined according to the best acc

def find_threshold(var, percentile):
    hist, bin_edges = np.histogram(var, 100)
    cdf = np.float32(np.cumsum(hist)) / np.sum(hist)
    bin_centers = (bin_edges[:-1]+bin_edges[1:])/2
    #plt.plot(bin_centers, cdf)
    threshold = np.interp(percentile*0.01, cdf, bin_centers)
    return threshold
