### ISSUE TITLE
random augmentation in training phase evaluation

### ISSUE THREAD

**Issue by sun9700** [davidsandberg/facenet#277]
The standalone validate_on_lfw.py is fine.
However, if I provide args.lfw_dir during training,
train_softmax.py will evaluate on LFW every epoch.
But the result is slight different with  the standalone validate_on_lfw.py .
It might caused by random augmentation to LFW, which should only be applied to training set:

 if args.random_rotate:
                    image = tf.py_func(facenet.random_rotate_image, [image], tf.uint8)
                if args.random_crop:
                    image = tf.random_crop(image, [args.image_size, args.image_size, 3])
                else:
                    image = tf.image.resize_image_with_crop_or_pad(image, args.image_size, args.image_size)
                if args.random_flip:
                    image = tf.image.random_flip_left_right(image)

Could the feeding pipeline splits into two, one with random augmentation for train(), one without for evaluate() after each epoch?

**Comment by davidsandberg** [comment]
Yes, this part needs to be changed to be able to disable augumentation by looking as phase_train.

**Comment by sczhengyabin** [comment]
Any solution yet?

**Comment by davidsandberg** [comment]
This has been fixed in d7f5a3a6919f5c36d8d027a50665c849ba5f428a.
