### ISSUE TITLE
Documentation for training models from scratch

### ISSUE THREAD

**Issue by delip** [davidsandberg/facenet#28]
I would like to help with several of the existing issues, including #19, #23, #22, #2, and many other future issues. One thing that will help me (and possibly others) speed up is a step-by-step documentation for training from scratch.

**Comment by davidsandberg** [comment]
Hi,
That's very good news!!
I will try to get started with such documentation.

**Comment by davidsandberg** [comment]
Hi again,
I have added a first version for a description of how to train a first model [here](https://github.com/davidsandberg/facenet/wiki/Running-training).
It would be great to get some feedback when you go through the procedure.

**Comment by delip** [comment]
Thanks for adding this!
