### ISSUE TITLE
How to get the model with .pb format, the format of the model I got from facenet_train_classifier.py is .ckpt

### ISSUE THREAD

**Issue by bingjilin** [davidsandberg/facenet#281]

**Comment by g-glowacki** [comment]
Use this:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py

**Comment by bingjilin** [comment]
@g-glowacki Thanks, I will learn it.Use the followed command
python src/classifier.py TRAIN data/my_dataset/ 20170426-021342/ models/my_classifier.pkl --batch_size 1000 also solve my problem. ie.changed the model file path to model dir

**Comment by Shreyash7** [comment]
I don't have this file models/my_classifier.pkl. How can i get it?

**Comment by sagartesla** [comment]
It is mentioned in the classifier.py file that .pkl is the output file.
Basically, when you will train classifier on your dataset. This file will be generated and will be used for classification post training.

**Comment by Shreyash7** [comment]
Got it. Thank You!!
