### ISSUE TITLE
proportional margin in alignment

### ISSUE THREAD

**Issue by rodrhern** [davidsandberg/facenet#283]
Hi,

The alignment with a fixed 44 px margin is biased by the face size, a proportional margin will center the face much better.

I performed a simple test, calculating the embedding of a face (width=399) and then downscaling the same picture and then calculating the distance between embeddings.

|face width|distance to original face (fixed margin)|distance to original face (proportional margin)
|---|---|---|
|399 |0.000   |0.000|
|271 |0.159   |0.139|
|209 |0.298   |0.228|
|161 |0.249   |0.181|
|134 |0.320   |0.227|
|113 |0.313   |0.207|
|103 |0.308   |0.168|
|87  |0.380   |0.188|
|82  |0.457   |0.125|

I re-scaled the margin as follows
```
    scale_factor = (face_width)/116
    scaled_margin = 2*int(margin*scale_factor/2)
```

I choose 116 because 116+44=160, but maybe there is a better number.

**Comment by thisfineday** [comment]
thanks for your contribution!!!

**Comment by kodonnell** [comment]
I also wondered about this, and as far as I can see, it's still a problem.  @davidsandberg does your closing of this mean it is resolved? If not, would a PR be useful?
