### ISSUE TITLE
why deal with image by "prewhiten"  used in compare.py but not uesd for training

### ISSUE THREAD

**Issue by emily2he** [davidsandberg/facenet#285]
@Davidsandberg,
 Hi, thank you for your wonderful work! 
I have one question about prewhiten. hope you can give me some guide.

why prewhiten used to deal with image before inference in compare.py, but I have checked there is no prewhiten when train model, no matter in facenet_softmax.py or alin_dataset_mtcnn.py.
if so, the image format is not same with the image feeded in train, it doesn't matter?
if it doesn't matter, why used in compare.py.

this puzzled me for a long time, could you give me some explanation?

**Comment by wangzzdeepir** [comment]
Prewhiten is equivalent to tf.image.per_image_standardization(), which is used in training.

**Comment by emily2he** [comment]
@wangzzdeepir thank you for your explanation!
