### ISSUE TITLE
the method to classify

### ISSUE THREAD

**Issue by emily2he** [davidsandberg/facenet#286]
@davidsandberg I see you supply a classifier.py, which is used to prediction and classify images.
I tested this function, but its result is ineffictive, I don't know the reason.
but also I think the last layer is used to classify, why not use it to prediction and classify directly.
and also I see in issue #62 @N2ITN and @svitlanacs try, but not get good result.

I test prediction embedding and calculate the European distance to tell that person is same or not, it is very accurate. 
why classify is ineffictive?

**Comment by davidsandberg** [comment]
Hi, what do you mean when you say that the result is ineffective.
I guess comparing distances between embeddings should work quite well. Also it's possible to replace the classification layer with a new fully connected layer with the number of identities that you have, but i didn't find any advantage of doing it like that.
