### ISSUE TITLE
Error with reading image 

### ISSUE THREAD

**Issue by nguyenhong86thinh** [davidsandberg/facenet#287]
Hello,

When I test the code with face image crop from RGB  image to 160x160, I always got this error:
Traceback (most recent call last):
  File "Test_new_person.py", line 166, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "Test_new_person.py", line 77, in main
    images = facenet.load_data(paths_batch, False, False, args.image_size)
  File "/home/tung/Documents/Plate/Thinh/facenet/src/facenet.py", line 265, in load_data
    images[i,:,:,:] = img
ValueError: could not broadcast input array from shape (160,160,4) into shape (160,160,3)

Please tell me problem?
Thank a lot

**Comment by RaviRaaja** [comment]
Can you explain how you fixed error

**Comment by MaartenBloemen** [comment]
@RaviRaaja Are you using a PNG image instead of JPG?

**Comment by nguyenhong86thinh** [comment]
In my case, input image is RGBA (RGB and transparent), so I just need to check the size of input before import to network. So all I do is modify a function load_data in facenet.py:
 if img_ndim[2] ==4:    
            img=img[:,:,0:3]
