### ISSUE TITLE
what is the relationship between  "distance matrix " and "accuracy"?

### ISSUE THREAD

**Issue by ouyangbei** [davidsandberg/facenet#295]

**Comment by luckyboysmith** [comment]
hi,
have you solve the question?
i am also puzzled about this
hope to get your help

**Comment by davidsandberg** [comment]
You get the accuracy on LFW by calculating the distance between the images in all image pairs and compare that to a threshold. High accuracy means that the distances between same identity pairs are smaller than threshold and different identity pairs are larger. The distance matrix in compare.py is just a way to present the distances between a number of images.

**Comment by luckyboysmith** [comment]
@davidsandberg 
your reply really help me! thanks a lot!!!

**Comment by kb-studios** [comment]
How should we decide the threshold for datasets? Is it different for every dataset?
