### ISSUE TITLE
Basic Instructions to install Facenet

### ISSUE THREAD

**Issue by eacosta1976** [davidsandberg/facenet#296]
Hi my name is Edgar Acosta. I want to run Facenet, detect face, the name of the person, and emotions. I download TensorFlow (Using container), I have python 2.7, and also iPython and Jupyter as my interactive editor. I need some advice:

To clone Facenet: 

Is there any basic instructions to install and run Facenet, step by step guide?
Do I need to clone inside Tensor Flow directory?.
Do you believe my setup is OK, or do I need to install something else.?
Is there any instructions to make it up and running with my WEB Cam?

Thank you very basic questions but I am very new to this Fascinating field.

My email address is : eacosta1976@gmail.com

**Comment by ouyangbei** [comment]
step1 :   git clone fecenet;
step2:    put  facenet folder to pip library , 
step3:    run python files

**Comment by davidsandberg** [comment]
Hi,
All instructions you need to set it up should be on the wiki. Have you checked that out?

**Comment by eacosta1976** [comment]
Hi David, thanks for your advice.   I have nit finished yet,  and I realize that the library is not working with WebCam,  need to detect faces in WebCam, detect names and detect emotions.  

  Also from your last post,  in step2:  put facenet folder to pip library.   I clone Facenet in my home directory.  what does it mean to put facet to pip library?.  ... seems very dumb questions but I am not so experienced in python tools, I came from java.

**Comment by ouyangbei** [comment]
@eacosta1976  You can find your answer here [https://github.com/davidsandberg/facenet/wiki/Classifier-training-of-inception-resnet-v1]

**Comment by speculaas** [comment]
Dear All, 
About emotion recognition, 
Anyone tried utilizing facenet for emotion recognition?

https://arxiv.org/abs/1804.08348
This paper gives a survey.

https://arxiv.org/abs/1609.06591
This paper use conv layers of face recognizing net plus a new fully connected layer to do emotion recognition

https://kpzhang93.github.io/papers/icmi.pdf
This paper describing their EmotiW 2017 winning method says before fine tuning for group emotion recognition, they first trained Resnet64 on Webface then finetune on ExpW.

And I think to do emotion recognition, maybe here is a good place to try getting started?

BR,
JimmyYS

**Comment by sassa95** [comment]
The steps of installation are:
step1 : git clone fecenet;
step2: put facenet folder to pip library ,
step3: run python files
I would like to give me a more details about this steps (instructions), i am a beginner in python and facenet. 
Thank you.
