### ISSUE TITLE
Run Facenet with WEBCAM

### ISSUE THREAD

**Issue by eacosta1976** [davidsandberg/facenet#297]
Hi I want to run Facenet using. a rudimentary WEB CAM, or the cam that my MacBook Pro has.

   Can I use this library with a Web Cam, to recognize face, name of the person, and emotions?

   I appreciate your help

**Comment by davidsandberg** [comment]
Hi,
Currently this is not possible with this repo. Have you seen [OpenFace](https://cmusatyalab.github.io/openface/demo-1-web/)?

**Comment by eacosta1976** [comment]
I just read about it.  if this is the case I will need to switch to OpenFace.    I only have a question,  I have an old Ubuntu computer 4 gig ram only, and 500 gig hd,  two cores.  Is an old computer from  around 2010.    do you believe OpenFace can run lets say good, in this computer?

**Comment by vudung45** [comment]
You definitely can do that if you want to with opencv VideoCapture, then preprocess the face ( you can either use haar cascade or dlib for facial detection) -> align face using mtcnn -> use that output  as feed_dict -> classification or embeddings

**Comment by eacosta1976** [comment]
Thank you.

  So  I get the signal with OpenCV, and then feed this signal to TensorFlow
or deeplearningforJ, or some other, and then do the rest by myself  using
Neural Networks (Detect faces, detect who is the person, detect the
feelings: happy, sad, angry).  If I can do that... what is the best book or
reference to start doing it... because I really don't know nothing about
OpenCV,  and what I know is basic Machine Learning Neural Networks theory,
I have never done anything practical... IN fact  I want to do this using C#


  I appreciate your orientation,  since I am very primitive...

**Comment by eladtann1** [comment]
Hi David,
Could you please explain why can't this repo be used with a webcam for live face detection? Is it just computational cost considerations or something else?

thank you

**Comment by phanxuanduc1996** [comment]
Hi all,
I want to learn a model that can apply facenet with webcam, camera. Has anyone had code with this direction yet? If possible, please give me the reference source. Thank you.
