### ISSUE TITLE
why my Validation rate is just 0.6?

### ISSUE THREAD

**Issue by luckyboysmith** [davidsandberg/facenet#300]
batch_size default is 90 and epoch_size default is 1000
but when i run the code i meet the  Error 
Limit: 5951455232
InUse: 5950830080
MaxInUse: 5951397632
NumAllocs: 726678842
MaxAllocSize: 1397393152
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[90,1,1,1792]
so  i reduce the batch_size to 80 and set epoch_size to 1125
but after 80 epoch 
Runnning forward pass on LFW images
Accuracy: 0.93800+-0.003
Validation rate: 0.61733+-0.01340 @ FAR=0.00100
why the validation rate is so low? just 0.6?

**Comment by amalF** [comment]
@luckyboysmith : Did you find a solution to your problem ? 

Thx

**Comment by luckyboysmith** [comment]
@amalF  
i solve the problem by two measures
first,make sure train data images are aligned
second, increase epoch number

but i also find a problem, if your image quality is low what i mean is ,if your train data image is blurred,then the validation rate will be very low

good luck!
