### ISSUE TITLE
Use facenet with binary image contain only landmarks point

### ISSUE THREAD

**Issue by nguyenhong86thinh** [davidsandberg/facenet#301]
Hi,

My project is to do realtime surveillance but to write data from camera into RGB image take delay several seconds; so I think about write directly output of camera to binary image contain only landmarks point. Is there  way to use these kind of images with pre-training CNN model?

Thanks

**Comment by davidsandberg** [comment]
Hi,
Yes, if you have the image as a numpy array it should be fairly easy to feed that to the model using feed_dict, just the way it's done in e.g. compare.py. But remember that you need to extract the part of the image corresponding to the face, resize it  and also do image whitening to get decent performance.
Good luck!

**Comment by BerenLuthien** [comment]
Hi David, I noticed "_prewhitenning_" in the code (shift by mean, and resize by variance; but not using eigenvalue). Did the code also perform _eigenvalue_ "_whitening_" ? Thanks
