### ISSUE TITLE
facenet model to caffe

### ISSUE THREAD

**Issue by hanbim520** [davidsandberg/facenet#303]
Hello, may I ask you to provide caffe version of the training data? I would like to use tensorflow to do a C + + version, but I feel like not getting well, Python, then I am not very familiar with, now use the caffe + MTCNN + VGG do, want to change facenet, training data this, my own Computer is a home computer, training more difficult. (Google Translate)

**Comment by davidsandberg** [comment]
Hi,
I'm not sure what you mean by caffe version of training data?

**Comment by hanbim520** [comment]
En, that's your model used in caffe's net, now i have not found tensorflow's data model converted to caffe's caffemodel tool. (Google Translate)

**Comment by davidsandberg** [comment]
I will not provide any training data but the training data that is used to train the models in this repo should be easy to get access to,
Closing this for now. Reopen if needed.
