### ISSUE TITLE
Why slim.flatten(net) before slim.dropout(net)?

### ISSUE THREAD

**Issue by chencjiajy** [davidsandberg/facenet#304]
when I read the model code, I found there is a layer slim.flatten(net) before net = slim.dropout(net, dropout_keep_prob, is_training=is_training, scope='Dropout'), it's different with paper.
sorry, I'm new to this area, thank you very much

**Comment by davidsandberg** [comment]
Hi,
The flatten operation just reshapes the activations tensor and for dropout the tensor shape doesn't matter. So the result will be the same for the two cases.
