### ISSUE TITLE
How to train my model?

### ISSUE THREAD

**Issue by ouyangbei** [davidsandberg/facenet#306]

**Comment by MaartenBloemen** [comment]
Have you checked out the [wiki](https://github.com/davidsandberg/facenet/wiki)?

**Comment by ouyangbei** [comment]
I want to train my own models , not train a classifier on your own images , like 20170511-185253  and 20170512-110547.

**Comment by davidsandberg** [comment]
Isn't [this](https://github.com/davidsandberg/facenet/wiki/Classifier-training-of-inception-resnet-v1) wiki page what you are looking for then?

**Comment by ouyangbei** [comment]
@davidsandberg  Thanks for your answer , I want to  train my own  "Inception-Resnet-v1 model" ,but I don not know how.

**Comment by davidsandberg** [comment]
The wiki page I linkednto describes exactly(!) that. Check it out...

**Comment by ouyangbei** [comment]
@davidsandberg  Thanks I will try.
