### ISSUE TITLE
validate on own dataset: tensor 'input:0' has different shape

### ISSUE THREAD

**Issue by ljstrnadiii** [davidsandberg/facenet#307]
Hi, 

When trying to validate on my own data set with images that are 64x64 I set image size to 64 but it has an issue. It says

``` Cannot feed value of shape (100, 64, 64, 3) for Tensor u'input:0', which has shape '(?, 160, 160, 3)'```

Is there a way to reshape the placeholder or is the model architecture specifically for 160 pixel images?

**Comment by davidsandberg** [comment]
Hi,
I'm not sure which scriptnyou are running but many of the scripts have a parameter image_size. Have you tried setting that to 64? But I think 64x64 pixels will be to little for the models in this repo. Also, when changing image size like that the model needs to be retrained to make any sense.

**Comment by ljstrnadiii** [comment]
I am running the `validate_on_lfw.py` script. I just had to resize the images to 160 which I think is what the model's input if made for.
