### ISSUE TITLE
Is there any .meta file for the pre-trained model-20160506.ckpt-500000?

### ISSUE THREAD

**Issue by GangqiangZhao** [davidsandberg/facenet#31]
Hi David:
       I am trying to run "validate_on_lfw.py". However, when using your provided model "model-20160506.ckpt-500000", I can not find the corresponding ".meta " file. And this results the "utf8' codec can't decode" error when loading the model file.

Best,
GQ

**Comment by davidsandberg** [comment]
Hi!
The readme is not so up-to-date. Could you check out the description on the [wiki](https://github.com/davidsandberg/facenet/wiki/Validate-on-lfw)? There you can find a zip file that contains both the model parameters and the metagraph.

**Comment by GangqiangZhao** [comment]
Hi David. Thanks, will check it later.

**Comment by hzxjtx** [comment]
hi, @davidsandberg 
    can you share the methods to how gen model-20160506.ckpt-500000 model? tensorflow c++ does not have "import_meta_graph" interface.

**Comment by davidsandberg** [comment]
Hi,
The easiest way probably to go back to get the model from a git revision when the model was trained, i.e. sometime close to 2016-05-06. For example you could start with revision 1678d34b88281f3cd7aeb5ef8021aedd251f1617.
