### ISSUE TITLE
Questions about overtraining

### ISSUE THREAD

**Issue by MaartenBloemen** [davidsandberg/facenet#311]
Hi all,
So I had some questions about over training and I hope anyone could help me with this. So I know upping the epochs can lead to over training, but what else can influence the over fitting of the training? And what is the correlation between the validation rate and over training?
If anyone knows a good paper on this subject that would also be great.
Thanks in advance for any help!

**Comment by twobob** [comment]
http://www.reality.ai/single-post/2017/01/17/Machine-Learning-the-Lab-vs-the-Real-World
is a very easy read

**Comment by MaartenBloemen** [comment]
@twobob Thanks this is perfect, its very well explained in the articles!

**Comment by twobob** [comment]
Might as well close this issue then ;)
