### ISSUE TITLE
some issue about the size of input image

### ISSUE THREAD

**Issue by KaiJin1995** [davidsandberg/facenet#314]
As we now,the size of input image in Inception-ResNet-v1 is 299X299X3.However,i see the code in train_softmax.py and i find that your size of input image is 160X160X3.I wonder konw why not resize 299X299X3?

**Comment by ugtony** [comment]
You can do with 299x299x3, the performance would be slightly better, but the batch size should be much smaller and the training time would be much longer.

**Comment by KaiJin1995** [comment]
OK,thank you for your replay
