### ISSUE TITLE
pkl model file for testing MS-Celeb-1M subset pretrained model with classifier.py

### ISSUE THREAD

**Issue by avikj** [davidsandberg/facenet#315]
I'm trying to test the classifier that was trained on a subset of MS-Celeb-1M. I found the .pb and other files on the [Google Drive link](https://drive.google.com/file/d/0B5MzpY9kBtDVZ2RpVDYwWmxoSUk/edit), and used the pb as the argument for 'model', but classifier.py also requires an argument for 'classifier_filename' which is a pkl. 

How can I create or find this pickle file?

**Comment by MaartenBloemen** [comment]
You need to generate it, how to do that you can read that on [this](https://github.com/davidsandberg/facenet/wiki/Train-a-classifier-on-own-images) wiki page.

**Comment by avikj** [comment]
Thanks. Is it possible to use the classes from the pretrained model and not supply any data of my own?

**Comment by MaartenBloemen** [comment]
Sure that's no problem at all

**Comment by avikj** [comment]
How would I do that? would I just specify data_dir as an empty directory?
