### ISSUE TITLE
Serving with TensorflowServing

### ISSUE THREAD

**Issue by xolott** [davidsandberg/facenet#316]
Hi, 
I'm working on a script to export the facenet model to a ServableModel using this code:

    def export():   

        model_dir = compat.as_str(FLAGS.checkpoint_dir)
        with tf.Graph().as_default():

            with tf.Session() as sess:
                load_model(model_dir)

                # Export inference model.
                output_path = os.path.join(
                    compat.as_bytes(FLAGS.output_dir),
                    compat.as_bytes(str(FLAGS.model_version)))
                print('Exporting trained model to', output_path)
                builder = saved_model_builder.SavedModelBuilder(output_path)
                 
                # Get input and output tensors
                images_placeholder = tf.get_default_graph().get_tensor_by_name("input:0")
                embeddings = tf.get_default_graph().get_tensor_by_name("embeddings:0")
                phase_train_placeholder = tf.get_default_graph().get_tensor_by_name("phase_train:0")
                
                # Build the signature_def_map.
           
                prediction_signature = signature_def_utils.build_signature_def(
                    inputs={'images': utils.build_tensor_info(images_placeholder),
                            'phase': utils.build_tensor_info(phase_train_placeholder)},
                    outputs={
                        'embeddings': utils.build_tensor_info(embeddings)
                    },
                    method_name=signature_constants.PREDICT_METHOD_NAME)
                
                legacy_init_op = tf.group(
                    tf.tables_initializer(), name='legacy_init_op')
                
                sess.run(tf.global_variables_initializer())
                
                builder.add_meta_graph_and_variables(
                    sess, [tag_constants.SERVING],
                    signature_def_map={
                        'calculate_embeddings':
                            prediction_signature,
                    },
                    legacy_init_op=legacy_init_op)
                
                builder.save()
                print('Successfully exported model to %s' % FLAGS.output_dir)

I can serve it using tensorflow serving, but I get differents embeddings if a run the ckpt model locally or on the remote server. I think that maybe I set the prediction_signature in a wrong way.

I tried to calculate the distance between 2 face, and always return similar values (0.002 or  0.003) no mather if the images are from the same or different person.

This code is based on the [mnist_saved_model.py](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_saved_model.py)

Any hint in how can I write the prediction_signature?

**Comment by AKSHAYUBHAT** [comment]
This typically happens due to batchnorm not being turned off. There is another issue that addresses this

**Comment by Cecilwang** [comment]
I meet this issue too.
And I freeze the graph then export it, but I got differents embeddings from ckpt model and tensorflow serving yet.
Anybody can help?

**Comment by Cecilwang** [comment]
I have solved this.

**Comment by xolott** [comment]
How do you solved this? I'm still trying

**Comment by xolott** [comment]
@AKSHAYUBHAT I don't understand how to apply that graph_def in my code. I made some test with my original code but I'm still facing this issue

    model_dir = compat.as_str(FLAGS.checkpoint_dir)
    with tf.Graph().as_default():
          
            with tf.Session() as sess:
                load_model(model_dir)

                # Retrieve the protobuf graph definition and fix the batch norm nodes
                input_graph_def = sess.graph.as_graph_def()
                input_graph_def.
                # Export inference model.
                output_path = os.path.join(
                    compat.as_bytes(FLAGS.output_dir),
                    compat.as_bytes(str(FLAGS.model_version)))
                print('Exporting trained model to', output_path)
                builder = tf.saved_model.builder.SavedModelBuilder(output_path)
                 
                # Get input and output tensors
                images_placeholder = sess.graph.get_tensor_by_name("input:0")
                embeddings = sess.graph.get_tensor_by_name("embeddings:0")
                phase_train_placeholder = sess.graph.get_tensor_by_name("phase_train:0")                
                
                # Build the signature_def_map.
           
                prediction_signature = tf.saved_model.signature_def_utils.build_signature_def(
                    inputs={'images': tf.saved_model.utils.build_tensor_info(images_placeholder),
                            'phase': tf.saved_model.utils.build_tensor_info(phase_train_placeholder)},
                    outputs={
                        'embeddings': tf.saved_model.utils.build_tensor_info(embeddings)
                    },
                    method_name = tf.saved_model.signature_constants.PREDICT_METHOD_NAME)
                
                legacy_init_op = tf.group(
                    tf.tables_initializer(), name='legacy_init_op')
                
                builder.add_meta_graph_and_variables(
                    sess, [tf.saved_model.tag_constants.SERVING],
                    signature_def_map={
                        'calculate_embeddings': prediction_signature,
                    })
                
                builder.save()
                print('Successfully exported model to %s' % FLAGS.output_dir)

I not able to get the expected embeddings. I saw that @Cecilwang made it, but don't know how.

**Comment by xolott** [comment]
I solved this, first freezing the model (converting all variables into constants) and then exported the servable model.

Tensorflow Serving work fine with this.

Thanks all! Closing this...

**Comment by pavankumarkatakam** [comment]
Hi @xolott, can you please share the code for facenet serving , if you done serving for face detection also please let me know.

**Comment by dingqs447** [comment]
Hi, @xolott  Same as you do， first freezing the model (converting all variables into constants) and then exported the servable model. tensorflow-serving can load the model.
but when clients call using gRPG was error.
Traceback (most recent call last):
  File "tf-serving_client.py", line 41, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "tf-serving_client.py", line 37, in main
    result = stub.Predict(request, 10.0) # 10 secs timeout
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 309, in __call__
    self._request_serializer, self._response_deserializer)
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 195, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.INVALID_ARGUMENT, details="input size does not match signature")

this my client code:
  1 #!/usr/bin/env python
  2 
  3 
  4 #usage:
  5 #    python tf-serving_client.py --server=ip:port
  6 from grpc.beta import implementations
  7 import tensorflow as tf
  8 
  9 from google.protobuf.json_format import MessageToDict, ParseDict
 10 from tensorflow_serving.apis import predict_pb2
 11 from tensorflow_serving.apis import prediction_service_pb2
 12 
 13 import requests
 14 import os
 15 import os.path
 16 
 17 tf.app.flags.DEFINE_string('server', 'localhost:9000', 'PredictionService host:port')
 18 FLAGS = tf.app.flags.FLAGS
 19 
 20 image = os.path.join(os.getcwd(), 'test_image.jpg')
 21 
 22 def main(_):
 23     host, port = FLAGS.server.split(':')
 24     channel = implementations.insecure_channel(host, int(port))
 25     stub = prediction_service_pb2.beta_create_PredictionService_stub(channel)
 26 
 27     # Send request
 28     with open(image, 'rb') as f:
 29         # See prediction_service.proto for gRPC request/response details.
 30         data = f.read()
 31         print(len(data))
 32         request = predict_pb2.PredictRequest()
 33         request.model_spec.name = 'model_output_18'
 34         request.model_spec.signature_name = 'calculate_embeddings'
 35         request.inputs['images'].CopyFrom(
 36         tf.contrib.util.make_tensor_proto(data, shape=[1]))
 37         result = stub.Predict(request, 10.0) # 10 secs timeout
 38         print(result)
 39 
 40 if __name__ == '__main__':
 41     tf.app.run()


can you share you client code?

**Comment by vivekaditya** [comment]
``` python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from tensorflow.python.framework import graph_util
import tensorflow as tf
import argparse
import os
import sys
import facenet
from six.moves import xrange

def main(args):
    with tf.Graph().as_default():
        with tf.Session() as sess:
            # Load the model metagraph and checkpoint
            print('Model directory: %s' % args.model_dir)
            meta_file, ckpt_file = facenet.get_model_filenames(os.path.expanduser(args.model_dir))

            print('Metagraph file: %s' % meta_file)
            print('Checkpoint file: %s' % ckpt_file)

            model_dir_exp = os.path.expanduser(args.model_dir)
            saver = tf.train.import_meta_graph(os.path.join(model_dir_exp, meta_file), clear_devices=True)
            tf.get_default_session().run(tf.global_variables_initializer())
            tf.get_default_session().run(tf.local_variables_initializer())
            saver.restore(tf.get_default_session(), os.path.join(model_dir_exp, ckpt_file))

            # Retrieve the protobuf graph definition and fix the batch norm nodes
            input_graph_def = sess.graph.as_graph_def()

            # Freeze the graph def
            output_graph_def = freeze_graph_def(sess, input_graph_def, 'embeddings')

            # Export facenet model.
            model_version = 1
            path = os.path.join("tf_models", str(model_version))
            print('Exporting trained model to', path)
            builder = tf.saved_model.builder.SavedModelBuilder(path)

            # Get input and output tensors
            images_placeholder = sess.graph.get_tensor_by_name("input:0")
            embeddings = sess.graph.get_tensor_by_name("embeddings:0")
            phase_train_placeholder = sess.graph.get_tensor_by_name("phase_train:0")

            # Build the signature_def_map.

            prediction_signature = tf.saved_model.signature_def_utils.build_signature_def(
                inputs={'images': tf.saved_model.utils.build_tensor_info(images_placeholder),
                        'phase': tf.saved_model.utils.build_tensor_info(phase_train_placeholder)},
                outputs={
                    'embeddings': tf.saved_model.utils.build_tensor_info(embeddings)
                },
                method_name=tf.saved_model.signature_constants.PREDICT_METHOD_NAME)

            legacy_init_op = tf.group(
                tf.tables_initializer(), name='legacy_init_op')

            builder.add_meta_graph_and_variables(
                sess, [tf.saved_model.tag_constants.SERVING],
                signature_def_map={
                    'calculate_embeddings': prediction_signature,
                })

            builder.save()
            print('Successfully exported model to ' + path)

        # Serialize and dump the output graph to the filesystem
        with tf.gfile.GFile(args.output_file, 'wb') as f:
            f.write(output_graph_def.SerializeToString())
        print("%d ops in the final graph: %s" % (len(output_graph_def.node), args.output_file))

def freeze_graph_def(sess, input_graph_def, output_node_names):
    for node in input_graph_def.node:
        if node.op == 'RefSwitch':
            node.op = 'Switch'
            for index in xrange(len(node.input)):
                if 'moving_' in node.input[index]:
                    node.input[index] = node.input[index] + '/read'
        elif node.op == 'AssignSub':
            node.op = 'Sub'
            if 'use_locking' in node.attr: del node.attr['use_locking']
        elif node.op == 'AssignAdd':
            node.op = 'Add'
            if 'use_locking' in node.attr: del node.attr['use_locking']

    # Get the list of important nodes
    whitelist_names = []
    for node in input_graph_def.node:
        if (node.name.startswith('InceptionResnetV1') or node.name.startswith('embeddings') or
                node.name.startswith('phase_train') or node.name.startswith('Bottleneck') or node.name.startswith(
                    'Logits')):
            whitelist_names.append(node.name)

    # Replace all the variables in the graph with constants of the same values
    output_graph_def = graph_util.convert_variables_to_constants(
        sess, input_graph_def, output_node_names.split(","),
        variable_names_whitelist=whitelist_names)
    return output_graph_def


def parse_arguments(argv):
    parser = argparse.ArgumentParser()

    parser.add_argument('model_dir', type=str,
                        help='Directory containing the metagraph (.meta) file and the checkpoint (ckpt) file containing model parameters')
    parser.add_argument('output_file', type=str,
                        help='Filename for the exported graphdef protobuf (.pb)')
    return parser.parse_args(argv)


if __name__ == '__main__':
    args = parse_arguments(sys.argv[1:])
    main(args)
```
Tried exporting as said by @xolott  and @Cecilwang but still find the same encoding for any image I sent to the server. Is the way I am fixing the batch norm nodes?

**Comment by annish07** [comment]
I am not able to send a rest api for the same.
`img_path='/media/msi/Secondary/layak_images/00000001.jpg'
image_np=cv2.imread(img_path)


payload = {"instances": [
    {
    "in":[image_np.tolist()],
    "phase":False
    }
]}
res = requests.post("http://localhost:8051/v1/models/face_recognition:predict", json=payload)
print(res.text)
print(res.json())
return_updated=res.json()['predictions'][0]
`

It is throwing some error.
{ "error": "The second input must be a scalar, but it has shape [1]\n\t [[{{node InceptionResnetV1/Conv2d_1a_3x3/BatchNorm/cond/Switch}} = Switch[T=DT_BOOL, _output_shapes=[<unknown>, <unknown>], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_phase_train_0_1, _arg_phase_train_0_1)]]" }

Can anyone please suggest me what to do?

**Comment by ljhll0942** [comment]
hello @annish07 
I have the same issue.

(code)
image_size = 160
im_file = '0001.png'	
im = cv2.imread(im_file)
im = cv2.resize(im, (image_size, image_size))
im = im.reshape(image_size,image_size,3)
inputs = {"instances": [{"phase":False, "images": im}]}
response = client.invoke_endpoint(EndpointName='sim', Body=json.dumps(inputs, cls=NumpyEncoder))

(errorMessage)
  "{ \"error\": \"The second input must be a scalar, but it has shape [1]\\n\\t 
  [[{{node InceptionResnetV1/Block8/Branch_0/Conv2d_1x1/BatchNorm/cond/Switch}}, 
  {{node InceptionResnetV1/Block8/Branch_0/Conv2d_1x1/BatchNorm/cond_1/Switch}}, ......

Has the issue been resolved? 
please answer about my question.

**Comment by rhit2020** [comment]
hello @ljhll0942 and @annish07:

I'm facing the same issue. Have you been able to find the solution for the error you mentioned:
{ "error": "The second input must be a scalar, but it has shape [1]\\n\\t [[{{node InceptionResnetV1/Block8/Branch_0/Conv2d_1x1/BatchNorm/cond/Switch}}, {{node InceptionResnetV1/Block8/Branch_0/Conv2d_1x1/BatchNorm/cond_1/Switch}}, {{node InceptionResnetV1/Block8/Branch_1/Conv2d_0a_1x1/BatchNorm/cond/Switch}}, {{node InceptionResnetV1/Block8/Branch_1/Conv2d_0a_1x1/BatchNorm/cond_1/Switch}},

@xolott  have you been able to call the predict function on the Tensorflow serving model? If yes, would you mind sharing how you passed the input to the model?

Thanks!

**Comment by rhit2020** [comment]
@vivekaditya could you please share how you send a request to the tensorflow serving model, calling the predict function?

**Comment by 2361305340** [comment]
> 

Hello, have you solved it yet?
