### ISSUE TITLE
why is 160*160? not 224*224?

### ISSUE THREAD

**Issue by tengshaofeng** [davidsandberg/facenet#318]
hi, @davidsandberg,
    You really did a great job. And I have learned much from you. I am a little confused about the input size of the  inception-v1-resnet.   It should be 224*224, why is 160*160 in your code. have you changed the architecture of inception-v1-resnet?

**Comment by vudung45** [comment]
I don't think it really matters that much what size of the image we start with. As long as we follow the architecture of the net, performance should be similar

**Comment by tengshaofeng** [comment]
@vudung45 ,
  ok, got it, thank you for your answer. as far as i know. the inception-resnet-v1 architecture in this project is not exactly same as in other projects.  So inception-resnet-v1 is just the idea, not the architecture? as far as i know, v1 has the conv 5*5, but i can not find it in this project.

**Comment by davidsandberg** [comment]
I checked the paper that describes the (inception-resnet-v1 architecture](https://arxiv.org/pdf/1602.07261.pdf) but I see no mentioning of any 5x5 covolutions.

**Comment by davidsandberg** [comment]
Closing this for now. Reopen if needed.
