### ISSUE TITLE
Restoring session for multiple use in the same process

### ISSUE THREAD

**Issue by xolott** [davidsandberg/facenet#320]
Hi,

I triying to load the facenet model at start, and later, after some events and preprocessing use that restored session to get the embeddings. I'm experimenting with your model, so I'll ready to create my own models and use it without problems.

        self.sess = tf.Session()       
        # This just restore the session using the meta and ckpt files
        self.__load_model_global()        
        self.sess.run(tf.global_variables_initializer())
        
        # Get input and output tensors        
        graph = tf.get_default_graph()
        self.images_placeholder = graph.get_tensor_by_name("input:0")
        self.embeddings = graph.get_tensor_by_name("embeddings:0")
        self.phase_train_placeholder = graph.get_tensor_by_name("phase_train:0")
        
        self.image_size = self.images_placeholder.get_shape()[1]
        self.embedding_size = self.embeddings.get_shape()[1]

And then, when I receive a image (in a numpy array), I do:

        emb_array = []
        # Run forward pass to calculate embeddings
        print_info('Runnning forward pass on LFW images')
        nrof_images = len(imgs)        
        
        images = np.zeros((nrof_images, self.image_size, self.image_size, 3))
        for idx, img in enumerate(imgs):
            img = facenet.prewhiten(img)
            img = facenet.crop(img, False, self.image_size)
            try:
                images[idx,:,:,:] = img
            except ValueError as e:
                print(e)
        
        feed_dict = { self.images_placeholder:images, self.phase_train_placeholder:False }
        emb_array = self.sess.run(self.embeddings, feed_dict=feed_dict)
        
        if len(emb_array) == 0:
            return None
        return emb_array[0]

With your example code (validate_on_lfw.py), modified with my input, and then calculate the distances(based on validate_on_lfw.py) I get:
0.54637 with faces of the same person
2.247 with faces of diferent persons

But if I run my code, restoring the session at the start, I get this results with the same photos:
0.00325157 (same person)
0.00317252 (different)

I guess that this issue is related to the load of the graph. But I'm new in this and don't know how to resolve it.

**Comment by xolott** [comment]
I'll respond in case someone else need this.
I made a mix betwwen how the mtcnn models are loaded and Facenet. Resulting this:

    class Facenet(object):
        def __init__(self):
            self.model = self.__load_network()

        def __load_network(self):  
            """
                Load the neural network
            """  
            print("Features: Loading model")
            with tf.Graph().as_default():
            gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction = self.gpuMemoryFaction)
            sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options, log_device_placement=False))
            
            with sess.as_default():                
                #Get model file names
                meta_file, ckpt_file = facenet.get_model_filenames(path.expanduser(self.model_dir))   
                model_dir_exp = path.abspath(path.expanduser(self.model_dir))
                saver = tf.train.import_meta_graph(path.join(model_dir_exp, meta_file))
                saver.restore(sess, path.join(model_dir_exp, ckpt_file))
                            
                self.images_placeholder = tf.get_default_graph().get_tensor_by_name("input:0")                
                self.image_size = self.images_placeholder.get_shape()[1]  
                model_fun = lambda img : sess.run('embeddings:0', feed_dict={ 'input:0':img, 'phase_train:0':False })
                return model_fun

And then simply use that lambda function anywhere in the class

**Comment by himabinduyeddala** [comment]
Hi@ xolott
Restroing session  working fine for u?...


Thanks in Adavance
bindu

**Comment by xolott** [comment]
Yes, @himabinduyeddala
It is working since that change without an issue
