### ISSUE TITLE
Separate new persons images into groups

### ISSUE THREAD

**Issue by nguyenhong86thinh** [davidsandberg/facenet#325]
Hi,
I do the collection data from the surveillance camera, then it get millions of images of about thousand peoples.  Now I have to separate those images into sub folder for each person. I use clustering algorithm (ex. Kmeans) on embedded vectors of  images, it works but does not obtain accuracy
Any suggest.

**Comment by vudung45** [comment]
@nguyenhong86thinh the accuracy can be calculated by distance threshold between those embedings. 
I've scratched a way to find the distance threshold at #324 
Accuracy % can probably be calculated by: max (100,100 * threshold/ smallest)

If you speak vietnamese, email me at: davidvu98@gmail for further discission

Hope this helps!

**Comment by davidsandberg** [comment]
Hi,
There are plenty of previous issues that discusses this. Have you looked at e.g. #140?
