### ISSUE TITLE
facenet wechat group

### ISSUE THREAD

**Issue by zhuchangjiang** [davidsandberg/facenet#327]
![_20170612153744](https://user-images.githubusercontent.com/26199641/27023448-2a4b5d88-4f85-11e7-9b1e-2615a7f8994f.jpg)

**Comment by zhuchangjiang** [comment]
many confuses hapen when i read the code ,so ,can i buil a contact group ? if not ,i delete this jpg quickly

**Comment by zixia** [comment]
Joined. +1

**Comment by AaronFan1992** [comment]
申请加入，wechat：aaronfan888

**Comment by wxthss82** [comment]
申请加入：wxthss82

**Comment by rexlow** [comment]
申请加入： rexlow0823
