### ISSUE TITLE
training with triplet loss

### ISSUE THREAD

**Issue by cvmlboy** [davidsandberg/facenet#331]
Hi @davidsandberg ,

Thank you for this project. It's really great!!!

I'm on my way with achieving same results as you using train_softmax.py (with center loss):
[Classifier-training-of-inception-resnet-v1](https://github.com/davidsandberg/facenet/wiki/Classifier-training-of-inception-resnet-v1)

But when I follow your steps for train_tripletloss.py and guide, then I get following error (using any face dataset - MsCelebrity / LFW):
https://pastebin.com/a2Jciccw

I'm not sure if current "master" is stable for [tripletloss training](https://github.com/davidsandberg/facenet/wiki/Triplet-loss-training), could you please help me with this?

Thank you :)

**Comment by jerrywind** [comment]
I have the same question! I was confused about the pipeline. Could anyone provide a solution ?

**Comment by davidsandberg** [comment]
Hi,
It looks like your LFW images cannot be found and my guess is that the problem you are seeing is related to your training images not being found or similar. Are your training images in png format?
There is a test case in test/train_test named test_train_tripletloss_inception_resnet_v1 that tests exactly this. You can compare to that.

**Comment by jerrywind** [comment]
By debuging, I found that the data canbe feed into the placeholders. But there is no data feed into the batch_join op

**Comment by davidsandberg** [comment]
The batch_join op is supposed to get data from the preprocessing threads, but it doesn't seem to handle your dataset very well. As I said before my guess is that your image format is not correct. I see 
```
Skipped 6000 image pairs
```
and that is not a good sign.

Closing this for now...
