### ISSUE TITLE
create wrong directory in download_vgg_face_dataset.py

### ISSUE THREAD

**Issue by ydhan** [davidsandberg/facenet#333]
###DESCRIPTION : 
    example: there are  A.J._Buckley.txt and A.R._Rahman.txt,   we will create one directory  named A,So A.R._Rahman.txt will be ignored. 

###STEPS : 
    
###EXPECTED : 
    i have a try as follow
for textfile_name in textfile_names:
        if textfile_name.endswith('.txt'):
            with open(os.path.join(args.dataset_descriptor, textfile_name), 'rt') as f:
                lines = f.readlines()
            l=len(textfile_name)
            dir_name = textfile_name[:l-4]
            class_path = os.path.join(args.dataset_descriptor, dir_name)
            if not os.path.exists(class_path):
                   os.makedirs(class_path)
###OBSERVATIONS : 
     from original code : 
        if textfile_name.endswith('.txt'):
            with open(os.path.join(args.dataset_descriptor, textfile_name), 'rt') as f:
                  lines = f.readlines()
            dir_name = textfile_name.split('.')[0]            
            class_path = os.path.join(args.dataset_descriptor, dir_name)
            if not os.path.exists(class_path):
                 os.makedirs(class_path)

**Comment by davidsandberg** [comment]
Yes, I think you are right. However, since the release of MsCeleb-1M there is not the same need for this script any more. I will probably remove the script at some point.
