### ISSUE TITLE
how to get mtcnn five landmarks?

### ISSUE THREAD

**Issue by yanmenglu** [davidsandberg/facenet#335]
@davidsandberg ,Thank you for your great project.Now I met a qustion ,could you tell me how to solve it ?
that is ,if I want to get the face detection( mtcnn faces) five landmarks,how can I get it ?

**Comment by lrsperanza** [comment]
The mtcnn function for face detection on the example provided here on git
returns 2 values. The first are the bounding boxes and the second are the
face landmarks. The function is in a document named align_mtcnn.py I think.

Em 20 de jun de 2017 06:56, "yanmenglu" <notifications@github.com> escreveu:

**Comment by achbogga** [comment]
Please let me know exactly the variable and index which stores the landmark points once again. It is not clear from the answer above. Thanks.

**Comment by dkarunakaran** [comment]
@achbogga Did you end up creating alignment module?
