### ISSUE TITLE
IDs of training images

### ISSUE THREAD

**Issue by bkj** [davidsandberg/facenet#337]
Hi --

I was wondering whether you're able to post the IDs of the images you used to train, both for the Celeb-1M and CASIA datasets.  I've not been able to find live links to clean versions of these datasets, but it should be relatively easy to just distribute the list of filenames.

Thanks!

**Comment by MaartenBloemen** [comment]
If you search "Casia cleaned" on Google you should be able to find some forums with a link to download the cleaned dataset. If you really want a list of the cleaned IDs I could post it tomorrow, that is only for the Casia dataset though, haven't had time to clean out the MS-Celeb I also would be interested in a list of the cleaned MS-Celeb dataset.

**Comment by bkj** [comment]
Yeah there are bunch of links, but if it's not too much trouble the list would be super helpful to me.  Just something like
```
find ./ -type f | 
```
in the cleaned directory is presumably enough.

To be clear -- do you know whether the model trained on Celeb-1M in this repo was trained on the raw dataset or some cleaned version?

Thanks!

**Comment by MaartenBloemen** [comment]
For both Casia and MS-Celeb the model was trained on a cleaned version of the dataset.
I'll post a list for cleaned Casia IDs tomorrow, right now I don't have access to the computer were I stored the training sets.

**Comment by bkj** [comment]
Awesome -- thanks!

**Comment by MaartenBloemen** [comment]
As promised [here](https://drive.google.com/open?id=0BwLR3C1wiEDWNm90RVV4SG9IZEk) is the list of the cleaned casia dataset (folders are surrounded with "---"). But I fear it will not be useful as all the images are just numbered in sequence.

**Comment by bkj** [comment]
Sorry -- why do you think it won't be useful?

**Comment by MaartenBloemen** [comment]
The image names are in sequence 1.jpg, 2.jpg, 3.jpg, so you don't know, based on the name, which images in the original dataset don't belong there (wrong faces).

**Comment by bkj** [comment]
I don't think that's the case -- these are the counts of the names of the image files in the list of cleaned files you just sent
```
9656 009.jpg
9646 010.jpg
9584 005.jpg
9563 012.jpg
9558 004.jpg
9539 013.jpg
9511 011.jpg
9502 003.jpg
9471 008.jpg
9457 014.jpg
```
vs in the original CASIA dataset
```
  10575 002.jpg
  10575 001.jpg
  10574 004.jpg
  10574 003.jpg
  10572 005.jpg
  10569 006.jpg
  10567 007.jpg
  10562 008.jpg
  10556 009.jpg
  10545 010.jpg
  10533 011.jpg
  10504 012.jpg
```
So the list you just sent appears to be the original filenames -- does that make sense?  I think it's just hard to see by scanning the file because only ~5% of the filenames were removed in the cleaning.
