### ISSUE TITLE
How to download the model 20170512-11054

### ISSUE THREAD

**Issue by LSX1020** [davidsandberg/facenet#341]
I click the link in the web,the link can not be open

6. Run the test

The test is ran using validate_on_lfw:
python src/validate_on_lfw.py ~/datasets/lfw/lfw_mtcnnpy_160 ~/models/facenet/20170512-110547

This will 
a) load the model,
b) load and parse the text file with the image pairs, 
c) calculate the embeddings for all the images in the test set,
d) calculate the accuracy, validation rate (@FAR=-10e-3), the Area Under Curve (AUC) and the Equal Error Rate (EER) performance measures.

it says runing  python src/validate_on_lfw.py ~/datasets/lfw/lfw_mtcnnpy_160 ~/models/facenet/20170512-110547  will load the model, but I operate like above, it will give error that can not find the model 

how can I get the model 20170512-11054
Thank you very much!

**Comment by Bananajia** [comment]
https://github.com/davidsandberg/facenet
in the page you can see
model 20170512-11054 link
as well
https://drive.google.com/file/d/0B5MzpY9kBtDVZ2RpVDYwWmxoSUk/edit

**Comment by Bananajia** [comment]
@LSX1020 
https://github.com/davidsandberg/facenet
in the page you can see
model 20170512-11054 link
as well
https://drive.google.com/file/d/0B5MzpY9kBtDVZ2RpVDYwWmxoSUk/edit

**Comment by LSX1020** [comment]
in the page 
https://github.com/davidsandberg/facenet 
I can see mode  20170512-11054 link, but it can not be opened
https://drive.google.com/file/d/0B5MzpY9kBtDVZ2RpVDYwWmxoSUk/edit  is also can not be opened

thank you!
