### ISSUE TITLE
ResourceExhaustedError with GPU1

### ISSUE THREAD

**Issue by zhengge** [davidsandberg/facenet#342]
Hi @davidsandberg ,
when I run the code with GPU1，the issue arise
> ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[90,8,8,128]

I add the code in train_softmax.py,
```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
```
in order to use the GPU1.
Hope to get your help!

**Comment by davidsandberg** [comment]
Hi,
Try to set the batch_size to a small value. This will require less GPU memory when training.

**Comment by zhengge** [comment]
@davidsandberg Thanks.
