### ISSUE TITLE
Do we actually want `random_flip`?

### ISSUE THREAD

**Issue by bkj** [davidsandberg/facenet#344]
Was wondering whether it actually makes sense to train the model w/ `random_flip` data augmentation.  

Faces are asymmetric and presumably we'd want the model to be able to take advantage of that.  We don't really need a model that's invariant to mirror images, since these are relatively rare.

However -- empirically, does training w/ `random_flip` yield better results on standard benchmarks?

**Comment by davidsandberg** [comment]
Hi,
That's an interesting question. I haven't tested the difference between flipping and not flipping, and I guess it depends on the dataset that is used for training as well (i.e big dataset => less need for data augmentation). But I guess the cases where the model need to use information about left and right are also relatively rare.

**Comment by bkj** [comment]
Yeah, makes sense.  I may do a test at some point.  Will report here if I do.

I've read in some of the literature of people catting/summing the feature vectors of regular/horizontally flipped versions of the query images.
