### ISSUE TITLE
How to debug the two models，20170511-185253 and 20170512-110547？？

### ISSUE THREAD

**Issue by YjDai** [davidsandberg/facenet#347]
As the title, how to debug these two models, it is difficult for me to understand the meaning of the downloaded model? What is the process? Thx

**Comment by davidsandberg** [comment]
Have you seen the wiki, for example [this page](https://github.com/davidsandberg/facenet/wiki/Validate-on-LFW)?

**Comment by YjDai** [comment]
@davidsandberg Yes, I had read the wiki later, and verified the model on LFW. The process is clear in the wiki, thank you so much.
