### ISSUE TITLE
No module named 'facenet'

### ISSUE THREAD

**Issue by nosqlcoco** [davidsandberg/facenet#352]
I try to run Validate on LFW in windows, but failed until I reaching 4th step in [Validate on LFW docment](https://github.com/davidsandberg/facenet/wiki/Validate-on-lfw) .
My steps are as follows,
1. Install dependencies (TensorFlow 1.1.0,  Python 3.5),
2. Download the LFW dataset
3. Setenv
![default](https://user-images.githubusercontent.com/3488475/27476848-d3434030-583c-11e7-9593-0e90035352cc.png)
4. CD facenet dictory and input
`> python src\align\align_dataset_mtcnn.py datasets/raw datasets/lfw_mtcnnpy_160 --image_size 160 --margin 32 --random_order --cpu_memory_fraction 0.25`

but get an error:
`Traceback (most recent call last):
File "src\align\align_dataset_mtcnn.py", line 34, in <module>
    import facenet
ImportError: No module named 'facenet'`

The root of facenet folder and sub-folder contain '__init__.py' files,
I am trying to modify the file "src\align\align_dataset_mtcnn.py", line 34
`sys.path.append('D:/ai/tensorflow/facenet/src/facenet.py')` instead of  `import facenet`

but get an another error
`Traceback (most recent call last):
  File "src\align\align_dataset_mtcnn.py", line 35, in <module>
    import align.detect_face
ImportError: No module named 'align'`

so, I am very frustrated, could I runnig in windows?

**Comment by pavankumarkatakam** [comment]
Hi @nosqlcoco, Where did you added the env variable there is actually two places in `Environment Variable` window one is logged in user specific and other is System variable try to keep in System variables then you will not get the error

For cross checking open the command prompt and issue command `set` which will print out the all env if the path you give exist in the output of that command then it is working fine.

**Comment by nosqlcoco** [comment]
Thanks
