### ISSUE TITLE
Parameter settings for `20170511-185253`

### ISSUE THREAD

**Issue by bkj** [davidsandberg/facenet#356]
Hi --

I'm trying to reproduce the performance of the `20170511-185253` model, training on the CASIA dataset.  Using the following parameter settings from the wiki, I get LFW accuracy of `0.979667` for the final model.  

Are these the parameters that were used to train `20170511-185253`?  If not, are those parameters available somewhere?

Thanks!

```
export PYTHONPATH="./src"

# Align
for N in {1..4}; do
    python src/align/align_dataset_mtcnn.py \
        ./data/CASIA-WebFace-clean/ \
        ./data/casia_maxpy_mtcnnpy_182 \
        --image_size 182 --margin 44 --random_order --gpu-id 0 --gpu_memory_fraction 0.2 &
done

# Train

python src/train_softmax.py \
    --logs_base_dir ./logs \
    --models_base_dir ./models \
    --data_dir ./data/casia_maxpy_mtcnnpy_182 \
    --image_size 160 \
    --model_def models.inception_resnet_v1 \
    --optimizer RMSPROP \
    --learning_rate -1 \
    --max_nrof_epochs 80 \
    --keep_probability 0.8 \
    --random_crop \
    --random_flip \
    --learning_rate_schedule_file ./data/learning_rate_schedule_classifier_casia.txt \
    --weight_decay 5e-5 \
    --center_loss_factor 1e-2 \
    --center_loss_alfa 0.9
```

(Also, FWIW, in the last epoch of training loss is approx. 1.35 and regloss is approx. 1.06)

**Comment by MaartenBloemen** [comment]
With those exact same parameters from the Wiki when training on Casia i get:
```
Accuracy: 0.983+-0.006
Validation rate: 0.94667+-0.01592 @ FAR=0.00100
```
on the final model. I don't know anymore what the loss and the regg loss we're though.
Hope this helps!

**Comment by bkj** [comment]
Hm interesting.  So you're doing better than me but still not as good as the published model.  Do you know who trained the `20170511-185253` originally?

**Comment by MaartenBloemen** [comment]
I guess @davidsandberg did, but its normal not to get the exact same result. I've ran the training multiple times and the end result is always 0.98x, the only thing I'm not sure about is the validation rate, I don't know how that compares to the pretrained model.

**Comment by bkj** [comment]
Interesting.  To be clear -- are you using the MTCNN implementation in this repo?  Or the original MATLAB version?

**Comment by MaartenBloemen** [comment]
The MTCNN implementation

**Comment by bkj** [comment]
OK thanks.  I was actually just able to replicate the 
```
Accuracy: 0.983+-0.006
Validation rate: 0.94667+-0.01592 @ FAR=0.00100
```
results you've reported.  

I think I know what the issue was -- will post an update this evening when this model is done training.

**Comment by MaartenBloemen** [comment]
Great, I'm keen on hearing your results!

**Comment by bkj** [comment]
OK -- as far as I can tell, the issue is related to using the "fused batch norm" option in Tensorflow:

https://www.tensorflow.org/performance/performance_guide#use_fused_batch_norm

That page makes it sound like `fused=True` uses a newer, faster but identical batch norm implementation.  Before I ran training for the first time, I was seeing if there were any trivial ways to speed up training, so I set `fused=True`.  However, I trained ~ 3 models w/ fused batched norm and never broke `acc=0.979` whereas the one model I trained w/o fused batched norm got to `0.983`.  

I recognize there's variability between runs, so I guess take this as preliminary evidence.  I haven't looked at the batch norm vs. fused batch norm implementations to see if it's even possible that they give different results, but will post here with more info if I figure anything out.

**Comment by davidsandberg** [comment]
Thanks for the investigation! Closing this for now...

**Comment by jerryhouuu** [comment]
@bkj Please give me some advises about how to modify code to use fused-normalization
I tried to add fused: True, but it's not work. 
```
    batch_norm_params = {
        # Decay for the moving averages.
        'decay': 0.995,
        # epsilon to prevent 0s in variance.
        'epsilon': 0.001,
        # force in-place updates of mean and variance estimates
        'updates_collections': None,
        # Moving averages ends up in the trainable variables collection
        'variables_collections': [ tf.GraphKeys.TRAINABLE_VARIABLES ],
        'fused': True,  # Use fused batch norm if possible.
    }
```

I will get this error below:
```
"Cannot convert a partially known TensorShape to a Tensor: %s" % s)
ValueError: Cannot convert a partially known TensorShape to a Tensor: (?, 128)
```

**Comment by AlexeyAL1e** [comment]
Okay, this repository has a huge number of problems, but I'm gradually trying to solve them.
Firstly, I formed my dataset of 30 personalities, each person has 34 face photos. after that i used [these](https://github.com/davidsandberg/facenet/issues/356#issue-238421699) commands to align and get the loss with using script `softmax.py`
Second, I had to run this script to get the `.pb` file
`python src/freeze_graph.py .model_dir output_file.pb`
Thirdly I got a .pkl file using this
`python src/classifier.py TRAIN ~/datasets/my_dataset/train/ ~/models/model-20170216-091149.pb ~/models/my_classifier.pkl --batch_size 34`
Now, I use my model to identify faces in my test dataset, with run script:
 `python src/classifier.py CLASSIFY ~/datasets/my_dataset/test/ ~/models/model-20170216-091149.pb ~/models/my_classifier.pkl --batch_size 34`
but I get an error `Found array with 0 sample(s) (shape=(0, 512)) while a minimum of 1 is required`, it looks like the file `.pkl`, there are no entries for embedded images
Tell me, if these are all points, then what am I doing wrong? @[bkj](https://github.com/bkj) @[MaartenBloemen](https://github.com/MaartenBloemen) @[jerryhouuu](https://github.com/jerryhouuu)
