### ISSUE TITLE
align_dataset_mtcnn.py:OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by limTeTE** [davidsandberg/facenet#358]
I run the tutorial on this [wiki](https://github.com/davidsandberg/facenet/wiki/Validate-on-LFW), and i met this 
problem:

- Traceback (most recent call last):
- File "/mnt/a/liujialin/mission/facenet/src/align/align_dataset_mtcnn.py", line 146, in 
- main(parse_arguments(sys.argv[1:]))
- File "/mnt/a/liujialin/mission/facenet/src/align/align_dataset_mtcnn.py", line 46, in main
- facenet.store_revision_info(src_path, output_dir, ' '.join(sys.argv))
- File "/mnt/a/liujialin/mission/facenet/src/facenet.py", line 496, in store_revision_info
- gitproc = Popen(['git', 'rev-parse', 'HEAD'], stdout = PIPE, cwd=src_path)
- File "/usr/lib/python2.7/subprocess.py", line 710, in init
- errread, errwrite)
- File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
- raise child_exception
- OSError: [Errno 2] No such file or directory

Any suggestions ? Thank you.

**Comment by limTeTE** [comment]
message above is a little messy, recopy it here:

Traceback (most recent call last):
  File "/mnt/a/liujialin/mission/facenet/src/align/align_dataset_mtcnn.py", line 146, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "/mnt/a/liujialin/mission/facenet/src/align/align_dataset_mtcnn.py", line 46, in main
    facenet.store_revision_info(src_path, output_dir, ' '.join(sys.argv))
  File "/mnt/a/liujialin/mission/facenet/src/facenet.py", line 496, in store_revision_info
    gitproc = Popen(['git', 'rev-parse', 'HEAD'], stdout = PIPE, cwd=src_path)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by limTeTE** [comment]
Ah, I solved this by adding 'shell=True' to the 'Popen'  function in facenet.store_revision_info():
 
- gitproc = Popen(['git', 'rev-parse', 'HEAD'], stdout = PIPE, cwd=src_path, shell=True)
- gitproc = Popen(['git', 'diff', 'HEAD'], stdout = PIPE, cwd=src_path, shell=True)

the reason may be demostrated by [doc](https://docs.python.org/2/library/subprocess.html#frequently-used-arguments) as:
If passing a single string, either shell must be True or else the string must simply name the program to be executed without specifying any arguments.

**Comment by i161079** [comment]
May I ask you to solve this problem in detail?

**Comment by limTeTE** [comment]
@i161079 sorry, i forgot the details after almost 3 months

**Comment by i161079** [comment]
@limTeTE  Thank you. I made a change based on your last answer. It has been successful

**Comment by limTeTE** [comment]
You're welcome.and i think maybe you could supply more details about the
original answer for others in the future, mine is too short.

2017-10-10 15:18 GMT+08:00 笑话 <notifications@github.com>:
