### ISSUE TITLE
Intention: to detect more number of  faces using the method bulk _detect _face 

### ISSUE THREAD

**Issue by harishank** [davidsandberg/facenet#360]
How to detect Bulk Faces in a image:

what  i did:

1.i have an image with 10 faces of different sizes.
2.i run mtcnn and call the detect face method from detectface.py file
3.i got 3 detected faces.

what i want:

1.i plan to run bulk detect face  method to find 10 faces.
2.what value should i assign for variable "detection_window_size_ratio"
3.how to run to get 10 faces in an image.

**Comment by davidsandberg** [comment]
The normal face detector detects multiple faces. But in later stages in the alignment process the largest and most centered face are selected.
