### ISSUE TITLE
ValueError when use compare.py

### ISSUE THREAD

**Issue by Akemi-Homura** [davidsandberg/facenet#362]
I tried both models '20170511-185253' and '20170511-185253' but got the same error
```
ValueError Cannot feed value of shape (1, 240, 240, 4) for Tensor 'pnet/input:0', which has shape '(?, ?, ?, 3)'
```

This is the iamge which caused the error
![1](https://user-images.githubusercontent.com/16780053/27820121-dae8c4b8-60cf-11e7-9e54-e6a0ff9f6620.png)

**Comment by AKSHAYUBHAT** [comment]
Its a png with RGBA (4 Channels) thus there is a mismatch, you can either convert all images to jpeg or sent channels=3 in the tf decode op

**Comment by Akemi-Homura** [comment]
@AKSHAYUBHAT Thank you very much ! I changed images to jpg and it works well ! :)
