### ISSUE TITLE
Problem with training dataset structure

### ISSUE THREAD

**Issue by emlacuden** [davidsandberg/facenet#364]
Hi everybody,
I try to setup and run the facenet.
When i training the data and i got this error:
./models/20170512-110547.pb ./models/my_classifier.pkl --batch_size 100
src/classifier.py:59: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(len(cls.image_paths)>0, 'There must be at least one image for each class in the dataset')
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
### Number of images: 49

=> i dont understand that  above said that "There must be at least one image for each class in the dataset" but after that the message is : ### Number of classes: 6

**Comment by davidsandberg** [comment]
Hi,
There is no problem with your dataset but the assert in the code is not correct and you could disregard from the warning you get.

**Comment by louiseruiwenli** [comment]
I got a similar problem. The number of classes shown is 5 but I actually only have 2 subfolders. Why is the number of classes detected to be so many?

**Comment by tusharc** [comment]
@louiseruiwenli You might have some hidden subfolders that are also getting counted. 
Try `ls -al` in a bash environment to confirm.
