### ISSUE TITLE
A minor doubt on coding.

### ISSUE THREAD

**Issue by Zhengtq** [davidsandberg/facenet#365]
In file src/facenet.py,  for line 431 and 432, does it better to put  `tpr = np.mean(tprs,0)
  | `fpr` = np.mean(fprs,0)` outside the 'for loop'？

**Comment by zixia** [comment]
I agree. It seems wired inside the loop.

https://github.com/davidsandberg/facenet/blob/85543a357d4901498404109faff7094f70af45e9/src/facenet.py#L436

I guess if you submit a PR of this, @davidsandberg will accept it.

**Comment by davidsandberg** [comment]
Thanks!
This has been fixed in 74be24fa9962d15a81959f18b323cd9c5b70489f.
