### ISSUE TITLE
Using Facenet to get Facial Action Units

### ISSUE THREAD

**Issue by mayank26saxena** [davidsandberg/facenet#367]
I have previously tried Open Face, which gives me the facial action units but, the majority of the time it isn't able to detect the face in the data I am using it on. 

However, Facenet detects the face and gives me the bounding box as well as the landmarks. I was wondering if there is a way to get the facial action units after the landmarks have been detected.

**Comment by davidsandberg** [comment]
Currently this project makes use of MTCNN for face detection. I'm not sure how to calculate facial action units but it should be possible to use the MTCNN face detector togehter with open face. But it should be noted that MTCNN only detects 5 landmarks as compared to dlib's 69, and maybe that can be a problem for you.
