### ISSUE TITLE
Get more than 5 facial landmarks

### ISSUE THREAD

**Issue by mayank26saxena** [davidsandberg/facenet#368]
Is it possible to get more than 5 (possibly all 68, like in dlib) facial landmark units using Facenet?

**Comment by achbogga** [comment]
I don't think so. The second vector returned by this detect_face has only 10 points.

**Comment by davidsandberg** [comment]
There are five landmarks detected by MTCNN and these are left eye, right eye, nose, left mouth corner, and right mouth corner. It would not be straight forward to detect a larger number of landmarks.

**Comment by mayank26saxena** [comment]
Thanks for the response @davidsandberg and @achbogga 

Any idea if it will be possible to detect emotions from only 5 facial landmarks?

**Comment by RakshakTalwar** [comment]
@mayank26saxena you could train on a picture of the whole face instead of the landmarks
