### ISSUE TITLE
classify images

### ISSUE THREAD

**Issue by rasmushaglund** [davidsandberg/facenet#37]
OpenFace has a way of classifying images to get a prediction based on the target labels. Is that implemented in facenet? From what I can see facenet does the embedding, but hasn't implemented training for image -> embedding -> label. If it isn't implemented, what would be the best way to do that?

**Comment by davidsandberg** [comment]
There is a first version of something similar on a separate branch called "classifier_pretrain". The goal with this branch was to bootstrap training by first training the network as a classifier and after convergence swapping the last fully connected layer with one that maps the output from the network to an embedding, trained using triplet loss. But this code is quite untested yet, but it would be nice to merge the two ways of training into one if it doesn't mess up the code too much.

**Comment by rasmushaglund** [comment]
Ok cool, I'll check that out and see if I could make something out of it. I guess it could be a good example to include in facenet.
