### ISSUE TITLE
WIDER or FDDB eval for your MTCNN?

### ISSUE THREAD

**Issue by jackculpepper** [davidsandberg/facenet#371]
Nice code! Thank you for sharing it.

Have you benchmarked your translation/re-implementation of MTCNN against WIDER or FDDB? You wrote:

"A Python/Tensorflow implementation of MTCNN can be found here. This implementation does not give identical results to the Matlab/Caffe implementation but the performance is very similar."

What did you mean by "the performance is very similar"? I set the minsize, scale factor, and threshold parameters in your code as the authors indicate here:

https://github.com/kpzhang93/MTCNN_face_detection_alignment/tree/master/code/codes

However, I found the bounding boxes produced by your detector to give significantly lower AP on WIDER (val). I would be happy to share a PR if you are interested.

Best,

Jack

**Comment by davidsandberg** [comment]
Hi,
I would be happy to accept a PR with the evaluation code.
I didn't manage to get identical results to the caffe implementation and the reason seemed to be different precision between matlab/caffe (64 bit) compared to tensorflow (32 bits). This resultet in differencies in the probability score for the highest scored bounding boxes. It would be very nice to fix this to get bit exact results but it worked well enough for the CNN model to give the same performance and that was good enough for me. Maybe the performance could be improved by retraining the models.
