### ISSUE TITLE
It seems that mismatch exists between outputs of MTCNN and inputs of inception-resnet-v1 

### ISSUE THREAD

**Issue by xs-han** [davidsandberg/facenet#373]
I am a beginner of the face recognition. In my view, inception-resnet-v1 (https://arxiv.org/abs/1602.07261) accepts a 299x299 image as the input, but in the "Validate on LFW" example, it seems that 160x160 aligned faced are cropped.
So,  how can the inception-resnet-v1 accept 160x160 cropped images as inputs? Thank you!

**Comment by davidsandberg** [comment]
Hi,
It's typically no problem to use a different input size. But of course the number of parameters will be smaller and this can perhaps reduce the performance slightly.
