### ISSUE TITLE
how to create pairs.txt for custom dataset 

### ISSUE THREAD

**Issue by vijaysagi** [davidsandberg/facenet#376]
Hi

i have custom dataset available,  for which i need to  train the dataset using  the approach **validate_on_lfw.py** for which lfw_pairs is the argument.

Pls suggest how to create pairs.txt.

Is it mandatory to create pairs.txt to train the custom datset ?

Thanks
vijay

**Comment by davidsandberg** [comment]
Hi,
If you want to use your own dataset for evaluation the easiest way is probably to create your own evaluation script based on 'validate_on_lfw.py'.  You would then  create 
`paths` and `actual_issame` to correspond to your own dataset.

**Comment by vijaysagi** [comment]
Tried the best i can but somehow i was not sucessful till now
 can u pls share  the logic like how to create pairs.txt

**Comment by davidsandberg** [comment]
You can have a look at e.g. compare.py.

**Comment by modanesh** [comment]
Hey @vijaysagi,

Have you successfully train and evaluate your custom dataset?

I have the same problem.

**Comment by allahbaksh** [comment]
@davidsandberg I just looked at compare.py. Essentially it is calculating the distance between the images. Should we use the distance between images to create the pair.txt?

**Comment by khaerulumam42** [comment]
I have the same problem @vijaysagi , do you have solved this problem?

**Comment by Dyex719** [comment]
Refer to http://vis-www.cs.umass.edu/lfw/README.txt to see the structure of the pairs.txt file.
I was able to find the accuracy given by the pre-trained openface model on a custom dataset.

I followed the procedure given in the sub-section Running The LFW Experiment at https://cmusatyalab.github.io/openface/models-and-accuracies/ 

To generate a pairs.txt you can consider writing a script, something like the following:
```
# Make all matches
for name in os.listdir("./dlib-affine-sz:96/"):
    a = []
    for file in os.listdir("./dlib-affine-sz:96//" + name):
        a.append(file)
    with open("pairs.txt","a") as f:
        for i in range(3):
            temp = random.choice(a).split("_") # This line may vary depending on how your images are named.
            w = temp[0] + "_" + temp[1]
            f.write(w + "\t" + random.choice(a).split("_")[2].lstrip("0").rstrip(".png") + "\t" + random.choice(a).split("_")[2].lstrip("0").rstrip(".png") + "\n")
# Make all mismatches
for i,name in enumerate(os.listdir("./dlib-affine-sz:96//")):
    remaining = os.listdir("./dlib-affine-sz:96//")
    del remaining[i] # deletes the file from the list, so that it is not chosen again
    other_dir = random.choice(remaining)
    with open("pairs.txt","a") as f:
        for i in range(3):
            file1 = random.choice(os.listdir("./dlib-affine-sz:96//" + name))
            file2 = random.choice(os.listdir("./dlib-affine-sz:96//" + other_dir))
            f.write(name + "\t" + file1.split("_")[2].lstrip("0").rstrip(".png") 
```

Ensure that you generate the pairs.txt file after you perform the dlib affine transform as some files are lost in the process (cannot be aligned properly).

The above code is very hacky, and does not check for duplicates, however this can be done easily by considering sets.

**Comment by VictorZhang2014** [comment]
Thank you! @Dyex719  Generate Pairs code is very useful!~

I made it as a class, running well on Python3. https://github.com/VictorZhang2014/facenet/blob/master/mydata/generate_pairs.py

**Comment by khadijakhaldi** [comment]
Please, how can pairs.txt used in plotting the roc ?
