### ISSUE TITLE
issues when i try to train my own model using train_softmax.py

### ISSUE THREAD

**Issue by recordcode** [davidsandberg/facenet#379]
When I try to train my own model using 5000000 pictures, my host memory(not GPU) is 8GB and it's  not enough to train,right? The errors are as follows:
![image](https://user-images.githubusercontent.com/5369259/28262025-1ada89fa-6b14-11e7-951c-1bf49eca7db0.png)
![image](https://user-images.githubusercontent.com/5369259/28262060-4b90bf24-6b14-11e7-941c-35ad82cef08a.png)
![image](https://user-images.githubusercontent.com/5369259/28262083-5d797410-6b14-11e7-9b9c-5a32017349a8.png)
What should I do?

**Comment by recordcode** [comment]
Thanks in advance and Thanks to @davidsandberg for his effort.

**Comment by mingfengwuye** [comment]
Modify the “gpu_memory_fraction” argument to a smaller one, such as 0.4

**Comment by davidsandberg** [comment]
Hi,
Assuming that it works fine for smaller datasets you can try to reduce the memory footprint by removing `train_set` variable, but it needs to be done after the line
```
        image_list, label_list = facenet.get_image_paths_and_labels(train_set)
```
and it should be something like
```
        del train_set
```

**Comment by recordcode** [comment]
Hi,
It works fine for smaller datasets, I have tried. As you say, Instead of using train_set, I build a txt file to put my path of all the pictures. Then I use python to read the txt file to get the image_list and label_list. In this way, I still met errors like above. @davidsandberg  Thank U, what can I do?
Thank U @mingfengwuye  , the reason isn't lack of gpu memory. It's host memory(8 GB).

**Comment by Victoria2333** [comment]
Hi,@recordcode ,i'm intereted in your question
If i want to test one image,and the result will cirle out the faces in the image and label his or her name beside the bounding boxes,so how to run this code to train my own model and  how to modify this code to accomplish my goal?
Thanks,very much!

**Comment by davidsandberg** [comment]
Closed due to inactivity. Reopen if needed.
