### ISSUE TITLE
Aligning facescrub data-set for training 

### ISSUE THREAD

**Issue by kdkalvik** [davidsandberg/facenet#38]
Do we have to use align_dataset.py for facescrub? The dataset had folders with picures of different people but it also has a folder with cropped faces.If we are supposed to use only the cropped faces how can I feed the images to facenet and If I have to use align_dataset.py does it drop the folder with the cropped faces?

**Comment by davidsandberg** [comment]
For the training I have used the same face alignment (i.e. align_dataset.py) for both the training dataset (Facescrub and Casia-WebFace) and the test dataset (LFW). I don't think it absolutely required to do it like that but I think it's a reasonable starting point. But the dlib face alignment (that is used by align_dataset.py) does not handle e.g. profile images very well so there could be some performance to gain by using pre-aligned images instead. But there are also more potential sources of error with that approach. 
You are right that the cropped faces of FaceScrub is typically not used.
