### ISSUE TITLE
About the accuracy on LFW

### ISSUE THREAD

**Issue by sczhengyabin** [davidsandberg/facenet#384]
I am wondering if the 0.992 +- 0.003 is the highest accuracy during training, or at the end model converged to it?
@davidsandberg

**Comment by davidsandberg** [comment]
It's the accuracy for the model at the end of training, as you get when running `validate_on_lfw.py`.

**Comment by Wunian1314521** [comment]
@davidsandberg 这个validate_on_lfw.py文件运行后，获得的参数值，是怎么定义的，有数据过程嘛
