### ISSUE TITLE
I am trying to extract the embedding but I am getting this error

### ISSUE THREAD

**Issue by aldarabs** [davidsandberg/facenet#388]
Hello guys, 
I am trying to extract the embedding from the network. However, I am getting this error

Traceback (most recent call last):
  File "get_dataset_embeddings_as_pkl.py", line 100, in <module>
    emb_array[start_index:end_index,:] = sess.run(embeddings, feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 975, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (5, 244, 244, 3) for Tensor u'input:0', which has shape '(?, 224, 224, 3)'

I am training using my own dataset.

Please advice.

**Comment by cjekel** [comment]
Have you tried tmp/export_embeddings.py

I don't see the get_dataset_embeddings_as_pkl.py file

**Comment by aldarabs** [comment]
It is a similar code to export_embeddings.py.

**Comment by davidsandberg** [comment]
It looks like you are feeding the images with the wrong size to you model. The model expects images of the size 224x224x3.

**Comment by aldarabs** [comment]
It worked!!

Thank you
