### ISSUE TITLE
Training from scratch fails

### ISSUE THREAD

**Issue by kdkalvik** [davidsandberg/facenet#39]
I am trying to train from scratch but when I start training I get the following error
Traceback (most recent call last):
  File "facenet_train.py", line 257, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "facenet_train.py", line 47, in main
    pairs = lfw.read_pairs(os.path.expanduser(args.lfw_pairs))
  File "/home/kalvik/facenet/facenet/src/lfw.py", line 64, in read_pairs
    with open(pairs_filename, 'r') as f:
IOError: [Errno 2] No such file or directory: '../data/pairs.txt'

**Comment by iqbalnaved** [comment]
I commented out the validation part with lfw, since I didn't have the data. you can do that to, otherwise try giving absolute path

**Comment by kdkalvik** [comment]
But isn't the pairs.txt supposed to be generated by the triplet selection function?

**Comment by davidsandberg** [comment]
The pairs file is only used for evaluating the performance on LFW. It should be perfectly fine to just comment out the lines related to LFW evaluation.
If you want to use the LFW evaluation you could follow the steps [here](https://github.com/davidsandberg/facenet/wiki/Validate-on-lfw) to download the pairs.txt file etc.

**Comment by kdkalvik** [comment]
Could you please provide the link for pairs.txt. In section 5 you didn't provide a link.

**Comment by davidsandberg** [comment]
The pairs file can be found [here](http://vis-www.cs.umass.edu/lfw/pairs.txt).

**Comment by kdkalvik** [comment]
Perfect Thank you.
