### ISSUE TITLE
Center loss, Regularization loss, Cross Entropy is strange.

### ISSUE THREAD

**Issue by apollo-time** [davidsandberg/facenet#390]
I train the facenet with center loss on MS Celeb 1M.
I put center and regularization loss log with cross entropy.
![center_loss](https://user-images.githubusercontent.com/9794932/28498757-af5af5ca-6fd7-11e7-9d11-bb47110169bf.png)
![cross_etropy](https://user-images.githubusercontent.com/9794932/28498758-af601c44-6fd7-11e7-9397-9f1bbb7dbee7.png)
![lfw_accuracy](https://user-images.githubusercontent.com/9794932/28498761-af62162a-6fd7-11e7-82f9-6197c1f9a08d.png)
![regularization_loss](https://user-images.githubusercontent.com/9794932/28498759-af610f5a-6fd7-11e7-9011-9d0fcb7dad05.png)
![total_loss](https://user-images.githubusercontent.com/9794932/28498760-af615e6a-6fd7-11e7-9a5e-bc47b8936b26.png)

training parameters is --weight_decay 5e-5 --center_loss_factor 5e-5 --center_loss_alfa 0.9.
1. Is useful center loss? I show the center loss value is very small in total loss.
2. Is not strange the regularization loss?

**Comment by davidsandberg** [comment]
Closing this for now. Reopen if needed.
