### ISSUE TITLE
batch size for training ms-celeb dataset

### ISSUE THREAD

**Issue by ForestWang** [davidsandberg/facenet#392]
what's the batch size for training ms-celeb dataset？ my GPU memory is 12G, the 64 batch size will cause oom. if it is smaller than 64, will it affect the result?

thanks.

**Comment by recordcode** [comment]
128 is fine. But I try to train MS (5000k pictures). It stuck in the last code in the picture(enqueue_op). Can you train MS now?
![image](https://user-images.githubusercontent.com/5369259/28661095-2517b722-72e8-11e7-9dd1-f99579d1af84.png)

**Comment by TianwenWei** [comment]
@ForestWang I use 1080 with 8G memory yet batch_size=64 works

**Comment by recordcode** [comment]
@TianwenWei  Can you use MS (5000k pictures) to train your own model?  Can I cantact you with qq or E-mail or something else? I want to ask you something. Thanks a lot!

**Comment by TianwenWei** [comment]
@recordcode yes you can contact me via email <first_name>.<last_name>@qq.com

**Comment by recordcode** [comment]
@TianwenWei  Do you mean weitianwen@qq.com? Perhaps I sent a e-mail to a wrong address..

**Comment by TianwenWei** [comment]
@recordcode Here is my QQ number: 181962352
