### ISSUE TITLE
why not using the same tf.session in tmp/export_embeddings.py

### ISSUE THREAD

**Issue by pavankumarkatakam** [davidsandberg/facenet#394]
Hi Im understanding the `export_embedding.py` file and has a doubt that for every batch creating tf.sessions in load_and_align_data function is this done intensionally? can we use same tf session for loading the facenet model as well as MTCNN networks (  pnet, rnet, onet).

**Comment by davidsandberg** [comment]
Closed due to inactivity. Reopen if needed.
