### ISSUE TITLE
can I use the code to compare to picture?

### ISSUE THREAD

**Issue by tonybaigang** [davidsandberg/facenet#396]
I found there is a file named compare.py. can I use the code to compare to picture? How?

**Comment by surajitsaikia27** [comment]
yes you can do so.
you just need to give path to the model and image folder.
For example: in the terminal you can type (assuming from the root)
facenet-master$python classify.py  pathtothemodel/model.pb  pathtoimages/*jpg

Each of the image will be compared against all other images in the folder :)

Hope it might help you

**Comment by tonybaigang** [comment]
it works well, thank @surajitsaikia27

**Comment by tlindener** [comment]
Do you guys know an efficient way to store the DNN results in a database and calculate distance only for new "incoming" pictures?
