### ISSUE TITLE
how to get a picture‘s embedding vector?

### ISSUE THREAD

**Issue by wjqy1510** [davidsandberg/facenet#397]
I'm a newer , i want to get a new picture‘ vecotr, how should i do ?

**Comment by davidsandberg** [comment]
You can use 'export_embeddings.py' in the tmp folder.

**Comment by mayank1123** [comment]
The file is in contributed folder.

**Comment by MdAshrafulAlam** [comment]
@davidsandberg does export_embeddings.py give the feature vector for further work?

**Comment by Estapraq** [comment]
When I do that my program takes time to go through the weights every time I lunch it, not ideal for life application. Any suggestion?
