### ISSUE TITLE
Detecting multiple faces in one image using compare.py

### ISSUE THREAD

**Issue by surajitsaikia27** [davidsandberg/facenet#400]
Hi,
I was working with the compare.py code. I am wondering how can i get bounding box coordinates of the multiple people detected in a single image. A single picture may contain more than one face.

But I see that only one face is detected in an image with more than one people?

**Comment by pavankumarkatakam** [comment]
Actually code in `compare.py` is doing the multiple face detection only but in this [line](https://github.com/davidsandberg/facenet/blob/master/src/compare.py#L97) he is taking only one face by squeezing, remove this line and if you do looping of `bounding_boxes` then you will get all the faces in single image.

**Comment by surajitsaikia27** [comment]
Thanks a lot :). 
I was new to the code and would have spent lots of time. Thanks again
