### ISSUE TITLE
CUDA_ERROR_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by quickj** [davidsandberg/facenet#402]
@davidsandberg Even i have set the batch_size to 1, also occur this error 
**I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0)
E tensorflow/stream_executor/cuda/cuda_driver.cc:924] failed to allocate 5.93G (6365773824 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY**

**Comment by pavankumarkatakam** [comment]
Try to change GPU memory fraction yo 0.9 or 0.8

**Comment by quickj** [comment]
@pavankumarkatakam thanks

**Comment by KLH1472** [comment]
@pavankumarkatakam Great! Thanks!
