### ISSUE TITLE
where to find the model file?

### ISSUE THREAD

**Issue by tonybaigang** [davidsandberg/facenet#404]
Hi, Experts
I had try to train the model. After the training finish, I can find some files under the folder of models, includes: .meta, .index, .data-00000-of-00001 and checkpoint, but can not find the .pb file. 
Where can I get the .pb file, which can be used for compare.

**Comment by MaartenBloemen** [comment]
You have to freeze it yourself using freeze_graph.py

**Comment by tonybaigang** [comment]
Thanks, it works well
