### ISSUE TITLE
Should we add collection for triplet_loss?

### ISSUE THREAD

**Issue by icodingc** [davidsandberg/facenet#41]
I find a collection "losses" for cross_entropy_mean in [facenet_train.py](https://github.com/davidsandberg/facenet/blob/master/facenet/src/facenet_train.py#L85).

but in function [_add_loss_summaries](https://github.com/davidsandberg/facenet/blob/master/facenet/src/facenet.py#L51) we always use collection "losses" .
if we should add a collection for triplet_loss?

**Comment by davidsandberg** [comment]
Rewriting the facenet_train.py so I'm closing this for now.
