### ISSUE TITLE
Thresholding distance for each identity verfication

### ISSUE THREAD

**Issue by JIEMIN1995** [davidsandberg/facenet#413]
Hi, I am replicating the face verification part and use my own dataset to test. But the size of testing dataset is small so that I cannot draw ROC curve. Is there any other methods to determine thresholding distance? I set the unified threshold value manually for all identities but the performance is not good. Can I set threshold for each identity to get better performance?

**Comment by Paleve** [comment]
For me, I set the distance threshold as 0.5

**Comment by pavankumarkatakam** [comment]
Hi @paleve, is 0.5 is enough for your dataset is there any false positive predictions?
