### ISSUE TITLE
Inference speed is around 18 samples/sec. Is that normal?

### ISSUE THREAD

**Issue by patrickliao2007** [davidsandberg/facenet#422]
With some slightly changes to validate_on_lfw.py, I run the inference model on a single Titan X. The speed is only around 18 samples/sec.  Is that normal? How could I boost it?

**Comment by JianbangZ** [comment]
No, it's abnormal. when I use batch_size=128, my inference speed is around 1600 images/sec with Titian X (Maxwell).
Please make sure you use CUDA 8.0, cudNN v5.x. Also try to test with a larger batch_size, usually single image inference speed is quite slow on GPU
