### ISSUE TITLE
Sharing tool to scrape face images from Google.

### ISSUE THREAD

**Issue by sczhengyabin** [davidsandberg/facenet#425]
Hi everyone:
    Months ago I started to build my own face dataset. I wrote several tools to accomplish this target. 
    The most useful one I thought, among those tools, is the one that scrap images from search engine based on keywords, and do concurrent download afterwards.
    It's easy to use, and has both command-line version and gui version.
    It has already helped some people to collect their own image dataset. 
    I want to share this tool with you guys hoping to help more.
    Here is the project link:
[https://github.com/sczhengyabin/Image-Downloader](https://github.com/sczhengyabin/Image-Downloader)
    Have fun with it!

**Comment by davidsandberg** [comment]
Looks really nice! Thanks!!
