### ISSUE TITLE
Add full wiki

### ISSUE THREAD

**Issue by Zumbalamambo** [davidsandberg/facenet#426]
Please add wiki on  
    1) how do I train with new faces 
    2) How do I recognize the trained faces.

**Comment by MaartenBloemen** [comment]
Have you seen the [Train a classifier on own images](https://github.com/davidsandberg/facenet/wiki/Train-a-classifier-on-own-images) page on the wiki? That explains exactly what you are asking for.

**Comment by Zumbalamambo** [comment]
Im ran the following script

```
sudo python align/align_dataset_mtcnn.py /datasets/lfw/raw /datasets/lfw/lfw_mtcnnpy_160 --image_size 160 --margin 32 --random_order --gpu_memory_fraction 0.25 
```

It is firing the following error
ERROR:

```
Traceback (most recent call last):
  File "align/align_dataset_mtcnn.py", line 34, in <module>
    import facenet
ImportError: No module named 'facenet'
```

**Comment by Zumbalamambo** [comment]
Ofcourse I ran the comman `export PYTHONPATH=/Users/zumbala/Documents/facenet/src/` before running

**Comment by MaartenBloemen** [comment]
From the looks of the path I take it you are on Windows? Setting the PYTHONPATH on windows is slightly different than on Linux, on the wiki everything is explained for Linux.

Anyway you can find an explanation on how to set the PYTHONPATH [here](https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-7).

Hope this helps you!

**Comment by Zumbalamambo** [comment]
No.. Im using mac....

**Comment by MaartenBloemen** [comment]
Well that's really weird then... What is the output of `echo $PYTHONPATH` after you do the export?

**Comment by Zumbalamambo** [comment]
it says `:/Users/zumbala/Documents/facenet/src`

**Comment by MaartenBloemen** [comment]
Well I don't see why you would get that error then, the only other thing I can think of that you can try is putting the export directly into your .bashrc at least if Mac has that, I've never used Mac so I don't know much about it sorry.

**Comment by Zumbalamambo** [comment]
i simply copy pasted everything from align folder to root and it worked. thank you

**Comment by AlexeyAL1e** [comment]
> Я просто скопировал и вставил все из папки выравнивания в корень, и это сработало. благодарю вас

please write how did you do it?
