### ISSUE TITLE
Why the dataset has to be aligned

### ISSUE THREAD

**Issue by Zumbalamambo** [davidsandberg/facenet#429]
i ran the following script ,

`sudo python align_dataset_mtcnn.py /datasets/lfw/raw /datasets/lfw/lfw_mtcnnpy_160 --image_size 160 --margin 32 --random_order --gpu_memory_fraction 0.25 `

May I know what this script basically does? why do we have to align it? [This](https://github.com/davidsandberg/facenet/wiki/Validate-on-lfw#4-align-the-lfw-dataset) doesn't explain why alignment is necessary

**Comment by maria8899** [comment]
The code in the repository does not do a proper facde alignment. In fact, it does not even use the facial landmarks points from MTCNN. All it does is recropping the image based on the face detected bounding box.

There are some papers claiming that doing alignement does not help in training DCNN for face recognition. See for example http://openaccess.thecvf.com/content_cvpr_2017_workshops/w6/papers/Ferrari_Investigating_Nuisance_Factors_CVPR_2017_paper.pdf

**Comment by Zumbalamambo** [comment]
okay thank you...
