### ISSUE TITLE
Deep funneling in FaceNet

### ISSUE THREAD

**Issue by Jusya** [davidsandberg/facenet#43]
Hello,
My question is about Deep funneling in FaceNet. We've achieved high accuracy (about 92%) on deep-funneled LFW, but was the model "model-20160506.ckpt-500000" trained on deep-funneled FaceScrub and CASIA-Webface images? If it so, could somebody share the link to implementation of deep-funneling algorithm, to apply it to the result from Viola-Jones or DLib before FaceNet CNN?
Or, if it isn't necessary, could, please, somebody explain me why? 
I know, that it is not the issue that is directly refereed to this FaceNet implementation, but I hope you will understand my curiosity)
Waiting for your answer.

**Comment by davidsandberg** [comment]
Hi,
The model you are referring to has been trained on a combination of CASIA-WebFace and FaceScrub datasets aligned using the Dlib face alignment (and align_dataset.py). No deep funneled images has been used for the training set. With the Dlib face alignment quite a few faces are missed and these images will not be included in the training set. For the CASIA-WebFace dataset i think this is around 50 000 images out of 490 000. This effectively filters out some of the difficult examples from the training set, like faces with sun glasses and other partially occluded images. My feeling is that this makes the training set a bit too "easy".
I have tried a couple of alternative face alignment algorithms, like [Clandmark](http://cmp.felk.cvut.cz/~uricamic/clandmark/) but this one missed more faces than Dlib on the LFW dataset. Currently I'm trying [TCDCN](http://mmlab.ie.cuhk.edu.hk/projects/TCDCN.html) which looks promising but I haven't used it for training yet. And [here](http://theonly1.tistory.com/entry/Facelandmarksdetectionbenchmark) you can find a nice list of face alignment packages.

**Comment by Jusya** [comment]
You helped me a lot to understand how this face recognition system works)
I'm very thankful to you!
I'm going to play with different face alignments you suggested)
