### ISSUE TITLE
use nets(models) from tensorflow repository

### ISSUE THREAD

**Issue by alirezaweb** [davidsandberg/facenet#430]
hello,
in your model directory, there are two models,
but there are slightly different with the tensorflow models! 
for example the inception_resnet_v2 in a tensorflow repository:
https://github.com/tensorflow/models/blob/e46ec60235ecdf34dd65f263a5bd47d25fc2a50c/slim/nets/inception_resnet_v2.py
and in your repository:
https://github.com/davidsandberg/facenet/blob/master/src/models/inception_resnet_v2.py

How can I change the tensorflow  models/slim/nets/ in an appropriate style for a facenet?
I cant just copy and paste in a model directory of facenet.
thanks

**Comment by davidsandberg** [comment]
Copy and paste should be fine.
