### ISSUE TITLE
how to compare 2 images and get the distance?

### ISSUE THREAD

**Issue by patienceFromZhou** [davidsandberg/facenet#434]
the tutorial shows how to calculate it on the lfw data set but can i compare just 2 images using classifier.py or compare,py..  or if i had to rewrite some of  the code?

**Comment by Dicksonchin93** [comment]
u can use compare.py ...put the 2 images you want to compare in a single folder and specify the 'image_files' parser argument to the path of the folder with the 2 images with an extra *jpg at the end of your path specification

**Comment by Zumbalamambo** [comment]
is it possible to do training realtime?

**Comment by sy0209** [comment]
@Dicksonchin93 
Hi, can I know how to specify 'image_files' with an extra *jpg?
Below is my result of comparing two image. Is it correct?
How to see whether the two images is the same person from distance matrix?
Thank you.

Images:
0: 263865_472419922778084_1158800669_n.png, 0 images
1: 793929_538122802874462_1938346222_o.png, 0 images
Distance matrix:
        0         1
0  1    0.6975    0.0000
