### ISSUE TITLE
 unable to select only eye parameters of complete face embedding

### ISSUE THREAD

**Issue by vijaysagi** [davidsandberg/facenet#436]
Hi All,

I uploaded test image and generated face embeddings i.e 128 face parameters.  Later on i changed the only the eye part of the face image the generated 128 face embeddings and noticed that face embeddings were completely different. Pls suggest how can i select only eye embeddings

![matrixsalman2_3](https://user-images.githubusercontent.com/6347404/29625364-52b72d40-87e0-11e7-92de-b291bbfd3d9c.JPG)
![matrixsalman2](https://user-images.githubusercontent.com/6347404/29625365-52c19096-87e0-11e7-9329-40c673fe3e45.JPG)

**Comment by davidsandberg** [comment]
Not sure what you mean by only eye embeddings. The embeddings are trained to give a large distance between faces of different identities. There's noting that makes the different dimensions in the embeddings to be orthogonal.
