### ISSUE TITLE
src/classifier.py prints the filename

### ISSUE THREAD

**Issue by e212156822000** [davidsandberg/facenet#439]
I would like to see which file was classified as which classes, so I like made a little change in ```src/classifier.py``` to print the filename.

## Before
![image](https://user-images.githubusercontent.com/11701668/29654897-aa7db326-88e1-11e7-8e95-1bd8c78c64e2.png)

## After
![image](https://user-images.githubusercontent.com/11701668/29655115-6c64d5c8-88e2-11e7-887c-a0127b84e161.png)

## How to do it ? 
Replace
```python
for i in range(len(best_class_indices)):
      print('%4d %s: %.3f' % (i, class_names[best_class_indices[i]], best_class_probabilities[i]))
 ```
with
```python
for i in range(len(best_class_indices)):
      print('%4d %s %s: %.3f' % (i, paths[i] , class_names[best_class_indices[i]], best_class_probabilities[i]))
 ```

**Comment by louiseruiwenli** [comment]
What is your dataset file looks like? Why I got the number of classes is 0 and the image is 0 too.

**Comment by e212156822000** [comment]
I set my dataset in ~/datasets/my_dataset/
```
|_____datasets
   |_____my_dataset
     |_____train
         |_____Jolin
            |_____Jolin(1).png
            |_____Jolin(2).png
            |_____Jolin(3).png
            .......
         |_____Tsai
            |_____Tsai(1).png
            |_____Tsai(2).png
            |_____Tsai(3).png
            .......
     |_____test
         |_____Jolin
            |_____Jolin(1).png
            |_____Jolin(2).png
            |_____Jolin(3).png
            .......
         |_____Tsai
            |_____Tsai(1).png
            |_____Tsai(2).png
            |_____Tsai(3).png
```

If you want to classify two classes (ex. Jolin and Tsai ) , you should put directory test as your parameter.

`
python src/classifier.py CLASSIFY ~/datasets/my_dataset/test/ ~/models/facenet/20170512-110547/20170512-110547.pb ~/models/facenet/lfw_classifier.pkl --batch_size 45 
`

**Comment by Shahnawazgrewal** [comment]
How did you `TRAIN` using `classifier`.py? @e212156822000

**Comment by e212156822000** [comment]
@Shahnawazgrewal 
by this command below : 
`python src/classifier.py TRAIN ~/datasets/my_dataset/train/ ~/models/20170512-110547/20170512-110547.pb ~/models/lfw_classifier.pkl --batch_size 45 `
