### ISSUE TITLE
Question about cross validation

### ISSUE THREAD

**Issue by JiaxiangChen** [davidsandberg/facenet#447]
I try to validate on my own data-sets. But when I look at the code I'm confused.
In the facenet.calculate_roc, I see 
`k_fold = KFold(n_splits=nrof_folds, shuffle=False)`
But KFold is used to split the dataset when using cross validation.I'm confused that I just want to validate my pre-trained model so I shouldn't split my dataset.
Can someone help me understand this? Thanks advance.

**Comment by davidsandberg** [comment]
The distance threshold is selected using cross validation.

**Comment by rustequal** [comment]
> The distance threshold is selected using cross validation.

I'm sorry, but I have the exact same question. Can you tell me why we should use K-Fold to split the test dataset? The best distance threshold we can calculate without splitting the test dataset. We still do not perform the training operation in this calculations.
