### ISSUE TITLE
Hi, a beginner of palmprint recoginition's question about this amzing code.

### ISSUE THREAD

**Issue by xvdehao** [davidsandberg/facenet#448]
Hi, I have read this program, and I  want to know if I can replace the part of extarcting faces' attributes with my own codes which is including how to extrat palmprints' attributes.
Maybe someone can help me or give me some tips to replace the part of program.
Farily look forward your reply.
Thx.

**Comment by fgervais** [comment]
Sure but if you have that code which extracts palmprints attributes you don't really need much from here.

All you could use is 'src/classifier.py' to match palmprints embedding with the label. For that script, if you use "input" and "embeddings" for your network input and output tensor name, I think you can use the code as is.

**Comment by xvdehao** [comment]
@fgervais @davidsandberg  These advices are so helpful to me. And after reading the program,facenet/tmp/export_embeddings.py and facenet/src/compare.py, I figure out  how to export the embeddings. Now I have a new confusion, both of these two programs have the code "facenet.load_model(args.model)" , then if I want to export embeddings from palmprints, should I use a new model about palmprint recognition or use the same model is alright for me?
Thanks again for all of your any tips

**Comment by fgervais** [comment]
You need a new one that recognises palmprints.
