### ISSUE TITLE
What is the meaning of this parameter lfw_dir ？ 

### ISSUE THREAD

**Issue by edongyu** [davidsandberg/facenet#45]
Hi, David

When run facenet_train.py , I met a problem :

I get the following error:

```
Runnning forward pass on LFW images
Traceback (most recent call last):
  File "facenet_train.py", line 340, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "facenet_train.py", line 126, in main
    images_placeholder, phase_train_placeholder, embeddings, nrof_folds=args.lfw_nrof_folds)
  File "/home/dy/tensorflow/facenet-master/facenet/src/lfw.py", line 26, in validate
    emb_array = np.vstack(emb_list)  # Stack the embeddings to a nrof_examples_per_epoch x 128 matrix
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/shape_base.py", line 230, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate
```

What is the meaning of this parameter lfw_dir ？ 
I noticed that ：--lfw_dir means "Path to the data directory containing aligned face patches."  
But i do not understand it , and the default value '~/datasets/lfw/lfw_realigned/' is not exist , run the method  lfw.get_paths() can't get “paths”  lead to validate error

Waiting for your answer.

**Comment by davidsandberg** [comment]
Hi!
This parameter is used to get evaluation on LFW after each epoch. The plan was to make it possible to run without that evaluation by not setting lfw_dir (i.e. an empty string). But i realize that I haven't pushed that to the master branch yet. You could make the change your self by 
* adding 
```
if args.lfw_dir:
```
before 
```
paths, actual_issame = lfw.get_paths(os.path.expanduser(args.lfw_dir), pairs, args.lfw_file_ext)
```
on line 50 in facenet_train.py
* and making sure that lfw_dir is an empty string, e.g. by changing 
```
    parser.add_argument('--lfw_dir', type=str,
        help='Path to the data directory containing aligned face patches.', default='~/datasets/lfw/lfw_realigned/')
```
to 
```
    parser.add_argument('--lfw_dir', type=str,
        help='Path to the data directory containing aligned face patches.', default='')
```
on line 331 in the same module.

**Comment by edongyu** [comment]
Thank you for your help !
Now , it run sucessfully !

**Comment by edongyu** [comment]
Close the issue
