### ISSUE TITLE
Classify new image 

### ISSUE THREAD

**Issue by Shahnawazgrewal** [davidsandberg/facenet#463]
I want to classify a single image using pretrained model `20170512-110547`.  How I can do that using `classifier.py`. 

--------------------------------------------------------------------------
What I did so far
I `TRAIN` a model with the following comman 
python src/classifier.py TRAIN  ~/datasets/lfw/lfw_mtcnnpy_160  ~/datasets/lfw/20170512-110547 ~/datasets/lfw/20170512-110547/model-orig.svm 
and then `CLASSIFY` with the following command line
python src/classifier.py CLASSIFY  ~/datasets/lfw/lfw_mtcnnpy_160  ~/datasets/lfw/20170512-110547 ~/datasets/lfw/20170512-110547/model-orig.svm 

**Issue**
For a single image taken `lfw_mtcnnpy_160`, I obtained 0.000 accuracy.

**Comment by arunk2** [comment]
If you have a trained the SVM classifier of images on your dataset, then you can use the **predict.py** in /tmp directory to predict for a single image. 

     python tmp/predict.py <<<YOUR_IMAGE>>> <<<FACENET_TRAINED_MODEL>>> <<<YOUR_CLASSIFIER>>>

For example:

     python tmp/predict.py test/img1.jpg models/facenet/20170512-110547/20170512-110547.pb models/my_classifier.pkl

should give you list of faces detected with prediction scores.

Note: For generating your own SVM classifier you may want to follow steps in wiki page (https://github.com/davidsandberg/facenet/wiki/Train-a-classifier-on-own-images)

**Comment by Shahnawazgrewal** [comment]
Thanks

**Comment by HaojieYuan** [comment]
Just a warm notification, the `predict.py` has been moved to `contributed` directory.

The command now should be:
```
python tmp/predict.py test/img1.jpg models/facenet/20170512-110547/20170512-110547.pb models/my_classifier.pkl
```

**Comment by ucasiggcas** [comment]
@HaojieYuan 
hi,dear,
could you please supply the .pkl or tell me where it is ?
`python tmp/predict.py test/img1.jpg models/facenet/20170512-110547/20170512-110547.pb models/my_classifier.pkl`

thanks a lot
