### ISSUE TITLE
Training is taking a lot of time

### ISSUE THREAD

**Issue by Zumbalamambo** [davidsandberg/facenet#465]
Im trying to train with a lot of images.

Training takes a lot of time.

Following s my output,

```
INFO:__main__:Processing iteration 15000 batch of size: 50

INFO:__main__:Created 2234450 embeddings
INFO:__main__:Training Classifier
```

Is it really training? because Im seeing this for the past 6 hours

**Comment by davidsandberg** [comment]
This script is typically used if you want to use a pretrained model to classify images in a small private dataset. If you would like to train a model from scratch you should look at [this](https://github.com/davidsandberg/facenet/wiki/Classifier-training-of-inception-resnet-v1) wiki page.
