### ISSUE TITLE
train facenet with grayscale image

### ISSUE THREAD

**Issue by trungtinnguyen** [davidsandberg/facenet#467]
How can I use grayscale image to training, i modify code but it not work, anyone can show me how to do, thanks in advance.

**Comment by hyang428** [comment]
for the model part, I don't think there is any difference for using either RGB or grayscale image only if the [Height, Width] is the same.
You didn't mention what kind of problem,  but I suggest double check the input pipeline, especially convert_to_grayscale and set_shape part.
