### ISSUE TITLE
problem in alignment

### ISSUE THREAD

**Issue by liangxiaoxi** [davidsandberg/facenet#47]
When I run alignment,I encounter some problems as follow:

` warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
  File "align_dataset.py", line 113, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "align_dataset.py", line 42, in main
    img = misc.imread(image_path)
AttributeError: 'module' object has no attribute 'imread'`

So what's reason of the problem?

**Comment by davidsandberg** [comment]
[Scipy](http://www.scipy.org/install.html) is used to read images and my guess is that this library is not installed on your system.

**Comment by liangxiaoxi** [comment]
I have installed scipy and other necessary dependent packages.

**Comment by shawjan** [comment]
I install pillow package and finally it works.
