### ISSUE TITLE
OutOfRangeError (see above for traceback): FIFOQueue '_2_batch_join/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)

### ISSUE THREAD

**Issue by rainy1798** [davidsandberg/facenet#472]
**Notice：i need run grayscale picture**

**first：** i test my picture can be read and show
![image](https://user-images.githubusercontent.com/22868335/30955783-71060cbe-a467-11e7-8626-f4229e893e7a.png)

Secondly：i changed 'channels=3' to 'channels=1' .（All the places that involve channels=3）
meanwhile：i set ‘batch_size’ to 1,and set 'max_nrof_epochs' to 10 .（The settings are small enough to avoid too few pictures）

but：i met this mistake 'OutOfRangeError (see above for traceback): FIFOQueue '_2_batch_join/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)'

and that mean: i can‘t read my .png file. 

What other places do I need to change besides ’channels‘, 'batch_size' and 'epoch_size' ?

**Comment by zzw1123** [comment]
Have you solved it?
