### ISSUE TITLE
on whatever image with a face ...

### ISSUE THREAD

**Issue by zendelcrow** [davidsandberg/facenet#478]
on whatever image with a face I get 

(tensorflow) carlos@carlos-ubuntu:~/tensorflow/facenet$ python src/compare.py 20170512-110547/ ./lfw/lfw_mtcnnpy_160/Antonio_Banderas/Antonio_Banderas_0001.png Creating networks and loading parameters
Model directory: 20170512-110547/
Metagraph file: model-20170512-110547.meta
Checkpoint file: model-20170512-110547.ckpt-250000
WARNING:tensorflow:The saved meta_graph is possibly from an older release:
'model_variables' collection should be of type 'byte_list', but instead is of type 'node_list'.
Images:
0: ./lfw/lfw_mtcnnpy_160/Antonio_Banderas/Antonio_Banderas_0001.png

Distance matrix
        0     
0    0.0000 

Someone with the same problem?

**Comment by davidsandberg** [comment]
You need to call compare with two or more images to get any interesting results.
