### ISSUE TITLE
Poor results when running predict.py

### ISSUE THREAD

**Issue by popkristina** [davidsandberg/facenet#479]
Hello,

I was following the intructions on the wiki for 'Train a classifier on your own images'. For that I got a small part of the lfw dataset, smth like 5%, plus added images from 10 other people. I run this command:

python src\classifier.py TRAIN datasets\retrain_160 models\20170512-110547\20170512-110547.pb models\classifier_new.pkl 

I get output

![screenshot_1](https://user-images.githubusercontent.com/31166985/31335745-2ef9f69c-acf4-11e7-91aa-35151c4ca81f.jpg)

And then with the saved new classifier I want to use the function predict.py to recognize a face that exist in the dataset but with a different image.

 I run: python tmp\predict.py datasets\test\image1.jpg models\20170512-110547\20170512-110547.pb 
models\classifier_new.pkl

So this is working but the results that I get are poor, for an image I give it sometimes outputs the correct names but with like 0.020 accuracy, and sometimes it outputs a wrong person.

Did anyone encounter an issue like this and maybe have an advice how to fix this or idea how it can be improved?

Thanks in advance

**Comment by himabinduyeddala** [comment]
Hi popkristina,
I got
![1_op](https://user-images.githubusercontent.com/30427692/31478879-00e00c58-af31-11e7-9a29-cb93302b565c.png)
 the same issue, Have you found any solution for that issue. If you have any ideas please share with me.
Did anybody got the solution for prediction accuracy. Please suggest me any ideas to improve accuracy .

**Comment by popkristina** [comment]
No I still didn't. If I do I will post it here if someone doesn't share meanwhile.
Also did you by any chance manage to modify the function to be called from PyCharm instead of the console?

**Comment by domarps** [comment]
@popkristina : Have you inspected your train/test split up of dataset? I believe your model is underfitting. Is there a class imbalance problem?

**Comment by moonyoung430** [comment]
@himabinduyeddala  I found that in classifier.py , param "min_nrof_images_per_class" means "Only include classes with at least this number of images in the dataset",so when we predict picture,choose the label in model.
