### ISSUE TITLE
Train on the Ms-Celeb-V1 dataset

### ISSUE THREAD

**Issue by davidsandberg** [davidsandberg/facenet#48]
The dataset is available [here](https://www.microsoft.com/en-us/research/project/ms-celeb-1m-challenge-recognizing-one-million-celebrities-real-world/).
A python program to decode the face thumbnails can be found [here](https://github.com/davidsandberg/facenet/blob/master/src/decode_msceleb_dataset.py).

**Comment by hudvin** [comment]
There is another one dataset https://www.microsoft.com/en-us/research/project/ms-celeb-1m-challenge-recognizing-one-million-celebrities-real-world/ but it's very dirty. I trained separate model to remove garbage. Still, it's around 10 million images and I have no resources to process all of them.

**Comment by davidsandberg** [comment]
Hi @hudvin!
How did you plan to remove the garbage?
I did some tests with the casia dataset where I selected a subset of the casia images based on the distance for each image to the class center (the implementation can be found on the branch `dataset_filtering`). It was just intended as an experiment to try to validate the method, but it actually improved the accuracy (when trained on casia only) from 0.984 to 0.988 which was a bit surprising. The plan is to apply the same principle on the MsCeleb dataset which contains a lot more label noise and see what happens.

**Comment by hudvin** [comment]
I suppose there must be at least two stages:
1. Remove  real garbage like photos without faces, postage stamps, drawings, bw and so on. I used basic caffe classifier for this. Works more or less ok, but quite slow. On my hardware it would take weeks to process whole dataset.
2.Some folders contain images of completely different persons. I suppose it's possible to calculate similarity  between them or make some kind of clusterization. But again this would take a lot of time.

**Comment by davidsandberg** [comment]
Here are some results from the training:
![20160127_msceleb_accuracy](https://cloud.githubusercontent.com/assets/15169058/22378544/479a2a66-e4b6-11e6-8d93-d6aca4bd555f.png)
I still need to test some more agressive dataset filtering settings but so far the best LFW accuracy is around 0.994.

**Comment by ugtony** [comment]
In the [decode program](https://github.com/davidsandberg/facenet/blob/master/src/decode_msceleb_dataset.py), 
the assignment of img_name and img_string looks weird, 
```python
# Column1: Freebase MID
# Column2: Query/Name
# Column3: ImageSearchRank
# Column4: ImageURL
# Column5: PageURL
# Column6: ImageData_Base64Encoded
.
.
.
img_name = fields[1] + '-' + fields[4] + '.' + args.output_format
img_string = fields[6]
```
I think a corrected version should be
```python
img_name = fields[1] + '-' + fields[2] + '.' + args.output_format
img_string = fields[5]
```
