### ISSUE TITLE
I have a problem with using align_dataset_mtcnn.py

### ISSUE THREAD

**Issue by Leedonggeon** [davidsandberg/facenet#480]
hi. I'm university student who major in computer science. 
First of all, thanks for your these great contribution. 
I worked in Window environment.
So its method is different from method using linux terminal.
will i do my work in Linux environment?
If not, how can i do the work in Window environment.

sys.argv[1:] is error's cause...
below error is found

Traceback (most recent call last) :
File "src/align_dataset_mtcnn.py", lune 144, in 
main(parse_arguments(sys.argv[1:]))
File "src/align_dataset_mtcnn.py", line 144, in 
facenet.store_revision_info(src_path, output_dir, ' '.join(sys.argv))
File "C:\Users\Lee\Desktop\facenet-master\src\facenet.py", line 508, in store_revision_info
gitproc = Popen(['git', 'rev-parse', 'HEAD'], stdout = PIPE, cwd= src_path)
File "C:\Users\Lee\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 676, in init
restore_signals, start_new_session)
File "C:\Users\Lee\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 955, in _execute_child
startupinfo)
FileNotFoundError: [WinError 2] the system cannot find the file specified

i wanna help.

**Comment by Leedonggeon** [comment]
Oh my god!!!!! It works!!!!!Thanks verrrrrrry much.Yea i use window.Thanks you very much.
Have a nice night!!!!


내 삼성 디바이스에서 보냈습니다

-------- 원본 메시지 --------
발신: 笑话 <notifications@github.com> 
날짜: 2017/10/10  23:59  (GMT+09:00) 
받은 사람: davidsandberg/facenet <facenet@noreply.github.com> 
참조: Leedonggeon <gd6745@naver.com>, Author <author@noreply.github.com> 
제목: Re: [davidsandberg/facenet] I have a problem with using
  align_dataset_mtcnn.py (#480) 

Do you use windows?

You can do this by modifying the “facenet.py” file:
At the end of the Popen () function, add "shell = True"
gitproc = Popen (['git', 'rev-parse', 'HEAD'], stdout = PIPE, cwd = src_path, shell = True)

gitproc = Popen (['git', 'diff', 'HEAD'], stdout = PIPE, cwd = src_path, shell = True)
Hope to help you

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/davidsandberg/facenet","title":"davidsandberg/facenet","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/davidsandberg/facenet"}},"updates":{"snippets":[{"icon":"PERSON","message":"@i161079 in #480: Do you use windows?\r\nYou can do this by modifying the “facenet.py” file:\r\n\r\nAt the end of the Popen () function, add \"shell = True\"\r\n\r\ngitproc = Popen (['git', 'rev-parse', 'HEAD'], stdout = PIPE, cwd = src_path, shell = True)\r\ngitproc = Popen (['git', 'diff', 'HEAD'], stdout = PIPE, cwd = src_path, shell = True)\r\n\r\nHope to help you\r\n"}],"action":{"name":"View Issue","url":"https://github.com/davidsandberg/facenet/issues/480#issuecomment-335501274"}}}

**Comment by yatharthahuja** [comment]
what can be done if this problem is faced in linux? @lipstick-49
