### ISSUE TITLE
Predict function works only from command line

### ISSUE THREAD

**Issue by popkristina** [davidsandberg/facenet#483]
Hello,

Was anyone able to modify the function predict.py to work with given arguments as called from another python script?
First I tried changing it instead of accepting command line arguments to accept the arguments when called, but I got these errors:

![screenshot_1](https://user-images.githubusercontent.com/31166985/31494667-a8991c14-af54-11e7-8fc1-57eed664b186.jpg)

Also I just tried to remove all arguments and just initialize those arguments up in the main function, but I get the same error output.
Anyone that tried to do something similar and succeeded?

**Comment by moonyoung430** [comment]
image_file  is  a list of  pictures path , you can try it
