### ISSUE TITLE
Align the LFW dataset under Windows

### ISSUE THREAD

**Issue by peter73421** [davidsandberg/facenet#486]
Dears,

now I'm trying go thru Validation as described on wiki [https://github.com/davidsandberg/facenet/wiki/Validate-on-LFW](url) on my Windows machine.

I'm getting this - can you help me wioth this?

Thank you.

`(C:\Anaconda3) C:\FaceNet\facenet>python src/align/alig
n_dataset_mtcnn.py "c:\\FaceNet\\datasets\\lfw\\raw"
 "c:\\FaceNet\\datasets\\lfw\\lfw_mtcnnpy_160" --ima
ge_size 160 --margin 32 --random_order --gpu_memory_fraction 0.25
Traceback (most recent call last):
  File "src/align/align_dataset_mtcnn.py", line 143, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/align/align_dataset_mtcnn.py", line 47, in main
    dataset = facenet.get_dataset(args.input_dir)
  File "C:\FaceNet\facenet\src\facenet.py", line 329, i
n get_dataset
    classes = os.listdir(path_exp)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'c'`

**Comment by dawningo** [comment]
I've had exactly the same problem! And it's due to facenet.py's line 327, where the paths is split by ':'. This works fine on linux, but when it comes to windows it cuts the path. You could just add a line that jumps through 'c' and you'll be fine!

**Comment by vedp1988** [comment]
Hello dawningo, we are also facing the same problem. Can you suggest what line we have to add at line 327 (in facenet.py).
"You could just add a line that jumps through 'c' and you'll be fine! "   ????
