### ISSUE TITLE
ValueError: need at least one array to stack when embedding images

### ISSUE THREAD

**Issue by henrych4** [davidsandberg/facenet#487]
I try to use export_embeddings.py inside facenet/tmp/ for embedding own images. The images I used are of size 64x64 and in .png format. When I run the codes, ValueError raises and it seems that no image is loaded. Is there any requirement on image size? Thanks.

**Comment by davidsandberg** [comment]
I think 64x64 is maybe to small for inception-resnet-v1. Whar error message do you get?

**Comment by henrych4** [comment]
ValueError: need at least one array to stack when embedding images

**Comment by luis0893** [comment]
I have the same problem help please
