### ISSUE TITLE
Question: what algorithm to use for clustering with embedding vectors?

### ISSUE THREAD

**Issue by bobzsj87** [davidsandberg/facenet#488]
Just wondering how do I do clustering after I get a bunch of embeddings from a number of pictures?

**Comment by MaartenBloemen** [comment]
I have done it with DBSCAN but based on the ecleudian distance you can calculate with the embedding vectors. You can find my code at #441 if you are interested.

**Comment by zhly0** [comment]
this is a different cluster algorithm:
https://github.com/zhly0/facenet-face-cluster-chinese-whispers-,which you do not need to specify the number of cluster number,all you need to do is specify the threshold.
https://github.com/davidsandberg/facenet/issues/370

**Comment by MaartenBloemen** [comment]
@zhly0 
The DBSCAN algorithm doesn't require you to specify the clusters, you just feed it the distance matrix and it will cluster based on the chosen threshold as well.

**Comment by Shahnawazgrewal** [comment]
I have also cluster using the DBSCAN as it doesn't require to specify the clusters.

**Comment by RaviRaaja** [comment]
@Shahnawazgrewal @MaartenBloemen  I have tried clustering with out using mtcnn (align function) , precomuputed and cropped all images in a directory of shape(4000,160,160,3), all 4000 instances belongs to different classes (images with various different brightness, saturation etc.. ) 
in cluster.py, i have substituted at main() as 
'In main function  
`     with tf.Graph().as_default():`
      `   with tf.Session() as sess:`
          `  facenet.load_model(args.model)`
          `  #image_list = load_images_from_folder(args.data_dir)`
          `  #images = align_data(image_list, args.image_size, args.margin, pnet, rnet, onet)`
          `  images = load_images_from_folder(args.data_dir)`
 Then performed clustering only Repeated images falls into same cluster. threshold tested with 1.0 to 0.5 still all resulted same!

**Comment by Shahnawazgrewal** [comment]
which pretrain model are you using? @RaviRaaja

**Comment by RaviRaaja** [comment]
@Shahnawazgrewal 20170512-110547

**Comment by Shahnawazgrewal** [comment]
can you upload the subset of images (say 100) on dropbox to test? @RaviRaaja

**Comment by RaviRaaja** [comment]
@Shahnawazgrewal https://www.dropbox.com/sh/eitw9wuh7lkjgz6/AAC863xj1LSUeCrDGob2N0x_a?dl=0

**Comment by Shahnawazgrewal** [comment]
Some of the clusters with eps = 0.50
![screenshot_2018-03-24_15-07-46](https://user-images.githubusercontent.com/6230351/37864895-2634743e-2f75-11e8-8b06-8ec27170bfce.png)
![screenshot_2018-03-24_15-08-37](https://user-images.githubusercontent.com/6230351/37864897-28a0416c-2f75-11e8-8602-f6892883eef8.png)
![screenshot_2018-03-24_15-08-55](https://user-images.githubusercontent.com/6230351/37864898-2b2c8c2e-2f75-11e8-9314-f4f0d88c1d11.png)
![screenshot_2018-03-24_15-09-23](https://user-images.githubusercontent.com/6230351/37864899-2df22946-2f75-11e8-93dc-84e0f6b3dcc7.png)
![screenshot_2018-03-24_15-09-31](https://user-images.githubusercontent.com/6230351/37864900-300b8e98-2f75-11e8-936e-bb3d5b19ca5e.png)

**Comment by RaviRaaja** [comment]
@Shahnawazgrewal will try with hdscan , can you add some more note about dbscan experiment for above results , Chinese whisper clustering normalisation is not done , and in dbscan normalization is done , does prewhiten(module name) do have impact on clustering??

**Comment by Shahnawazgrewal** [comment]
I have not experiment with prewhiten module. @RaviRaaja 
Apparently, results are okay.
