### ISSUE TITLE
ValueError: Cannot have number of splits n_splits=10 greater than the number of samples: 0.

### ISSUE THREAD

**Issue by lidgik** [davidsandberg/facenet#490]
I got some trouble when I execute the command below:

python src/validate_on_lfw.py ~/datasets/lfw/lfw_mtcnnpy_160 ~/models/facenet/20170512-110547

I have execute the align_dataset_mtcnn.py successfully.

The Error information as the following:

Runnning forward pass on LFW images
Traceback (most recent call last):
  File "src/validate_on_lfw.py", line 113, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/validate_on_lfw.py", line 83, in main
    actual_issame, nrof_folds=args.lfw_nrof_folds)
  File "/Users/andycooper/facenet/src/lfw.py", line 40, in evaluate
    np.asarray(actual_issame), nrof_folds=nrof_folds)
  File "/Users/andycooper/facenet/src/facenet.py", line 426, in calculate_roc
    for fold_idx, (train_set, test_set) in enumerate(k_fold.split(indices)):
  File "/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py", line 330, in split
    n_samples))
ValueError: Cannot have number of splits n_splits=10 greater than the number of samples: 0.

Anyone else has the same problem as me? Please help.

**Comment by mingrui** [comment]
I have the same problem, even after re-running the alignment script.

**Comment by mingrui** [comment]
turns out `align_dataset_mtcnn.py` is adding a `_0` to the end of all the files, so all my files is name like this:
`datasets/lfw/lfw_mtcnnpy_160/Slobodan_Milosevic/Slobodan_Milosevic_0002_0.png`
which should have been this:
`datasets/lfw/lfw_mtcnnpy_160/Slobodan_Milosevic/Slobodan_Milosevic_0002.png`

if you don't want to fixed the naming in `align_dataset_mtcnn.py`, a quick and dirty fix is change `lfw.py`:
```
        if len(pair) == 3:
            path0 = os.path.join(lfw_dir, pair[0], pair[0] + '_' + '%04d' % int(pair[1])+'_0.'+file_ext)
            path1 = os.path.join(lfw_dir, pair[0], pair[0] + '_' + '%04d' % int(pair[2])+'_0.'+file_ext)
            issame = True
        elif len(pair) == 4:
            path0 = os.path.join(lfw_dir, pair[0], pair[0] + '_' + '%04d' % int(pair[1])+'_0.'+file_ext)
            path1 = os.path.join(lfw_dir, pair[2], pair[2] + '_' + '%04d' % int(pair[3])+'_0.'+file_ext)
```

**Comment by lidgik** [comment]
Thank you! It really works. The problem has solved as you said.

**Comment by ttjslbz** [comment]
HI @lidgik 
i met the same problems, can you past your edition

Thanks
Carl Chen

**Comment by AppleCoffee** [comment]
@mingrui Hi, I  have the same problem, even after modifing the script(lfw.py) as suggested here.



thanks

**Comment by xmuszq** [comment]
@mingrui 
I changed the codes and run the codes, the previous error is gone but an new error occurs:

ZeroDivisionError: float division by zero

Any help????Many thanks..

**Comment by patrickhwood** [comment]
This patch fixes the file naming in align_dataset_mtcnn.py:

diff --git a/src/align/align_dataset_mtcnn.py b/src/align/align_dataset_mtcnn.py
index a7aaf80..6665dd0 100644
--- a/src/align/align_dataset_mtcnn.py
+++ b/src/align/align_dataset_mtcnn.py
@@ -123,7 +123,7 @@ def main(args):
                                 cropped = img[bb[1]:bb[3],bb[0]:bb[2],:]
                                 scaled = misc.imresize(cropped, (args.image_size, args.image_size), interp='bilinear')
                                 nrof_successfully_aligned += 1
-                                output_filename_n = "{}_{}.{}".format(output_filename.split('.')[0], i, output_filename.split('.')[-1])
+                                output_filename_n = "{}.{}".format(output_filename.split('.')[0], output_filename.split('.')[-1])
                                 misc.imsave(output_filename_n, scaled)
                                 text_file.write('%s %d %d %d %d\n' % (output_filename_n, bb[0], bb[1], bb[2], bb[3]))
                         else:

**Comment by davidsandberg** [comment]
This has been fixed in 4c33d4d64d6908ccf5cfb6616b6dd49776c6d266.

**Comment by chaotaklon** [comment]
According to:
https://q-a-assistant.info/computer-internet-technology/valueerror-cannot-have-number-of-splits-n-splits-10-greater-than-the-number-of-samples-0/1299682

It could be because of png/jpg. If validate_on_lfw.py expect png and your dataset is jpg, it will fail to load image and cause the error.
Adding parameter "--lfw_file_ext jpg" can solve the issue.

**Comment by gadginir** [comment]
Hi,
Even after taking latest code, I am getting the same issue.

`ValueError: Cannot have number of splits n_splits=10 greater than the number of samples: 0.`

I checked the file name and extension. Both are correct. It doesn't contain _0 and it has extension of .png after cropping.

**Comment by chaotaklon** [comment]
No metter _0 or jpg/png, if the program fail to read the dataset, the image list length will be zero and cause this error. Print the dataset variable line by line and check when it becomes an empty list or None.

**Comment by tensorflowt** [comment]
Please check if your database path is entered correctly, for example:

~ / datasets/LFW lfw_mtcnnpy_160 correctly

~ / dataset/LFW lfw_mtcnnpy_160 errors
@chaotaklon

**Comment by yashbhalgat** [comment]
I was getting this error because the number of `hard_triplets` became 0 after a few (40~50) epochs. Hence, in the `validate_on_lfw.py`, the number of samples is 0. It just means that your model is getting better.

I am just getting away with this by adding a try-catch condition.
