### ISSUE TITLE
TypeError: slice indices must be integers or None or have an index method

### ISSUE THREAD

**Issue by ronyuzhang** [davidsandberg/facenet#497]
when i run download_vgg_face_dataset.py to download vggface datasets , but have a error

as fallows:
python download_vgg_face_dataset.py ../../../data/vgg_face_dataset/files/ --output_format jpg 
http://snarkerati.com/profile_pics/Leslie-Bibb.jpg: <urlopen error [Errno -3] Temporary failure in name resolution>
Traceback (most recent call last):
  File "download_vgg_face_dataset.py", line 104, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "download_vgg_face_dataset.py", line 74, in main
    img_cropped = img[box[1]:box[3],box[0]:box[2],:]
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by RakshakTalwar** [comment]
Try typecasting the indices to integers

```
box = map(int, box)
img_cropped = img[box[1]:box[3],box[0]:box[2],:]
```
