### ISSUE TITLE
How do you setup the project?

### ISSUE THREAD

**Issue by mia-petkovic** [davidsandberg/facenet#499]
I am missing the setup.py file, was the installation procedure changed?

**Comment by MaartenBloemen** [comment]
You can follow step 1 till 3 [here](https://github.com/davidsandberg/facenet/wiki/Classifier-training-of-inception-resnet-v1), those steps and installing all dependencies in [requirements.txt](https://github.com/davidsandberg/facenet/blob/master/requirements.txt) is all you need to do to setup the project.

**Comment by mia-petkovic** [comment]
I completely missed the Wiki tab. Thanks.
