### ISSUE TITLE
how much time does it take you to train a model with 0.919 accuracy on LFW?

### ISSUE THREAD

**Issue by ZHAIXINGZHAIYUE** [davidsandberg/facenet#50]

**Comment by davidsandberg** [comment]
It depends on a few factors, e.g. how fast your disk is, how fast the triplet selection can run on the CPU and how fast the training on the GPU is. For me it takes roughly 72 hours to train for 500 000 steps with triplet loss and the nn4 model.

**Comment by ZHAIXINGZHAIYUE** [comment]
@davidsandberg thank you very much.
