### ISSUE TITLE
Unbearable Execution Time for a Real Time Recognition

### ISSUE THREAD

**Issue by lidgik** [davidsandberg/facenet#504]
I executed the real_time_face_recognition.py on my laptop.After about 100 seconds, the camera window showed.That's an unbearable long time for real time face recognition. How can I speed up the running process? Is there anybody have the solution? Any help would be appreciated.

**Comment by gengstah** [comment]
At first run, it will create the MTCNN & load the model and classifier. That process takes a while but after that, there should be no problem in performance.

**Comment by thuoctran** [comment]
Hi,
If I want to use  Inception-Resnet-v1 model as a classifier instead of SVM model, what should I do?
