### ISSUE TITLE
face size for embeddings

### ISSUE THREAD

**Issue by mohammaduzair9** [davidsandberg/facenet#506]
Hey,
Can you tell me why you are using 160 as the face size? Also what can be the minimum and maximum size for face that we can calculate embeddings for ?

**Comment by Shahnawazgrewal** [comment]
it depends on the trained model. I have trained a model with image size of `100x100`.
I tried to train a model with image size of `64x64` and it is low to pass through the resnet model.

**Comment by JianbangZ** [comment]
It's the combination of (1) GPU FLOPS (1) GPU memory size (2) target system image size


- 

-

**Comment by hustzeyu** [comment]
@Shahnawazgrewal How did you do the size of 100*100? I have specified --image size 100 as:
python src/classifier.py TRAIN /home/hzy/datasets/all_face/Ball_100/ /home/hzy/model/20170512-110547.pb /home/hzy/model/wasian_classifier.pkl --batch_size 1000 --image_size 100
But I have got an error: InvalidArgumentError (see above for traceback): computed output size would be negative

**Comment by Shahnawazgrewal** [comment]
@hustzeyu  you need to train a model with image size `100x100`. Then you would be able to run classifier.
