### ISSUE TITLE
The step of face embedding

### ISSUE THREAD

**Issue by dyshuang** [davidsandberg/facenet#507]
Sorry to bother you. As I am just start studying python and Facenet, I have some elementary questions for the code implement. I will be very appreciate if you can help me.
The first question:
I am working on the face clustering. Is the step face detection---face embedding --face clustering/face recognition? Should I choose the script---detect_face.py for the first step? And then implementing the export_embeddings.py and finally the cluster.py/clustering.py?
And the second:
I just use this format for the implement (for the detect_face.py) but it seems no work...
-----------
cd facenet
python  /path/detect_face.py /path/of/input/folder /path/of/output/folder/
-----------
If you have any advice please reply me QAQ
Thank you very much!

**Comment by RakshakTalwar** [comment]
use the mtcnn align script for the first step.
Your steps in general look fine

**Comment by dyshuang** [comment]
@RakshakTalwar Thank you a lot for your reply!
Do you mean the first step is align_dataset_mtcnn.py? 
I am still a little confused with the format of the implement,  should I use as this format?

cd facenet
python align_dataset_mtcnn.py~/path/of/input/folderA~/path/of/output/folderB/_mtcnnpy_160 --image_size 160 --margin 32 --random_order --gpu_memory_fraction 0.25

And then use the picture in folderB for the input of script export_embeddings.py?

Looking forward to your reply^_^

**Comment by j859920050** [comment]
Hi,I have the same confusion.Have you succeeded in face clustering or face recognition?
Can you reply me about the format?
Thank you very much!

**Comment by RakshakTalwar** [comment]
take a look at steps 1-4 to prepare your training images
https://github.com/davidsandberg/facenet/wiki/Classifier-training-of-inception-resnet-v1

then you can take a look at this
https://github.com/davidsandberg/facenet/wiki/Train-a-classifier-on-own-images

I haven't tried face clustering

hope this helps!
