### ISSUE TITLE
Wiki "Triplet loss training", how to classify my own image after training?

### ISSUE THREAD

**Issue by chaotaklon** [davidsandberg/facenet#509]
Hi,

I followed the "Triplet loss training" wiki and got a saved tensorflow checkpoint. Is there any code demonstrate how to classify my own image using that checkpoint?

Thanks and Regards,
Alan

**Comment by rajaprerak** [comment]
You can look through freeze.py file where you have to specify folder where you have saved your model during training. You can run freeze.py file by typing python src/freeze_graph.py  ~/temp/facenet/models/specify your model folder name here/ ~/temp/facenet/models/anyname.pb 
After completing the above steps and try to modify validate_on_lfw.py file accordingly.
