### ISSUE TITLE
exporting embeddings im getting this error

### ISSUE THREAD

**Issue by RaviRaaja** [davidsandberg/facenet#512]
File "/home/stan/Desktop/Algorithms)_implemented/facenet/src/export_embeddings.py", line 189, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "/home/stan/facenet/src/export_embeddings.py", line 103, in main
    images = facenet.load_data(image_list[i*batch_size:n], False, False, args.image_size)
  File "/home/stan/facenet/src/facenet.py", line 266, in load_data
    images[i,:,:,:] = img
ValueError: could not broadcast input array from shape (119,160,3) into shape (160,160,3)

i initially thought it was a dimension error so i removed all images with height or width less than 160 but still iam getting this error ? could any one suggest me why this error ? and how to fix it ?

**Comment by cjekel** [comment]
Are the images already aligned (i.e. are the images in your dataset just cropped faces)? If not you should run with --is_aligned False which will automatically crop and resize all of the images with faces to the same size.

**Comment by RaviRaaja** [comment]
yup , default alignment parameter changed into False , It worked. Thank you!

**Comment by cjekel** [comment]
If you have a large number of images, I think you should align the dataset because it can be costly to align a dataset. 

The load_and_align_data() function within export_embeddings doesn't write the aligned image to your hard drive.
