### ISSUE TITLE
Hi， a quesition about how to improve the accuracy about the model

### ISSUE THREAD

**Issue by xvdehao** [davidsandberg/facenet#515]
Hello, now I can use my own images to make a SVM model,and then try to use this model to classify some test images, well I think the probability of every test image is not too bad(if I use 10 images per class to train a SVM model, I can get about 0.7 probability)
So are there some ideas to improve the SVM model's result or maybe another algorithm is better than SVM?
Any answer is so helpful to me
Looking forward your reply sincerely
Thx

**Comment by shdyn** [comment]
You should implement multi-gpu, multi-machine yourself. Just a advice, TensorPack is a good way.
