### ISSUE TITLE
how to use this modle to test if a  face-picture be recognized?

### ISSUE THREAD

**Issue by juzhitao** [davidsandberg/facenet#517]
I run The test :
python src/validate_on_lfw.py ~/datasets/lfw/lfw_mtcnnpy_160 ~/models/facenet/20170512-110547

and it is only output accuracy rate like:
Runnning forward pass on LFW images
Accuracy: 0.992+-0.003
Validation rate: 0.97733+-0.01340 @ FAR=0.00100
Area Under Curve (AUC): 1.000
Equal Error Rate (EER): 0.007

**but if I want to test a face picture in this modle, how to do?**

**Comment by davidsandberg** [comment]
Have you seen [this](https://github.com/davidsandberg/facenet/wiki/Train-a-classifier-on-own-images) wiki page. It sounds like that is what you are after.
