### ISSUE TITLE
99% lfw verfication accuracy, but only 2.7% on other dataset

### ISSUE THREAD

**Issue by shdyn** [davidsandberg/facenet#520]
Hi, David, Thanks for your excellent work.
Based on your code, I tried to implement another model, which ahieved 99% verfication accuracy on LFW dataset. But when I tried to extract featurs for other dataset, the performance was just 2.7% (center loss model can achieve 60%, vggface model can achieve 54%). The performance was so low that I thought I must miss somethig. Do you have any ideas about this?

**Comment by davidsandberg** [comment]
You should be able to get ~50% verification performance on LFW by pure chance. If you get 2.7% accuracy then it sounds like you have confused the flag indicating same and different pairs or something like that.

**Comment by shdyn** [comment]
2.7% is on another dataset. Let me state the problem as following:
During training, my model can achieve 98.9% accuracy on LFW. But when I tried to valiated my saved model on LFW by validate_on_lfw.py, the accuracy is just 66.7%.

**Comment by qixianbiao** [comment]
I think you should carefully check your own code, especially the pre-processing. Have you used the same pre-processing skills(face detection, pixel value normalized to [0, 1]). Without code, it is impossible to find your errors extactly.

**Comment by xmuszq** [comment]
2.7% means if you treat the wrong answer as right, you got 97.3% accuracy!?
