### ISSUE TITLE
Directory problem

### ISSUE THREAD

**Issue by alisidaniel** [davidsandberg/facenet#523]
please what will be in this folder at line 28(sess,  './Path to det1.npy').
And how can i training i need steps please.
What directory is this i don't understand /..Path to pre-trained model../20170512-110547/20170512-110547.pb .
jst explain full the concept of the training for me thanks

**Comment by davidsandberg** [comment]
Not sure which script you are running and what you are trying to do, but have you seen the [wiki](https://github.com/davidsandberg/facenet/wiki/Validate-on-LFW)?
