### ISSUE TITLE
Wrong file name format when validate on LFW

### ISSUE THREAD

**Issue by YF-Tung** [davidsandberg/facenet#524]
When I try to run the [validation on LFW](https://github.com/davidsandberg/facenet/wiki/Validate-on-lfw), it shows no files found.
The file name in LFW data set is like `Aaron_Eckhart_0001.jpg`, while after alignment it is like `Aaron_Eckhart_0001_0.jpg`. I guess the trailing number is to denote different faces in one picture.
The script that produces this result is `src/align/align_dataset_mtcnn.py`.
But in `lfw.py`, the filename is assumed as the original format, thus the validation script cannot fetch any file from the aligned directory, and leads to an error.

Possible fixes IMO are trying to enumerate files in folder rather than trying fixed filename, or change the filename format in `lfw.py`. If someone can confirm this issue you have my gratitude, then we can fix this.

**Comment by davidsandberg** [comment]
Hi,
Thanks for spotting this. It has been fixed in 4c33d4d64d6908ccf5cfb6616b6dd49776c6d266. I also added a test case for alignment which has been missing.
