### ISSUE TITLE
In center loss, the way of centers update

### ISSUE THREAD

**Issue by zlchen6** [davidsandberg/facenet#528]
Hi，I don't understand your demo about center loss，your demo  about centers update centers below：
diff = (1 - alfa) * (centers_batch - features)
centers = tf.scatter_sub(centers, label, diff)

but in the paper，centers should update should follow below：
    diff = centers_batch - features
    unique_label, unique_idx, unique_count = tf.unique_with_counts(labels)
    appear_times = tf.gather(unique_count, unique_idx)
    appear_times = tf.reshape(appear_times, [-1, 1])
    diff = diff / tf.cast((1 + appear_times), tf.float32)
    diff = alpha * diff
    # update centers
    centers = tf.scatter_sub(centers, labels, diff)

**Comment by qixianbiao** [comment]
The center is updated not by gradient descent, instead, the code uses a moving averaging method to update the centers....
