### ISSUE TITLE
why there are 3 set of similar files in the trained model, which set I should used when download the trained model

### ISSUE THREAD

**Issue by xmuszq** [davidsandberg/facenet#529]
after trained the model, there are 3 sets of similar file. which one I should used when download the model to continue to train?

![image](https://user-images.githubusercontent.com/15931069/32785826-7233df52-c920-11e7-97cb-db169f296641.png)

**Comment by xmuszq** [comment]
max_to_keep indicates the maximum number of recent checkpoint files to keep. As new files are created, older files are deleted. If None or 0, all checkpoint files are kept. Defaults to 5 (that is, the 5 most recent checkpoint files are kept.)

**Comment by huyazhou-2018** [comment]
can you load pretrain model?
