### ISSUE TITLE
the way of loading data about train_softmax.py

### ISSUE THREAD

**Issue by limicala** [davidsandberg/facenet#534]
As I know, the script load data by reading these image files.
what I need to do is transform these files to a TFRecord file and read it when training.

I have read this [code](https://github.com/yeephycho/tensorflow_input_image_by_tfrecord/blob/master/src/flower_train_cnn.py) 
and know how to transform image files to TFRecord files and read as bacth

But I don't know how to modify the [train_softmax.py](https://github.com/davidsandberg/facenet/blob/master/src/train_softmax.py)

Looking forward your reply sincerely
Thx

**Comment by xxllp** [comment]
@limicala ，你最后找到办法了吗
