### ISSUE TITLE
How limit RAM usage

### ISSUE THREAD

**Issue by ramonamorim** [davidsandberg/facenet#538]
I'm following the topic: Classifier training of inception resnet v1
so when i run the step 5 my RAM isn't enough , is possible limit the memory ram usage? There's any parameter for setup this?

**Comment by RakshakTalwar** [comment]
Are you referring to VRAM (GPU) or RAM? How much do you have?

**Comment by ramonamorim** [comment]
Hi @RakshakTalwar! Thanks for reply. Well i didn't understanding exactly what happened but i saw some process stuck consuming all my VRAM. Maybe i did something wrong killing the process and this consumed all my memory, thanks :)
