### ISSUE TITLE
How to determine what an epoch is

### ISSUE THREAD

**Issue by weedwind** [davidsandberg/facenet#541]
I saw in the code the number of batches in an epoch is preset to a fixed value. I am wondering how to determine this value?

**Comment by RakshakTalwar** [comment]
This is a hyper-parameter you have to play with. There's no deterministic way to set the number of batches.

Here's  something to read: https://www.quora.com/Intuitively-how-does-mini-batch-size-affect-the-performance-of-stochastic-gradient-descent/answer/Alberto-Bietti?srid=uIvy8
