### ISSUE TITLE
How can i use export_embeddings.py?

### ISSUE THREAD

**Issue by PHMark** [davidsandberg/facenet#542]
How can I load a .npy file containing the embeddings and .npy of names of known faces.
After that I will distinguish known faces and unknown faces.
It has embeddings.npy and labels.npy.
and I want to place it in here:
dist = np.sqrt(np.sum(np.square(np.subtract(EXPORT_EMBEDDINGS, face_to_compare.embedding))))

Please help me.

**Comment by cjekel** [comment]
You can use np.load('my.npy') to open a binary numpy file.

See my posts in https://github.com/davidsandberg/facenet/issues/496
