### ISSUE TITLE
A question about how to make a face verification?

### ISSUE THREAD

**Issue by xvdehao** [davidsandberg/facenet#544]
Hello, now I have a new question: if I have an array of  one people's face embeddings, how can I use these embeddings to make face verification? 
I mean if I need do train these embeddings with a model and then give a new embeddings to verify, maybe there is a threshold, if the probability is greater than the threshold they are the same person, or they are two people.
How I choose the model?(Apparently the SVM model cant be used under the circumstances )
Looking forward your replying sincerely
Thanks @davidsandberg

**Comment by MaartenBloemen** [comment]
Hey @xvdehao ,
For example of face verification you can take a look at [compare.py](https://github.com/davidsandberg/facenet/blob/master/src/compare.py).
If you want to use something like SVM it is classification. There is also an example of classification: [classifier.py](https://github.com/davidsandberg/facenet/blob/master/src/classifier.py).
I hope this answers your questions.

**Comment by xvdehao** [comment]
So thankful of your answer @MaartenBloemen   Thats realy helpful to me
And now I use the compare.py to verify two pictures,the result is here

![result](https://user-images.githubusercontent.com/31030801/33158185-b5a5b5ca-d042-11e7-8c75-0e4516340159.png)

Whats the meaning of this result? And thejudgment criteria is the same as SVM model used in classify.py?
@MaartenBloemen  @davidsandberg 
Any answer is very helpful to me Thank you

**Comment by MaartenBloemen** [comment]
@xvdehao The output is the euclidean distance, this is always a number between 0 and 2 where 0 is 100% the same and 2 is 0% the same, if you want the output as a percentage you can use `confidence = (2 - dist) * 50`, so in your case it would mean the confidence is 72.75%.

For SVM the output is different, here the output is a percentage as a decimal number. If you need an explanation on how to train an SVM classifier have a look on the [wiki](https://github.com/davidsandberg/facenet/wiki/Train-a-classifier-on-own-images).

**Comment by xvdehao** [comment]
Got it, this answer is really useful and distinct.
Thank you so much
