### ISSUE TITLE
How to handle the data

### ISSUE THREAD

**Issue by Leedonggeon** [davidsandberg/facenet#546]
I'm a student major in computer science. And now i wanna identify whether the two person are the same person  or not.
If i wanna use my data, it's feature is different from  dataset that is used for this model.
so if i use the new image to run compare.py,  it return shape error like input:0 is must be ( , , , , ) ...
so how to handle the newdata?
I wanna help.

**Comment by xvdehao** [comment]
Hi @Leedonggeon beacause of the pretained model, all you need is to resize your image to 160*160(thats the default),and then you can use the compare.py to face verification
hope its helpful to you

**Comment by Leedonggeon** [comment]
Thanks for your help. I got it. I will resize the image!
Thank u!
