### ISSUE TITLE
my_classifier.pkl missing

### ISSUE THREAD

**Issue by FilippoGrazioli** [davidsandberg/facenet#550]
Hello, when I try to run real_time_face_rcognition.py I get the following error:

`FileNotFoundError: [Errno 2] No such file or directory: '/home/user/facenet/contributed/../model_checkpoints/my_classifier_1.pkl'`

I downloaded the pretrained Inception ResNet v1 on MS-Celeb-1M dataset. How should I get the my_classifier.pkl file now?

Thanks a lot.
Filippo

**Comment by xvdehao** [comment]
Hello @FilippoGrazioli  the pretrained model is used to export the face_embeddings and the you need used these embeddings to train your own model(my_classifier_1.pkl which is used by SVM model) you cans see the /src/classify.py 
Firstly you must get your own model and the you use it to real_time_face_recoginition
