### ISSUE TITLE
How to modify AlignMtcnn.py on images containing multiple faces?

### ISSUE THREAD

**Issue by RaviRaaja** [davidsandberg/facenet#554]
How to use alignmtcnn for dataset containing images and in each image there are multiple faces?

**Comment by cjekel** [comment]
Something is wrong, so I suggest using the MTCNN from the facenet library on a single image. Pick a good image, with a clearly identifiable face. Then tweak the parameters until you can get something working...

 i.e. perhaps your min face size was too small...

What is the resolution of the images? 

I've made a script to plot the MTCNN results on detecting faces, which may be useful in your case just to tweak the parameters...
https://github.com/cjekel/cjekel.github.io/blob/master/assets/2017-05-01/faceDetect.py
with a short description of the script here > http://jekel.me/2017/How-to-detect-faces-using-facenet/

**Comment by qixianbiao** [comment]
https://github.com/davidsandberg/facenet/blob/master/src/align/align_dataset_mtcnn.py

bounding_boxes, _ = align.detect_face.detect_face(img, minsize, pnet, rnet, onet, threshold, factor)
#actually, this line will detect all faces in the image, the following code will only select one face in the middle of the image.
                        nrof_faces = bounding_boxes.shape[0]
                        if nrof_faces>0:
                            det = bounding_boxes[:,0:4]
                            det_arr = []
                            img_size = np.asarray(img.shape)[0:2]
                            if nrof_faces>1:
                                if args.detect_multiple_faces:
                                    for i in range(nrof_faces):
                                        det_arr.append(np.squeeze(det[i]))
                                else:
                                    bounding_box_size = (det[:,2]-det[:,0])*(det[:,3]-det[:,1])
                                    img_center = img_size / 2
                                    offsets = np.vstack([ (det[:,0]+det[:,2])/2-img_center[1], (det[:,1]+det[:,3])/2-img_center[0] ])
                                    offset_dist_squared = np.sum(np.power(offsets,2.0),0)
                                    index = np.argmax(bounding_box_size-offset_dist_squared*2.0) # some extra weight on the centering
                                    det_arr.append(det[index,:])
                            else:
                                det_arr.append(np.squeeze(det))

**Comment by RaviRaaja** [comment]
Thank you ,very useful
