### ISSUE TITLE
Questions in the procedure of validation on lfw

### ISSUE THREAD

**Issue by zzw1123** [davidsandberg/facenet#555]
Thanks for your contribution,david.
But I have a doubt that before feeding the testset into the model we trained already, should we first detect faces in the images of lfw?In order to make the embeddings contain only the part of face which is more pure?

**Comment by qixianbiao** [comment]
See my reply in Sphereface repository issue.....

**Comment by zzw1123** [comment]
Thank you,xianbiao.
It is aligned as preprocess.
