### ISSUE TITLE
if size of images set 110, and how to set margin?

### ISSUE THREAD

**Issue by ronyuzhang** [davidsandberg/facenet#556]
@davidsandberg

**Comment by qixianbiao** [comment]
Currently, it is very hard to train the model with Triplet loss. 
The most succussful model is trained with classification loss (softmax  loss, center loss), no margin..

If you train your model with sphereface, it has an angle margin. it is hard to set the margin, no fixed solution. Try it.

**Comment by davidsandberg** [comment]
@ronyuzhang Difficult to say. I guess you would have to try a few margins and select the one that works best.
