### ISSUE TITLE
Why don't use cos distance for LFW validation?

### ISSUE THREAD

**Issue by xiaoyaozzr** [davidsandberg/facenet#558]
I wonder why in facenet don't use cos distance in LFW validation.  The lfw.py using "thresholds = np.arange(0, 4, 0.01)", and the  function "calculate_roc" in facenet.py is using 
"diff = np.subtract(embeddings1, embeddings2)   
 dist = np.sum(np.square(diff),1)"

**Comment by qixianbiao** [comment]
If embeddings1 and embeddings2 are both L2 normalized, then L2 distance equals to cos distance....

**Comment by Salon-sai** [comment]
I not agree @qixianbiao . After L2 normalizing, them L2 distance is not equals cosine distance. You can derived the formula of cosine ([Law of cosines](https://en.wikipedia.org/wiki/Law_of_cosines)). 
1. In the training, the loss function use the L2 distance as main factor of measuring the similarity with three vectors.
2. If you use the cosine as distance, you will change the `thresholds = np.arange(1, -1, 0.01)`. You can try to change it, but I guess L2 distance is better than cosine distance.
