### ISSUE TITLE
Remove phase_train from Squeezenet 

### ISSUE THREAD

**Issue by ottisoftware** [davidsandberg/facenet#560]
Hello, 
I'd like to convert my Squeezenet tensorflow model using the Qualcomm NPE. The problem is, that Qualcomm's NPE only supports a 3D tensor as an input. Squeezenet uses an image tensor plus a phase_train tensor (4D tensor) as an input. 
```
with slim.arg_scope([slim.batch_norm, slim.dropout], is_training=phase_train):
``` 
My question is: How can I remove the phase_train tensor from the squeezenet model in order to input only an image?
Maybe one can remove the phase_train during freezing of the graph?

**Comment by JianbangZ** [comment]
You can write a pbtxt with removing phase_train, then use the checkpoint file and modified pbtxt to freeze graph.

**Comment by ottisoftware** [comment]
Thanks @JianbangZ  
I saved the model to a pbtxt.
Instead of removing phase_train I replaced it with a Constant:
`node { 
  name: "phase_train" 
  op: "Const" 
  attr { 
    key: "dtype"
	value { 
	  type: DT_BOOL 
	} 
  } 
  attr { 
    key: "value" 
	value { 
	  tensor { 
	    dtype: DT_BOOL 
		tensor_shape { } 
	    bool_val: false 
	  } 
	} 
  } 
}
`
Then I converted the .pbtxt back to .pb file
