### ISSUE TITLE
How about implement CapsNet?

### ISSUE THREAD

**Issue by apollo-time** [davidsandberg/facenet#564]
How about implement CapsNet based on Geoffrey Hinton's paper [Dynamic Routing Between Capsules](https://arxiv.org/abs/1710.09829)?

**Comment by RakshakTalwar** [comment]
Fantastic idea, would you like to implement it?

**Comment by apollo-time** [comment]
I don't know how to implement it :(.

**Comment by tiagofrepereira2012** [comment]
there's some examples online, I can give it a try and do a PR: https://github.com/bourdakos1/capsule-networks
