### ISSUE TITLE
Don't have pairs for my dataset

### ISSUE THREAD

**Issue by malmajid** [davidsandberg/facenet#565]
Hi David, 

I'm trying to use some of your code to predict age classification. The problem is that I don't have pairs of images for my dataset. Is there a way to go around that so that I can still use your code? 

Also, do you have the trained weights for Facenet? I want to try and use transfer learning using these weights to predict the age. 

Please let me know. 

Thanks, 
Muhammad

**Comment by Zumbalamambo** [comment]
@malmajid did u manage to do this?
