### ISSUE TITLE
How to use facenet with multi-gpu ?

### ISSUE THREAD

**Issue by LingJiangXie** [davidsandberg/facenet#566]

**Comment by hustzeyu** [comment]
I have the same question ...

**Comment by RakshakTalwar** [comment]
Try taking a look at the following link. I haven't tried it myself but it's worth taking a look at. Please note this resource talks about data parallelism and not process parallelism.

https://github.com/vahidk/EffectiveTensorflow#multi-gpu-processing-with-data-parallelism

**Comment by Alireza-Akhavan** [comment]
Same question .
