### ISSUE TITLE
New train dataset

### ISSUE THREAD

**Issue by aleksandar** [davidsandberg/facenet#569]
http://www.robots.ox.ac.uk/~vgg/data/vgg_face2/
There is new face dataset for training, it would be nice to see results with this set which has high variance.

paper: https://arxiv.org/pdf/1710.08092.pdf

**Comment by RakshakTalwar** [comment]
Would you like to train it on this and show us results?

**Comment by aleksandar** [comment]
no problem, but i need computing power :)
