### ISSUE TITLE
Question about the shape of embddings

### ISSUE THREAD

**Issue by VictoryDong** [davidsandberg/facenet#57]
About two month ago, I used facenet_train.py to train nn4_small2_v model.if I input one image, the output shape of embddings is (1, 128).But now,I used the new code of  facenet_train.py  to train nn4_small2_v model,if I input one image, the output shape change to (9,128).Is this normal?
my code :
feed_dict = {self.images_placeholder: [oneimage], self.phase_train_placeholder: False}
output=(self.sess.run(self.embeddings, feed_dict=feed_dict))
print(output.shape)

**Comment by davidsandberg** [comment]
I'm not sure what is going on there. I ran the test case test_training_nn4_small2_v1 in test/train_test and put a break point on line 200 in facenet_train.py.
For the variable batch i have the dimensions
>>> batch.shape
(6, 96, 96, 3)
and for the emeddings generated by that line i get the dimensions
>>> sess.run(embeddings, feed_dict=feed_dict).shape
(6, 128)
So the batch size is 6 in both the input and the embeddings which is as expected.

**Comment by VictoryDong** [comment]
@davidsandberg 
I have gived up finding the answer. My datasets had some error pictures ,so I used try/exception to keep training  going on.I don't know whether it can cause the problem or not.  Now, my first job is to remove error images.Anyway, Thanks a lot.
