### ISSUE TITLE
Number of triplets

### ISSUE THREAD

**Issue by Shahnawazgrewal** [davidsandberg/facenet#570]
Number of triplets depend on the nature of the dataset. One can increase or decrease number of triplets using `images_per_person`. 
I am interested to know the number of triplets the network can handle. (I am not able to train the network if triplet is more `100k`). I hope someone can provide insights.

**Comment by RakshakTalwar** [comment]
It's not the network itself that poses as a limiting factor. It's the computational complexity of finding a larger selection of triplets.
