### ISSUE TITLE
det1.py error 

### ISSUE THREAD

**Issue by numbjugler** [davidsandberg/facenet#571]
hai sir.im currently using ur repository to make face recognition.i run the program using ubuntu and python. ive follow all requirement needed for the process. but when i run some program in aligning face i couldn't find the path or directories containing the det1.py. ive got an error of ioerror even the path that should contained the det1. py do existed in that directories. how do i solve this problem?

**Comment by RakshakTalwar** [comment]
Make sure you set your working directory to the right path if you're using an IDE. All paths are relative to the working directory.
