### ISSUE TITLE
problem with freeze_grapy.py

### ISSUE THREAD

**Issue by lztnus0129003** [davidsandberg/facenet#572]
Hi
I got a problem it seems I made some mistake.
When I use the freeze_graph.py, I run in the terminal with
python /home/rhlog/facenet/src/freeze_graph.py /home/rhlog/1/20171208-130038/  output_file=2017120813.pb
and it showed:  6352 ops in the final graph: output_file=2017120813.pb

However I can not find the file.

**Comment by hsm4703** [comment]
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile:  出現這個問題
