### ISSUE TITLE
Did the module align implement the alignment function？

### ISSUE THREAD

**Issue by haoxuhao** [davidsandberg/facenet#573]
In the script file align_dataset_mtcnn.py, i can only find the expanding margin but not alignment. Furthermore, the face landmarks returned by function align.detect_face.detect_face() is not used in the file. Did I miss some details?  Can anybody help me,? Thanks a lot.

**Comment by MaartenBloemen** [comment]
No you are right there is no real alignment the face is just cropped out of the picture. But as quoted from the [Google FaceNet Paper](https://arxiv.org/pdf/1503.03832.pdf).
> Another strength of our model is that it only requires
minimal alignment (tight crop around the face area). [17],
for example, performs a complex 3D alignment. We also
experimented with a similarity transform alignment and notice
that this can actually improve performance slightly. It
is not clear if it is worth the extra complexity.

**Comment by haoxuhao** [comment]
Thanks very much.
