### ISSUE TITLE
Alignment Fail

### ISSUE THREAD

**Issue by GarrettLee** [davidsandberg/facenet#574]
Hi, everyone.

Following the tutorial [Validate on LFW](https://github.com/davidsandberg/facenet/wiki/Validate-on-lfw). Only 8 of the faces can be aligned, all of the other faces can not be detected correctly. I checked the file align_dataset_mtcnn.py, and found that at the line below, for almost all of the fail faces, nrof_faces is equal to 0:

https://github.com/davidsandberg/facenet/blob/95b3b5d31666a1bb2f2fd26a4c3030dc2313be7c/src/align/align_dataset_mtcnn.py#L98

Anyone has the same problem? Can anyone help me? T

**Comment by davidsandberg** [comment]
Closed due to inactivity. Reopen if needed.
