### ISSUE TITLE
The validation rate is very low around 0.2 while the accuracy is high around 0.9

### ISSUE THREAD

**Issue by cactuslei** [davidsandberg/facenet#577]
When I training the inception-net-v1 on the new released dataset vggface2, the accuracy on lfw can reach 0.9 while the validation rate is very low around 0.2 and not increasing. Anyone met this problem? Thanks.

**Comment by Vallum** [comment]
If I am not wrong, it is normal.
Val-rate will grow more than 0.4 after the accuracy is over 0.95.
If you want high val-rate like 0.9, the accuracy should be much higher.
The learning curve is pretty different between the two.

**Comment by cactuslei** [comment]
After I add Squeeze-net to inception_resnet_v1 and training with vggface2, the val-rate could reach 0.9 now.

**Comment by InitAction** [comment]
@cactuslei I have same problem
