### ISSUE TITLE
scipy.misc deprecated functions @align/align_dataset_mtcnn.py

### ISSUE THREAD

**Issue by Victoratgit** [davidsandberg/facenet#579]
The following functions in scipy.misc are deprecated since [scipy 1.0.0](https://docs.scipy.org/doc/scipy/reference/misc.html): bytescale, fromimage, imfilter, imread, imresize, imrotate, imsave, imshow and toimage. 
Use [imageio](http://imageio.github.io/) instead.

Affected file (at least): align/align_dataset_mtcnn.py
solution:

import imageio
with
imageio.imread
imageio.imresize
imageio.imsave

_(sorry, newbee don't know how to do it myself)_

**Comment by cjekel** [comment]
Okay so 
misc.imread = imageio.imread
misc.imresize = skimage.transform.resize (but you need to remove interp='')
misc.imsave = imageio.imwrite

I have a working align_dataset_mtcnn.py that does not use scipy.misc (using the above equivalents). 

I'd like someone to comment if these replacement functions are adequate before creating a pr with these changes throughout facenet.

**Comment by cjekel** [comment]
okay so skimage.transfrom.resize isn't a replacement for cv2.resize in the following line of detect_face.py
```
 im_data = cv2.resize(img, (sz[1], sz[0]), interpolation=cv2.INTER_AREA) 
```
