### ISSUE TITLE
Did anyone tried other models that also can achieve ~99% accuracy on LFW?

### ISSUE THREAD

**Issue by xmuszq** [davidsandberg/facenet#592]
Based on inception_resnet, it's able to go up to ~99% accuracy on LFW. However, I tried other models like alex net even with very deep architectures, I was only able to get <95% accuracy. Does any one has any experience on training Alex net (OR other architectures) and get relatively high accuracy?  

Many thanks,

**Comment by xmuszq** [comment]
I tried an Alex net with 17 conv layers, it's only able to get 94% accuracy. What's the wrong?

**Comment by hustzeyu** [comment]
inception_resnet is the best

**Comment by xmuszq** [comment]
@hustzeyu 
Thank you for your reply!  Yes, inception_resnet is good. I just want to know how much the other architecture can achieve.
