### ISSUE TITLE
I'm sorry, I'm currently working in China. There is no access to drive.google.com.

### ISSUE THREAD

**Issue by Heermosi** [davidsandberg/facenet#598]
I'm sorry, because of political issues, the scientists and students in China cannot get an access to this website. May be you can send an email to me so that I can share it?
If the emails are not still not accessible …… well, we have to train it. May be you may predict how much time may be spent on a 1080Ti?

**Comment by efun100** [comment]
链接：https://pan.baidu.com/s/1nvBX233 密码：s0sb

**Comment by cjekel** [comment]
[Here](https://mega.nz/#!d6gxFL5b!ZLINGZKxdAQ-H7ZguAibd6GmXFXCcr39XxAvIjmTKew) is a mega mirror of the 20170512-110547 model

**Comment by hustzeyu** [comment]
至少要会翻墙吧，不然搞什么科研

**Comment by xxllp** [comment]
@efun100 ,分享过期了，能重新发下嘛

**Comment by efun100** [comment]
链接：https://pan.baidu.com/s/1cdNwkJPW29r9RHjRbNXmIg 密码：449o
