### ISSUE TITLE
"Training classifier" is running ? or stuck ?

### ISSUE THREAD

**Issue by hustzeyu** [davidsandberg/facenet#603]
I had trained my 20,000 (100 * 100) images to create my own model using train_softmax.py, then I got .ckpt files. I froze the model with freeze_graph.py to get .pb file. Then, I tried to use .pb to get .pkl by classifier.py. In this step, it is running almost 2 days, and still shows "Training classifier"... is it really running? Or it is stuck ?  Why it takes so long? Last time I remember when training 10,000 (160 * 160) CASIA-WebFace faces, it only took less than a day... Please help me or give some information, thanks! 
   
![image](https://user-images.githubusercontent.com/16651561/34593187-425ec8a2-f204-11e7-89cf-b55b270a3878.png)

![image](https://user-images.githubusercontent.com/16651561/34593213-6da9d6aa-f204-11e7-87d8-533d47a03c88.png)

**Comment by NanhaiK** [comment]
Did you use the model "models.inception_resnet_v1"?I use the "models.inception_resnet_v2"，but the error occured:
"FailedPreconditionError (see above for traceback): Attempting to use uninitialized value InceptionResnetV2/Conv2d_1a_3x3/weights
         [[Node: InceptionResnetV2/Conv2d_1a_3x3/weights/read = Identity[T=DT_FLOAT, _class=["loc:@InceptionResnetV2/Conv2d_1a_3x3/weights"], _device="/job:localhost/replica:0/task:0/gpu:0"](InceptionResnetV2/Conv2d_1a_3x3/weights)]]
         [[Node: embeddings/_421 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_18859_embeddings", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]"
 Is that the clsssify.py and facenet.py are only for the  "inception_resnet_v1”？

**Comment by hustzeyu** [comment]
@NanhaiK  I used inception_resnet_v1. But as I look deeper into details, I found that the reason may be the input image size is too small and it should be or bigger than 160*160. Say my input is 100*100, the feature map inference is as follows:
100*100  
49*49
47*47
47*47
23*23
23*23
21*21
10*10
10*10  Inception-ResNet-A *5
4*4    Reduction-A
4*4    Inception-ResNet-B *10
1*1    Reduction-B
1*1    Inception-ResNet-C
Int the last layer, it should at least be 3*3, because it has to go through a conv2d with filter size being [1,3] and [3,1]... 
Say the input is 160*160, the feature map changes like this:

160*160
79*79
77*77
77*77
38*38
38*38
36*36
17*17
17*17
8*8
8*8
3*3
3*3
And it satisfies the inception_ResNet_v1 minimum requirement. So the smallest input for this network should be 160*160. I did not have a chance to look at inception_ResNet_v2. But your error may be related to the image size too. Say if your input is too small, then the last couple of layers are not even initialized. Or did you use inception_ResNet_v2 to calculate from the very beginning? Or did you use the inception_ResNet_V1 pretrained model to calculate inception_ResNet_V2? All of these is from my guess...

**Comment by hsm4703** [comment]
How many classifications
How many pictures does a category have?
your performance is better?
