### ISSUE TITLE
training triplet loss erro that is ValueError: cannot reshape array of size 160 into shape (3).

### ISSUE THREAD

**Issue by maguro27** [davidsandberg/facenet#609]
Hi.
When I implemented transfer learning, I receive error that is "ValueError: cannot reshape array of size 160 into shape (3)".
Here is implementation code.

`python src/train_tripletloss.py --logs_base_dir ~/lab/experiments/facenet/logs/facenet/ --models_base_dir ~/lab/experiments/facenet/models/facenet/ --data_dir ~/lab/experiments/noise_lfw_30_mtcnnalign_182_160 --image_size 160 --model_def models.inception_resnet_v1 --weight_decay 1e-4 --optimizer RMSPROP --learning_rate 0.01 --keep_probability 0.8 --random_crop --random_flip --pretrained_model ~/lab/experiments/facenet/model/20170512-110547/model-20170512-110547.ckpt-250000 --people_per_batch 80 --images_per_person 2  --gpu_memory_fraction 0.15`

And here is all error messages

////////////////////////////////////////
Running forward pass on sampled images: Traceback (most recent call last):
  File "src/train_tripletloss.py", line 486, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/train_tripletloss.py", line 186, in main
    args.embedding_size, anchor, positive, negative, triplet_loss)
  File "src/train_tripletloss.py", line 217, in train
    labels_array = np.reshape(np.arange(nrof_examples),(-1,3))
  File "/home/hideki/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 232, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/hideki/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 160 into shape (3)
////////////////////////////////////////

The dataset used transfer learning is LFW dataset aligned by mtcnn and size is 160 x 160.
The dataset have 1678 directories and 3356 files.
Although I tried to changing 160 to 182 in size, program said the same error.
What should I do?

Please lend me hands.

**Comment by maguro27** [comment]
I changed `people_per_batch` and `image_per_batch` to `(people_per_batch*image_per_batch)%3==0`. Then, program didn't say that error. But I don't know that it is the primordial resolution.

**Comment by abhisheksgumadi** [comment]
@maguro27 , where did you make the change please?

**Comment by maguro27** [comment]
@abhisheksgumadi I'm sorry to send you message lately. I changed `people_per_batch` and `image_per_batch` in my implementation code. Finally, I set `people_per_batch 3` and `image_per_batch 5`. But, when I set `(people_per_batch*image_per_batch) < 10`, program said error.

**Comment by ghost** [comment]
@maguro27  Can you please explain further, the explanation is a bit unclear. What exactly do you mean by your code implementation? Where did you make changes?

**Comment by anandhakrishnanh** [comment]
@maguro27 Can you explain why is the error coming?

**Comment by maguro27** [comment]
@ichippa96 @anandhakrishnanh1998 
Thank you for replying me. However, I already fixed the above problem and closed this issue. Moreover, I already did not use FaceNet since 2018, Mar.
Therefore, I forget the problem of my question. Thanks.

**Comment by pv4n** [comment]
assert (people_per_batch * images_per_person) % 3 == 0
