### ISSUE TITLE
squeezenet pre-train

### ISSUE THREAD

**Issue by Alireza-Akhavan** [davidsandberg/facenet#613]
There is a squeezenet.py in a model directory.
Could you please share pre-train model for **squeezenet** architecture?
what is the LFW accuracy.

**Comment by Alireza-Akhavan** [comment]
@davidsandberg I would be grateful if you could consider my above question.

**Comment by yipsang** [comment]
@Alireza-Akhavan 
I have trained a model of squeezenet on VGG Face 2 Dataset.

<img width="1315" alt="screen shot 2018-02-06 at 8 46 31 pm" src="https://user-images.githubusercontent.com/17806604/35860811-61e61ac8-0b80-11e8-80c8-344ba576a644.png">

Here is the result after running validation on LFW:
```
Model directory: ../models/20180204-160909
Metagraph file: model-20180204-160909.meta
Checkpoint file: model-20180204-160909.ckpt-266000
Runnning forward pass on LFW images
Accuracy: 0.982+-0.008
Validation rate: 0.91933+-0.02102 @ FAR=0.00133
Area Under Curve (AUC): 0.998
Equal Error Rate (EER): 0.017
```

You can download it here if you find it useful.
[https://drive.google.com/file/d/1phGtQBEAh8L2GsKXByagD1sLQnFQ8hjd/view?usp=sharing](url)

**Comment by vathlala** [comment]
How did you freeze graph of SqueezeNet architecture and export to .pb file?

**Comment by hgffly** [comment]
@yipsang 
Thanks for sharing your pretrained squeeze net, it's a great achievement
It would be very helpful if you could share the way you trained the squeeze net
You trained it with softmax or triplet loss ?
How about the learning rate ?
Thanks advance

**Comment by Alireza-Akhavan** [comment]
Hi @yipsang ,
I am so thankful for your cooperation.
As @hgffly asked, could you please give me more information about the train information?
You have used softmax or triplet loss ? and about parameters like LR?
Thanks

**Comment by zhenglaizhang** [comment]
Hi @yipsang I tried your model, but met with following issue:

```
FailedPreconditionError (see above for traceback): Attempting to use uninitialized value squeezenet/conv1/BatchNorm/beta
         [[Node: squeezenet/conv1/BatchNorm/beta/read = Identity[T=DT_FLOAT, _class=["loc:@squeezenet/conv1/BatchNorm/beta"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](squeezenet/conv1/BatchNorm/beta)]]
```

**Comment by zhenglaizhang** [comment]
update the freeze_graph.py a bit, and now the model provided by @yipsang could work successfully.

**Comment by yipsang** [comment]
@hgffly @Alireza-Akhavan 
I used center loss to train. And here is the hyperparameters I've used:
--keep_probability 0.8 --max_nrof_epochs 2000 --weight_decay 5e-5 --random_crop --random_flip --learning_rate_decay_factor 0.5 --learning_rate 0.1 --learning_rate_decay_epochs 25 --center_loss_factor 1e-2 --center_loss_alfa 0.9 --optimizer RMSPROP

@zhenglaizhang I haven't come across with the error you had before, glad to hear you've solved it.

**Comment by karlTUM** [comment]
@yipsang Have you ever tried to train MobileNet or ShuffelNet?

**Comment by hgffly** [comment]
@yipsang , very thankful for your sharing

**Comment by karlTUM** [comment]
@zhenglaizhang I also have your problem. How did you solve that? Thank you very much.

**Comment by kodonnell** [comment]
Same problem as @zhenglaizhang and @karlTUM . Using the checkpoints (not `.pb` file) works, but the accuracy is very poor (compared to the standard model) for my use case (for now, basically just comparing ten members of the office) - though I do get similar LFW numbers when I validate it.

From what I can tell, this is using the euclidean distance - though oddly, these distances are on the order of 1e-3 instead of more like 1e-1 for the current model, which makes me think something might be off.

**Comment by tslater** [comment]
@zhenglaizhang Do you mind sharing what you did to freeze the model?

**Comment by caocuong0306** [comment]
Hi @yipsang , thanks for great work.

Can you explain a bit more about face alignment, --image_size, --margin information when training with VGGFace2.

Thank you.

**Comment by drohack** [comment]
I'm very new to all of this tensorflow, training, and freezing. I'm attempting to compile the trained squeezenet graph provided in this issue to run on the [Google AIY Vision Kit](https://aiyprojects.withgoogle.com/vision/#makers-guide--tensorflow-model-compiler).

Using their [compiler](https://dl.google.com/dl/aiyprojects/vision/bonnet_model_compiler_latest.tgz) I've tried running this command:
`./bonnet_model_compiler.par --frozen_graph_path 20180204-160909/20180204-16090.pb --output_graph_path vggface2_sqeezenet.binaryproto --input_tensor_name input --output_tensor_names embeddings --input_tensor_size 160 --debug`
But I'm getting this error:
```2018-06-24 19:57:47.448345: I external/org_tensorflow/tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 1207 operators, 1562 arrays (0 quantized)
2018-06-24 19:57:47.484325: I external/org_tensorflow/tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 1207 operators, 1562 arrays (0 quantized)
2018-06-24 19:57:47.526755: I external/org_tensorflow/tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 989 operators, 1360 arrays (0 quantized)
2018-06-24 19:57:47.564350: I external/org_tensorflow/tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 989 operators, 1360 arrays (0 quantized)
2018-06-24 19:57:47.586820: F external/org_tensorflow/tensorflow/contrib/lite/toco/toco_tooling.cc:46] Check failed: unsupported_ops.empty() These unsupported ops were not removed by graph transformations: Prod, Reciprocal, SquaredDifference, VariableV2
```

I've tried looking up the `unsupported_ops.empty()` online, but could not parse what was needed to be done to get past this error (or if anything could be done). I'm not even sure if I'm running the compiler on the correct file, or if I need to freeze the graph (or is the 20180204-16090.pb file the already frozen graph)...

Thanks for any help

**Comment by VyasAyushi** [comment]
How to define squeezenet model in model_def?
when i am giving --model_def models.squeezenet it is giving me this error
train_softmax.py: error: unrecognized arguments: models.squeezenet
I am new to this.Please help

**Comment by jass-singh-zz** [comment]
Hi, 
@yipsang i tried to convert 20180204-16090.pb into .binaryproto for AIY vision tool kit ,
where it is showing error : 

Check failed: unsupported_ops.empty() These unsupported ops were not removed by graph transformations: FIFOQueueV2, Prod, QueueDequeueUpToV2, Reciprocal, SquaredDifference, VariableV2

How to resolve it ??
Thanks,

**Comment by tfabio** [comment]
> update the freeze_graph.py a bit, and now the model provided by @yipsang could work successfully.

Can you please share what you changed to make the model working?

**Comment by taojin1992** [comment]
@yipsang How do you get the evaluation metric values? I got the following errors when running the command. 

c02wj0huhv2t:facenet jintao01$ python3 src/validate_on_lfw.py dataset/lfw/lfw_mtcnnpy_160 20180204-160909 --distance_metric 1 --use_flipped_images --subtract_mean --use_fixed_image_standardization
2018-11-02 17:08:09.928446: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Model directory: 20180204-160909
Metagraph file: model-20180204-160909.meta
Checkpoint file: model-20180204-160909.ckpt-266000
Traceback (most recent call last):
  File "/Users/jintao01/.local/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 667, in import_graph_def
    op._add_input(source_tensor, dtype=input_type)
  File "/Users/jintao01/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1898, in _add_input
    (tensor.dtype.name, dtype.name))
TypeError: Cannot convert a tensor of type int32 to an input of type int64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/validate_on_lfw.py", line 164, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/validate_on_lfw.py", line 73, in main
    facenet.load_model(args.model, input_map=input_map)
  File "/Users/jintao01/Documents/facenet/src/facenet.py", line 382, in load_model
    saver = tf.train.import_meta_graph(os.path.join(model_exp, meta_file), input_map=input_map)
  File "/Users/jintao01/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1927, in import_meta_graph
    **kwargs)
  File "/Users/jintao01/.local/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 741, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/Users/jintao01/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/Users/jintao01/.local/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 671, in import_graph_def
    node, 'Input tensor %r %s' % (input_name, te)))
ValueError: graph_def is invalid at node 'Reshape': Input tensor 'label_batch:0' Cannot convert a tensor of type int32 to an input of type int64.

**Comment by taojin1992** [comment]
@yipsang  Which version of validate_on_lfw.py did you use? How did you run the command? Thank you!

**Comment by taojin1992** [comment]
My problem fixed.

**Comment by axelaco** [comment]
@tfabio In freeze_graph.py you have to add this line in whitelist_names, 
node.name.startswith('squeezenet'))

**Comment by larsonwu0220** [comment]
@zhenglaizhang  : 
I have the same error of "Attempting to use uninitialized value". 
How did you solve this problem?

The error message as following :
FailedPreconditionError (see above for traceback): Attempting to use uninitialized value squeezenet/conv1/weights
         [[Node: squeezenet/conv1/weights/read = Identity[T=DT_FLOAT, _class=["loc:@squeezenet/conv1/weights"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](squeezenet/conv1/weights)]]

Thanks for your help.
