### ISSUE TITLE
How to pretrain model when setting --pretrained_model

### ISSUE THREAD

**Issue by xiaoxinyi** [davidsandberg/facenet#614]
Error:

```
 Data loss: not an sstable (bad magic number)
```

I used pretrained model by repository and first-echo-model from scratch training, both failed with the same error.

**Comment by changgongcheng** [comment]
I have the same problem

**Comment by Mahsa1994** [comment]
I fixed it by giving the semi-complete path of the model, something like this:
`--pretrained_model ./models/20170512-110547/model-20170512-110547.ckpt-250000`
