### ISSUE TITLE
How to submit LFW test result to lfw webpage?

### ISSUE THREAD

**Issue by shanren7** [davidsandberg/facenet#616]
I want to submit LFW test result to LFW results webpage(http://vis-www.cs.umass.edu/lfw/results.html). However, I failed to find any submit port or webpage or description. Could anybody give me some advice?

**Comment by allenxcp** [comment]
send your result to gbhuang@cs.umass.edu

**Comment by zhengge** [comment]
I want to submit LFW test result to LFW results webpage too. Did you do it?

**Comment by yewuyue111** [comment]
Hi @shanren7 @zhengge 
Have you guys know how to submit LFW test result to LFW results webpage?I also want to do this job.
Thanks.

**Comment by kli-casia** [comment]
+1
