### ISSUE TITLE
Opening new research areas: Video demo of FaceNet Face Recognition using MTCNN detection and alignment

### ISSUE THREAD

**Issue by smajida** [davidsandberg/facenet#623]
Hi,

Is a script provided with which one can run a test video to see the performance of FaceNet on open-set scenarios like the one provided in SphereFace project:https://github.com/wy1iu/sphereface?
@davidsandberg 
A script which would work with videos or webcam can be a good indicator of accuracy of system on face recognition in wild to find out what are the flaws on which one can do research.

**Comment by AshutoshDongare** [comment]
I have created a sample of continuous Face recognition by looping through Taking photo - MTCNN - Facenet. https://github.com/AshutoshDongare/FaceNet-IOT

**Comment by arasharchor** [comment]
@AshutoshDongare thanks a lot. that is great.!
