### ISSUE TITLE
compare.py has a bug! AttributeError: 'list' object has no attribute 'copy'

### ISSUE THREAD

**Issue by lvmeng8** [davidsandberg/facenet#638]
Python version: 2.7.12
CMD: python compare.py models/facenet/20170512-110547 fanwei-1.jpg fanwei-2.jpg
ERROR: 
Traceback (most recent call last):
  File "compare.py", line 129, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "compare.py", line 40, in main
    images = load_and_align_data(args.image_files, args.image_size, args.margin, args.gpu_memory_fraction)
  File "compare.py", line 91, in load_and_align_data
    tmp_image_paths = image_paths.copy()
AttributeError: 'list' object has no attribute 'copy'

Then I modify the code of the line 91 of  compare.py:  tmp_image_paths = copy.deepcopy(image_paths), the error above disappear.
Is this project support python 2.7?

**Comment by joypeacee** [comment]
I have the same issue on python 2.7

**Comment by joypeacee** [comment]
Solved by adding import copy to compare.py. Then change "tmp_image_paths = image_paths.copy()" to
    "tmp_image_paths=copy.copy(image_paths)"
