### ISSUE TITLE
Run code "op_def = op_dict[node.op]" and got KeyError: u'StridedSlice'

### ISSUE THREAD

**Issue by shawjan** [davidsandberg/facenet#64]
Hi,
   David, when I run your code for LFW test as you said in [Validate on LFW](https://github.com/davidsandberg/facenet/wiki/Validate-on-LFW) step by step, but unfortunately I got an error KeyError: u'StridedSlice'. More detail as follow. I just know that the dictionary "op_dict" has not key "StridedSlice". can you tell me why this error happen? Thank you!

> /Library/Python/2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Skipped 6000 image pairs
Model directory: /Users/shawjan/models/facenet/20161030-023650
Metagraph file: model-20161030-023650.meta
Checkpoint file: model-20161030-023650.ckpt-80000
Traceback (most recent call last):
  File "validate_on_lfw.py", line 89, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "validate_on_lfw.py", line 57, in main
    facenet.load_model(args.model_dir, meta_file, ckpt_file)
  File "/Users/shawjan/Documents/xcodeworkspace/facenet/src/facenet.py", line 469, in load_model
    saver = tf.train.import_meta_graph(os.path.join(model_dir_exp, meta_file))
  File "/Library/Python/2.7/site-packages/tensorflow/python/training/saver.py", line 1415, in import_meta_graph
    return _import_meta_graph_def(read_meta_graph_file(meta_graph_or_file))
  File "/Library/Python/2.7/site-packages/tensorflow/python/training/saver.py", line 1305, in _import_meta_graph_def
    importer.import_graph_def(meta_graph_def.graph_def, name="")
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/importer.py", line 228, in import_graph_def
    op_def = op_dict[node.op]
KeyError: u'StridedSlice'

**Comment by davidsandberg** [comment]
Which version of tensorflow are you using? According to #76 similar errors can occur with TF 0.10.

**Comment by keerthanpg** [comment]
Figured that if models are created in one version and evaluated in another, similar issue happens. I had multiple versions of tensorflow on my machine and the server hence the error.
