### ISSUE TITLE
Unable to load pretrained model

### ISSUE THREAD

**Issue by ricky5151** [davidsandberg/facenet#645]
Hi, I would like to load pretrained model in my data training. When i type this in my command:

-- pretrained_model model-20170512-110547.ckpt-250000

My program failed to load it. Can I know how should I write in my command?

**Comment by davidsandberg** [comment]
This option can be used to resume training but the number of classes must be the same when training is resumed.

**Comment by yyssmm** [comment]
HI, if the the number of classes is different from yours, what should I do to correctly load the pretrained model
