### ISSUE TITLE
Classifying the image using the trained model

### ISSUE THREAD

**Issue by heroinsoul** [davidsandberg/facenet#66]
I've followed the instructions in [Classifier training of inception resnet v1](https://github.com/davidsandberg/facenet/wiki/Classifier-training-of-inception-resnet-v1) and got the model files. 
Now similar to Openface I'd like to use the model to classify the images I feed. However, I haven't found a way to do that in the Wiki. The instructions mentioned in "Validate on LFW" use the predefined pairs of files from the dataset which is not exactly what I need.

I've found previously opened issues (#62 #30 #37) and you've mentioned a separate classifier_pretrain branch in development that was supposed to address this. There is no such branch anymore thus I've opened the issue to clarify that.

So, is it possible to feed an image to the facenet and output the name of the recognized person using the pretrained model? 

Thanks

**Comment by davidsandberg** [comment]
The branch classifier_pretrain was merged to master some time ago. With `facenet_train_classifier` you can train a model as a classifier.
This issue seems to be very similar to #62 so i propose closing this one and continue the discussion in that thread.
