### ISSUE TITLE
explanation about the prewhiten function

### ISSUE THREAD

**Issue by helloyide** [davidsandberg/facenet#661]
the prewhiten function in facenet.py:
`

def prewhiten(x):

    mean = np.mean(x)

    std = np.std(x)

    std_adj = np.maximum(std, 1.0 / np.sqrt(x.size))

    y = np.multiply(np.subtract(x, mean), 1 / std_adj)

    return y

`
It looks similar as standardization, except the std_adj part. why we take max of std and 1/sqrt(N) ?
Any link or explanation about this calculation would be very thankful.

**Comment by a7744hsc** [comment]
Also get confused here.

**Comment by helloyide** [comment]
well, i think i guess it's just the similar implement as tf.image.per_image_standardization, to prevent the underflow.

**Comment by milinddeore** [comment]
In statistics this is called [Z-Score](https://en.wikipedia.org/wiki/Standard_score), to standardized and normalized the data.

**Comment by Hamiltonsjtu** [comment]
It is capped away from zero to protect against division by 0 when handling uniform images.
