### ISSUE TITLE
use cosine similarity in center lose?

### ISSUE THREAD

**Issue by helloyide** [davidsandberg/facenet#662]
in the paper of center lose, author uses L2 norm in the center loss. Euclidean distance doesn't work well in high dimensional space, so how about replace it with the cosine similarity?

I saw some people use cosine similarity to compare the embedding vectors, but I think while the embedding are trained by L2 norm based center lose, we should also change the training as well.

Did anyone try this before? I will try it later.

**Comment by daeyoun24** [comment]
I'm curious about this as well. Any progress so far?

**Comment by helloyide** [comment]
Hi daeyoun, I wrote an email to the author of paper, don't get answer yet.

When I have time I will try it by myself. If anybody tested before, welcome to post your result here.

What I found out right now is that even the network is trained with L2 norm as written in paper, we can still compare the result embedding vectors with Cosine Similarity, it has similar result as Euclidean distance. So maybe it doesn't worth to change the original center loss, but need more research here.
