### ISSUE TITLE
Classifier training of inception resnet v1

### ISSUE THREAD

**Issue by BingoTiger** [davidsandberg/facenet#67]
Hi,
After face-alignment, python align_dataset_mtcnn.py ~/datasets/casia/CASIA-maxpy-clean/ ~/datasets/casia/casia_maxpy_mtcnnpy_182 --image_size 182 --margin 44, I get casia_maxpy_mtcnnpy_182

However,when starting training, you use casia_maxpy_mtcnnalign_182_160,how can I get this file from casia_maxpy_mtcnnpy_182?

Thanks

**Comment by davidsandberg** [comment]
It's just a matter of naming. Change the data directory to casia_maxpy_mtcnnpy_182 when you run the training command and you should be fine.
