### ISSUE TITLE
training on own dataset

### ISSUE THREAD

**Issue by zeynali** [davidsandberg/facenet#678]
How i train this model on own dataset ? is it possible for training ? my dataset is breeds of dogs.

**Comment by DSRYhh** [comment]
Absolutely you can. These are parameters you should pay attention:
- `--data_dir`: you own training dir with the same structure as LFW
- `--lfw_pairs` and `--lfw_dir` for testing.

Then you can train this without making any changes to the code.

**Comment by zeynali** [comment]
Thanks
Please put the walk-through for training and evaluation.

**Comment by zeynali** [comment]
Thanks
Please put the step by step for training and evaluation.

**Comment by DSRYhh** [comment]
@zeynali Yes you can train this for any type data. Just run `train_tripletloss.py` with required parameters

**Comment by lqd1994** [comment]
@huangbiubiu  
hi,thanks for your reply
i got a error when i run train_tripletloss.py

`InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 640 values, but the requested shape requires a multiple of 384`

sometimes 640 values could chenge to 1280 when i change batch_size 

Do you have any idea of this?

**Comment by erdalalim** [comment]
hi mr. @huangbiubiu , I want train facenet model with Casia Web Face dataset, and then to test it on LFW dataset.Its possible? 
I will try to do augmentation techniques on Casia Web dataset, If I will do good augmentation on the data it will give better accuracy?

**Comment by huangbiubiu** [comment]
@erdalalim 

Your first question. Yes. Certainly, it's possible.

Your second question, yes. If the augmentation technic is good it will definitely give a good result on the testing set.

**Comment by erdalalim** [comment]
@huangbiubiu  thanks for reply.
You Run facenet before? 
I wanna run facenet according to :https://github.com/TessFerrandez/research-papers/blob/master/facenet/FaceNet.ipynb   because there is video explanation : https://www.youtube.com/watch?v=w--c0qG9MCc 

the link with .ipynb is the same one like the code in this repository?
