### ISSUE TITLE
Calculate match-scores between pairs of face images

### ISSUE THREAD

**Issue by vmirly** [davidsandberg/facenet#681]
I have downloaded the trained model **20170512-110547** as well all the source code. However, I cannot find a documentation to build the computation-graph from the "20170512-110547.pb" file.

I tried the following, but the resulting g_in is None:
```
import tensorflow as tf
from tensorflow.python.platform import gfile

with tf.Session() as sess:
    model_filename =os.path.join(facenet_path, '20170512-110547.pb')
    with gfile.FastGFile(model_filename, 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        g_in = tf.import_graph_def(graph_def)
``` 

Is there any documentation, or example code to build the model, and restore the model parameters for the given checkpoints?

**Comment by MaartenBloemen** [comment]
You might want to take a look at [compare.py](https://github.com/davidsandberg/facenet/blob/master/src/compare.py). I think that is what you are looking for.
