### ISSUE TITLE
incremental training

### ISSUE THREAD

**Issue by mohammed-Emad** [davidsandberg/facenet#685]
Hi First I would like to thank everyone who contributed to providing these tools and that destination
Thanks @davidsandberg   for your patience in following and guiding users.
I really did not need to ask for anything before,
I found All answers were here.

But I apologize if my question was misplaced.,
Ask how to begin a **incremental training** while building the model in the future!
As a wonderful example train_softmax.py
But he does not meet what I've been talking about.
I do not want complete construction every time I **add more data**

Is this possible?
thank you

**Comment by AshutoshDongare** [comment]
Can @davidsandberg or other experts help. I also need to train incrementally not the full training every time. How do I go about achieving this ?
