### ISSUE TITLE
MTCNN alignment

### ISSUE THREAD

**Issue by liangxiaoxi** [davidsandberg/facenet#71]
`/home/dl1/LXX/facenet/datasets/casia/CASIA/0000099/255.jpg
Unable to align "/home/dl1/LXX/facenet/datasets/casia/CASIA/0000099/255.jpg"
/home/dl1/LXX/facenet/datasets/casia/CASIA/0000099/043.jpg
Unable to align "/home/dl1/LXX/facenet/datasets/casia/CASIA/0000099/043.jpg"
/home/dl1/LXX/facenet/datasets/casia/CASIA/0000099/152.jpg
Unable to align "/home/dl1/LXX/facenet/datasets/casia/CASIA/0000099/152.jpg"
/home/dl1/LXX/facenet/datasets/casia/CASIA/0000099/004.jpg
Unable to align "/home/dl1/LXX/facenet/datasets/casia/CASIA/0000099/004.jpg"
/home/dl1/LXX/facenet/datasets/casia/CASIA/0000099/256.jpg
Unable to align "/home/dl1/LXX/facenet/datasets/casia/CASIA/0000099/256.jpg"
/home/dl1/LXX/facenet/datasets/casia/CASIA/0000099/206.jpg
Unable to align "/home/dl1/LXX/facenet/datasets/casia/CASIA/0000099/206.jpg"
/home/dl1/LXX/facenet/datasets/casia/CASIA/0000099/212.jpg
Traceback (most recent call last):
  File "align_dataset_mtcnn.py", line 142, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "align_dataset_mtcnn.py", line 95, in main
    bounding_boxes, _ = align.detect_face.detect_face(img, minsize, pnet, rnet, onet, threshold, factor)
  File "/home/dl1/LXX/facenet/facenet-master/src/align/detect_face.py", line 383, in detect_face
    tmp = np.zeros((int(tmph[k]),int(tmpw[k]),3))
ValueError: negative dimensions are not allowed
`

**Comment by zhly0** [comment]
have you figure it out?because I have the same issue.

**Comment by kylerwang** [comment]
@zhly0 Hi! Could you help me with this issue? I have the same issue!

**Comment by cw-plus** [comment]
Me too...  so sad.
