### ISSUE TITLE
Still have pre-trained model on MS-Celeb-1M ?

### ISSUE THREAD

**Issue by raobystorm** [davidsandberg/facenet#711]
@davidsandberg and others

Hi, thanks for providing this awesome facenet! 👍 

I saw the pre-trained mode is updated with the one trained on VGG dataset.
Also I tried to use 20180402-114759 model to do cleaning on my own dataset. I want to create another dataset for face recognition, which consists faces varies in different ages.
But unfortunately the performance of this model is not as good as former one (2017 model trained on MS-Celeb-1M). 
I think this is because difference between dataset and maybe the distribution of MS dataset is closer to my dataset, but I deleted the model by accident... 😢 😢 😢 
Could you provide the download link again for the model 20170512-110547 ?

Very appreciate any advises and help!

**Comment by raobystorm** [comment]
Never mind. I found it by myself. Sorry for trouble 😃 
Please close this
https://drive.google.com/file/d/0B5MzpY9kBtDVZ2RpVDYwWmxoSUk/edit

**Comment by Nuha1412** [comment]
Can you tell me about 20170512-110547 accuracy and if the validation on lfw is available can you tell me ?
