### ISSUE TITLE
.pb file not generted after Classifier training of inception resnet v1 using train_softmax.py 

### ISSUE THREAD

**Issue by Abhijitdas2048** [davidsandberg/facenet#721]
.pb file not generated after Classifier training of inception resnet v1 using train_softmax.py 
please let me if some is facing smiler prob and any solution?

**Comment by MaartenBloemen** [comment]
You can get a protobuf file by using [freeze_graph.py](https://github.com/davidsandberg/facenet/blob/master/src/freeze_graph.py).

**Comment by Abhijitdas2048** [comment]
but it takes .pbtxt as one of the input argument right which is also  not generated in the code.

**Comment by MaartenBloemen** [comment]
It only takes model_dir as input, the dir which contains the cktp and meta files.

**Comment by Abhijitdas2048** [comment]
thanks can you send me the signature of using it

**Comment by liuajian** [comment]
Have you encountered this problem?
 max_axis = tf.reduce_max(target, axis, keepdims=True)
TypeError: reduce_max() got an unexpected keyword argument 'keepdims'
when run the align_datasets_mtcnn.py

**Comment by Abhijitdas2048** [comment]
@liuajian can i know which version of tenserflow / python you are using?

**Comment by Abhijitdas2048** [comment]
.pb file problem solved
