### ISSUE TITLE
Incorrect implementation of euclidean distance in facenet.py

### ISSUE THREAD

**Issue by stardust66** [davidsandberg/facenet#726]
https://github.com/davidsandberg/facenet/blob/master/src/facenet.py#L412

Euclidean distance is the square root of the differences of the squares of the vectors. Should be
```python
diff = np.subtract(embeddings1, embeddings2)
dist = np.sqrt(np.sum(np.square(diff), 1))
```

Correct me if I'm missing something obvious.

**Comment by darwin-xu** [comment]
I think it is not that important to do the sqrt. Only if you keep it consistent, it is just fine.
