### ISSUE TITLE
how to make pairs.txt file on custom data set. 

### ISSUE THREAD

**Issue by praveenkumarchandaliya** [davidsandberg/facenet#730]
no of images in --data_dir or --lfw_dir  folders or relationship between this two folder with pairs.txt file at the time of custom data set is create

**Comment by praveenkumarchandaliya** [comment]
import os
import random
#generate pairs.txt
# Make all matches
for name in os.listdir("/datasets/clf160//"):
        path, dirs, files = next(os.walk("/datasets/clf160//"+name))
        file_count = len(files)
        print(file_count)
        if(file_count==2):
            a = []
            for file in os.listdir("/datasets/clf160//" + name):
                a.append(file)
            with open("pairs.txt","a") as f:
                 pair_two_list=[[0,1]]
                 temp = random.choice(a).split("_")[0] # This line may vary depending on how your images are named.
                 n0  = a[pair_two_list[0][0]].split("_")[1].lstrip("0").rstrip(".png")
                 n1  = a[pair_two_list[0][0]].split("_")[1].lstrip("0").rstrip(".png")
                 f.write(temp + "\t" + n0 + "\t" +n1 + "\n")
        if (file_count == 3):
            a = []
            for file in os.listdir("/datasets/clf160//" + name):
                a.append(file)
            with open("pairs.txt", "a") as f:
                pair_two_list = [[0, 1],[0,2],[1,2]]
                temp = random.choice(a).split("_")[0]  # This line may vary depending on how your images are named.
                for l1  in pair_two_list:
                    n0 = a[l1[0]].split("_")[1].lstrip("0").rstrip(".png")
                    n1 = a[l1[1]].split("_")[1].lstrip("0").rstrip(".png")
                    f.write(temp + "\t" + n0 + "\t" + n1 + "\n")
        if (file_count == 4):
            a = []
            for file in os.listdir("/datasets/clf160//" + name):
                a.append(file)
            with open("pairs.txt", "a") as f:
                pair_two_list = [[0, 1],[0,2],[0,3],[1,2],[1,3],[2,3]]
                temp = random.choice(a).split("_")[0]  # This line may vary depending on how your images are named.
                for l1  in pair_two_list:
                    n0 = a[l1[0]].split("_")[1].lstrip("0").rstrip(".png")
                    n1 = a[l1[1]].split("_")[1].lstrip("0").rstrip(".png")
                    f.write(temp + "\t" + n0 + "\t" + n1 + "\n")
        if (file_count == 5):
            a = []
            for file in os.listdir(/datasets/clf160//" + name):
                a.append(file)
            with open("pairs.txt", "a") as f:
                pair_two_list = [[0, 1],[0,2],[0,3],[0,4],[1,2],[1,3],[1,4],[2,3],[2,4],[3,4]]
                temp = random.choice(a).split("_")[0]  # This line may vary depending on how your images are named.
                for l1  in pair_two_list:
                    n0 = a[l1[0]].split("_")[1].lstrip("0").rstrip(".png")
                    n1 = a[l1[1]].split("_")[1].lstrip("0").rstrip(".png")
                    f.write(temp + "\t" + n0 + "\t" + n1 + "\n")

# Make all mismatches
for i,name in enumerate(os.listdir("/datasets/clf160")):
        remaining = os.listdir("/datasets/clf160")
        del remaining[i] # deletes the file from the list, so that it is not chosen again
        other_dir = random.choice(remaining)
        with open("pairs.txt","a") as f:
            flag=1
            for i in range(1):
                file1 = random.choice(os.listdir("/datasets/clf160//" + name))
                file2 = random.choice(os.listdir("/datasets/clf160//" + other_dir))
                #path, dirs, files = next(os.walk("/datasets/clf160//" + name))
                #file_count = len(files)
                #if(file_count ==1 and flag==1):
                #    f.write(name + "\t" + file1.split("_")[1].lstrip("0").rstrip(".png") + "\t" +other_dir + "\t" + file2.split("_")[1].lstrip("0").rstrip(".png") + "\n")
                #    flag=0
                #if (file_count !=1):
                f.write(name + "\t" + file1.split("_")[1].lstrip("0").rstrip(".png") + "\t" + other_dir + "\t" +
                            file2.split("_")[1].lstrip("0").rstrip(".png") + "\n")

# After shuffle pairs.txt file  usings
import random
with open('pairs.txt','r') as source:
    data = [ (random.random(), line) for line in source ]
data.sort()
with open('shufflepairs.txt','w') as target:
    for _, line in data:
        target.write( line )

**Comment by qjqjqjj** [comment]
Hi @praveenkumarchandaliya,

Thanks for your post but I have a few issue when creating my own pairs.txt when I run the to Make all matches. It stop with a message of 'StopIteration', is it my path that direct to my data wrong or?
