### ISSUE TITLE
Can't use GPU in getting embedding layers?

### ISSUE THREAD

**Issue by taewookim** [davidsandberg/facenet#742]
Versions:
OS: Ubuntu 16.04 LTS
OS RAM: 15gb
GPU: Tesla k80 w/ 12gb memory
TF: 1.8.0
Keras: 2.1.5
Facenet: Latest (git cloned 5/11/2018)
CUDA: Cuda compilation tools, release 9.0, V9.0.176

To make sure TF/Keras can access the GPU, i ran

`from keras import backend as K; print(K.tensorflow_backend._get_available_gpus())`

> 2018-05-12 05:27:28.496005: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that thi\
> s TensorFlow binary was not compiled to use: AVX2 FMA
> 2018-05-12 05:27:28.584137: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from S\
> ysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2018-05-12 05:27:28.584531: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties:
> name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
> pciBusID: 0000:00:04.0
> totalMemory: 11.17GiB freeMemory: 11.09GiB
> 2018-05-12 05:27:28.584556: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
> 2018-05-12 05:27:28.891873: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor w\
> ith strength 1 edge matrix:
> 2018-05-12 05:27:28.891948: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0
> 2018-05-12 05:27:28.891958: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N
> 2018-05-12 05:27:28.892256: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:loc\
> alhost/replica:0/task:0/device:GPU:0 with 10749 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000\
> :00:04.0, compute capability: 3.7)
> /home/T/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of i\
> ssubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).t\
> ype`.
>   from ._conv import register_converters as _register_converters
> Using TensorFlow backend.
> ['/job:localhost/replica:0/task:0/device:GPU:0']

`import tensorflow as tf;sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))`

> 2018-05-12 05:26:45.383271: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that thi\
> s TensorFlow binary was not compiled to use: AVX2 FMA
> 2018-05-12 05:26:45.471990: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from S\
> ysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2018-05-12 05:26:45.472361: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties:
> name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
> pciBusID: 0000:00:04.0
> totalMemory: 11.17GiB freeMemory: 11.09GiB
> 2018-05-12 05:26:45.472382: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
> 2018-05-12 05:26:45.757933: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor w\
> ith strength 1 edge matrix:
> 2018-05-12 05:26:45.757980: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0
> 2018-05-12 05:26:45.757996: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N
> 2018-05-12 05:26:45.758367: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:loc\
> alhost/replica:0/task:0/device:GPU:0 with 10749 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000\
> :00:04.0, compute capability: 3.7)
> 2018-05-12 05:26:45.949442: I tensorflow/core/common_runtime/direct_session.cc:284] Device mapping:
> /job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability\
> : 3.7
> 
> /home/T/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of i\
> ssubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).t\
> ype`.
>   from ._conv import register_converters as _register_converters
> Device mapping:
> /job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability\
> : 3.7
> 

Problem: 

When i run this:

`CUDA_VISIBLE_DEVICES=0 python compare.py  (... rest of parameters ...)`

Watching the output of nvidia-smi, i see that load_and_align_data() seems to getting the GPU memory spiked.. but during the sess.run(), GPU memory is at zero.. which makes me wonder

1) why is the GPU being used ONLY for load_and_align_data?
2) if not, how do I get the GPU to be used for generating the embedding layers as well?

**Comment by taewookim** [comment]
Ok I solved my own case. Turns out to be [CUDA/CUDNN version issue](https://github.com/tensorflow/tensorflow/issues/17566#issuecomment-372490062)

As of this post's date... for anyone who's having similar issues, make sure your CUDA toolkit version is 9.0.x.. and your CUDNN is 7.0.X...   (note that latest CUDA toolki is 9.1'ish.. and CUDNN is 7.1'ish)

But one question I had @davidsandberg  - load_and_align_data() is quite slow . 80 images took 10 seconds. Particularly, align.detect_face.detect_face() took 7.5 second. 

Is there any way to run that in parallel?

**Comment by taewookim** [comment]
I found [bulk_detect_face](https://github.com/davidsandberg/facenet/commit/6718c3be9d1f70a41a45335f982a4dd29c2b0e88), can't quite make out what the return values are

**Comment by Dawson-huang** [comment]
@taewookim I am sure my CUDA toolkit version is 9.0.176 and CUDNN is 7.0.5, but when I ran the recommand :
`python3 align/align_dataset_mtcnn.py align/lfw/ align/lfw_mtcnnalign_160 --image_size 160 --gpu_memory_fraction 0.6`
My computer fan is very loud and the display does not have graphics output signal which is black screen. I am sure my environment is no problem for other cv project. Do you know the reason?

**Comment by taewookim** [comment]
that sounds like your GPU isn't being utilized (maybe driver issue, maybe GPU not supported.. not sure wihch). Try to see if TF can detect your GPU
