### ISSUE TITLE
Detection Face run via Tensorflow Serving

### ISSUE THREAD

**Issue by axmadjon** [davidsandberg/facenet#758]
Hi @davidsandberg and all participants in the project Facenet

I can not solve this problem in any way?
how to make a face detection module through Tensorflow Serving?
are there any options or someone did something like this?

**Comment by axmadjon** [comment]
I did this before the answer.
All thanks for the promptness soon lay out the source code and the model itself

**Comment by axmadjon** [comment]
https://drive.google.com/open?id=1fMHb4mhbEg10YNSbLO2VI5o5hXQRCdNu

**Comment by HFrost0** [comment]
Hi@axmadjon . Thanks for your code. I find that the MTCNN model may not in this facenet project. Can you show me how you construct this model please?
