### ISSUE TITLE
Is this repository has no longer maintain?

### ISSUE THREAD

**Issue by wiput1999** [davidsandberg/facenet#769]
Does anyone have a suggestion about another better facenet or anything that still maintaining by owner?

**Comment by vivekaditya** [comment]
This repository is maintained and is not abandoned. You can find updates by the owner ( looks at the commits ). I do not think there is better facenet implementation (in tensorflow) available although you can find one [keras implementation](https://github.com/nyoki-mtl/keras-facenet).
