### ISSUE TITLE
why the size of my finetune model only 94MB?

### ISSUE THREAD

**Issue by clscy** [davidsandberg/facenet#773]
Hi
I try to train with pretrained_model(tendorflow1.4.1, model:[20180402-114759](https://drive.google.com/open?id=1EXPBSXwTaqrSC0OhUdXNmKSh9qJUQ55-)),
python train_tripletloss.py --logs_base_dir ~/logs/facenet/ --models_base_dir ~/models/facenet/ --data_dir ~/data/vggface2/train_160 --image_size 160 --model_def models.inception_resnet_v1 --lfw_dir ~/data/lfw --lfw_pairs ~/data/pairs.txt --optimizer RMSPROP --learning_rate 0.01 --weight_decay 1e-4 --max_nrof_epochs 500 --people_per_batch 6 --pretrained_model /home/Github36/facenet/src/20180402-114759/model-20180402-114759.ckpt-275

final model only have 94MB.Is this a problem?
Thanks.

**Comment by svobora** [comment]
It is a problem if you have 93 MB HDD.
