### ISSUE TITLE
how to get vggface2 dataset? Please help me.

### ISSUE THREAD

**Issue by LaviLiu** [davidsandberg/facenet#786]
The[ link](http://zeus.robots.ox.ac.uk/vgg_face2/get_file?fname=vggface2_train.tar.gz)http://zeus.robots.ox.ac.uk/vgg_face2/get_file?fname=vggface2_train.tar.gz for vggface2_train.tar.gz doesn`t work still? How can i get vggface2_train.tar.gz now? Please help me.

**Comment by Lunrot** [comment]
I asked the vggface2 administrator to fix the link.
You will be able to download it now.

**Comment by LaviLiu** [comment]
@Lunrot I really can download it now! You are so kind! Thank you very much!

**Comment by vivekaditya** [comment]
@Laviyy Please close the issue if you are able to download the dataset

**Comment by boozyguo** [comment]
@vivekaditya The link of Vggface2 doesn't work again :(

**Comment by igor71** [comment]
Hi, today I'm also tried download Vggface2_train.tar.gz & Vggface2_test.tar.gz and those files are not available on the server...

**Comment by dmonn** [comment]
@Lunrot The downloads are extremely slow/unavailable again

**Comment by ilyanelken** [comment]
@vivekaditya @Laviyy 
Hi, I managed to download the data but it seems like bb_landmarks.tar.gz link is broken:
http://www.robots.ox.ac.uk/~vgg/data/vgg_face2/bb_landmark.tar.gz
I will appreciate your help.

**Comment by LaviLiu** [comment]
@ilyanelken it is work now.

**Comment by ilyanelken** [comment]
@Laviyy Yep, thanks.

**Comment by cagaraza** [comment]
How can I download the dataset if my machine is headless? I have no way of using a browser to click the link that points to the tar.gz file

**Comment by geml** [comment]
@vivekaditya  @Laviyy 
I am having problems downloading the training data - it does not download fully so I cannot extract it.
Can you help?

**Comment by Sawatdatta** [comment]
The download is not resume-able, I tried to download it several times but every time it fails due to interrupted network or power failure. Someone please share the cloud drive link. baidu or dropbox

**Comment by pi-null-mezon** [comment]
Hi. The download link stoped to work today 14.07.2019, near to 00:00. When I have downloaded about 32 out of 36 GB - this kind of troubles always happens with me :). Today browser shows "_The requested URL /vgg_face2/get_file was not found on this server._" So, please, help me too )

**Comment by tamerthamoqa** [comment]
> Hi. The download link stoped to work today 14.07.2019, near to 00:00. When I have downloaded about 32 out of 36 GB - this kind of troubles always happens with me :). Today browser shows "_The requested URL /vgg_face2/get_file was not found on this server._" So, please, help me too )

I wanted to download the dataset today and I am having the same issue, I am also unsure how to officially contact the Visual Group people since their webmaster email domain no longer exists.

EDIT
The issue was fixed (as of Monday 15th July 2019)

**Comment by rinigo** [comment]
> Hi. The download link stoped to work today 14.07.2019, near to 00:00. When I have downloaded about 32 out of 36 GB - this kind of troubles always happens with me :)  

This is exactly whats happening to me these days... anyone know any other link that i can download the datasets from?

**Comment by vkpankov** [comment]
Hi. The link is not working (404 not found). How can I download this dataset? Please, help me!

**Comment by tamerthamoqa** [comment]
> Hi. The link is not working (404 not found). How can I download this dataset? Please, help me!

It is available on [AcademicTorrents](https://academictorrents.com/details/535113b8395832f09121bc53ac85d7bc8ef6fa5b)
