### ISSUE TITLE
Is it possible to run both MTCNN alignment and FaceNet together for a live webcam demo?

### ISSUE THREAD

**Issue by simplysimleprob** [davidsandberg/facenet#79]
Hi David,

Is it possible to run both MTCNN alignment (to get bb and landmarks) and FaceNet (to get embeddings for the bbs) to show landmarks detection as well as recognition on live webcam streams using your pre-trained models on a GPU? (similar to OpenFace webcam demo https://cmusatyalab.github.io/openface/demo-4-sphere/)

Using two sessions seem conflicting, if you have any idea regarding this, please let me know.
I really appreciate your help.
Thank you.

**Comment by davidsandberg** [comment]
Have a look at `compare.py` which does exactly this. It should give you an idea of how it could be done.

**Comment by simplysimleprob** [comment]
@davidsandberg Thank you so much!!! I will take a look at compare.py. Thank you:)
