### ISSUE TITLE
How to convert to CoreML (iOS)

### ISSUE THREAD

**Issue by ramiro-feria-puron** [davidsandberg/facenet#792]
Can anyone provide insights on how to convert the trained models to CoreML?

**Comment by cyrilzakka** [comment]
+1

**Comment by hi-yox** [comment]
+1

**Comment by jiangxiluning** [comment]
@ramiro-feria-puron @cyrilzakka plz refer to my repo https://github.com/jiangxiluning/facenet_mtcnn_to_mobile
