### ISSUE TITLE
MTCNN tensorflow training

### ISSUE THREAD

**Issue by apollo-time** [davidsandberg/facenet#81]
I use this tensorflow NTCNN model well.
And I want to train MTCNN model on own database.
I see like "However, work is ongoing to reimplement MTCNN face alignment in Python/Tensorflow. Currently some work still remains on this but the implementation can be found here." in README.
How can I train this model on own database with tensorflow python?

**Comment by Tobias-Fischer** [comment]
Hi,
I am interested in training MTCNN as well. Is there any hint on how to do this?
Thanks!

**Comment by davidsandberg** [comment]
Just to be clear I just converted the Caffe model from the authors to tensorflow, so I didn't have to train the model my self. In the [MTCNN](https://github.com/kpzhang93/MTCNN_face_detection_alignment/blob/master/paper/spl.pdf) paper they describe pretty well how the training was done, so that's a good starting point.

**Comment by joyhuang9473** [comment]
Hi @davidsandberg . May I ask how do you convert MTCNN caffe model to the tensorflow model ?

I have tried to use [ethereon/caffe-tensorflow](https://github.com/ethereon/caffe-tensorflow) to convert the model, but it seems that 'PReLU' layer is not supported at it.

Thank you!

**Comment by davidsandberg** [comment]
Hi @joyhuang9473,
I also used ethereon/caffe-tensorflow but as you say it didn't have an implementation of PReLU, so I had to add it. I have added a a fork of ethereon/caffe-tensorflow that contains the required changes [here](https://github.com/davidsandberg/caffe-tensorflow).

```
    @layer
    def prelu(self, input, name):
        with tf.variable_scope(name):
            i = input.get_shape().as_list()
            alpha = self.make_var('alpha', shape=(i[-1]))
            output = tf.nn.relu(input) + tf.mul(tf.ones(i[0:-1]+[1]) * alpha, -tf.nn.relu(-input))
        return output
```

**Comment by ManningZhang** [comment]
Hi@apollo-time I am interested in training MTCNN model as well , have you found anything useful ??
Hope for your answer~thanks a lot~

**Comment by AITTSMD** [comment]
@Tobias-Fischer I have trained MTCNN using tensorflow.Please refer https://github.com/AITTSMD/MTCNN-Tensorflow

**Comment by Tobias-Fischer** [comment]
Thanks @AITTSMD, I'll give it a try.
