### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by alanMachineLeraning** [davidsandberg/facenet#821]
Epoch: [1][993/1000]	Time 0.462	Loss nan	Xent nan	RegLoss nan	Accuracy 0.456	Lr 0.00005	Cl nan
Epoch: [1][994/1000]	Time 0.447	Loss nan	Xent nan	RegLoss nan	Accuracy 0.556	Lr 0.00005	Cl nan
Epoch: [1][995/1000]	Time 0.471	Loss nan	Xent nan	RegLoss nan	Accuracy 0.489	Lr 0.00005	Cl nan
Epoch: [1][996/1000]	Time 0.469	Loss nan	Xent nan	RegLoss nan	Accuracy 0.556	Lr 0.00005	Cl nan
Epoch: [1][997/1000]	Time 0.457	Loss nan	Xent nan	RegLoss nan	Accuracy 0.589	Lr 0.00005	Cl nan
Epoch: [1][998/1000]	Time 0.469	Loss nan	Xent nan	RegLoss nan	Accuracy 0.456	Lr 0.00005	Cl nan
Epoch: [1][999/1000]	Time 0.474	Loss nan	Xent nan	RegLoss nan	Accuracy 0.500	Lr 0.00005	Cl nan
Epoch: [1][1000/1000]	Time 0.460	Loss nan	Xent nan	RegLoss nan	Accuracy 0.444	Lr 0.00005	Cl nan
Saving variables
Variables saved in 0.74 seconds
Saving metagraph
Metagraph saved in 3.01 seconds
Saving statistics
Traceback (most recent call last):
  File "src/train_softmax.py", line 580, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/train_softmax.py", line 260, in main
    for key, value in stat.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by angpao** [comment]
same error 

AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by FortiLeiZhang** [comment]
That is because Python3 has renamed dict.iteritems() to dict.items().

**Comment by tiagolofi** [comment]
the solution is update library with the error

in my case: openpyxl==1.0.0 => openpyxl==3.0.9
