### ISSUE TITLE
Problems with --pretrained_model

### ISSUE THREAD

**Issue by Victoria2333** [davidsandberg/facenet#827]
when i run:
python train_softmax.py --data_dir /home/han2/facenet/face/CASIA-WebFace_align --image_size 160 --pretrained_model /home/han2/facenet/src/pretrained_models/20180408-102900/model-20180408-102900.ckpt-90
I got the error:
Assign requires shapes of both tensors to match. lhs shape= [1792,128] rhs shape= [1792,512]
	 [[Node: save/Assign_21 = Assign[T=DT_FLOAT, _class=["loc:@InceptionResnetV1/Bottleneck/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](InceptionResnetV1/Bottleneck/weights, save/RestoreV2/_841)]]
	 [[Node: save/RestoreV2/_1554 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_730_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:194)]]

I don't change the code, but it can't run with the provided pretrained_model

**Comment by bing1zhi2** [comment]
@Victoria2333 hello,I got the same error.Have you solved the problem?
