### ISSUE TITLE
How to make train_softmax.py run on GPU?

### ISSUE THREAD

**Issue by rgsousa88** [davidsandberg/facenet#858]
Hi everyone,

I have a question. How can I set the train_softmax.py script to run in gpu? I have a machine with a NVIDIA 1080 GPU and I'm training a model (using a different dataset of faces) in this one. But, when I run the command _**nvidia-smi**_ I've got the message "No running processes found". I've searched for this kind of issues or questions but I have not found anything.

Thanks.

**Comment by winroot** [comment]
google install cuda cudnn

rgsousa88 <notifications@github.com> 于2018年8月28日周二 上午2:13写道：

**Comment by winroot** [comment]
sudo apt install tensorflow-gpu==1.7.0

**Comment by rgsousa88** [comment]
Hi, @winroot,

First of all, thanks for answer my question. Unfortunately, this command did not work for me. I also tried **sudo pip3 install tensorflow-gpu==1.7.0** and whem importing tensorflow a error has ocurred:
**ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory.**

Have you ever seen something like this? I've googled it but without sucess.

Thanks.

**Comment by winroot** [comment]
https://www.tensorflow.org/install/install_linux 
plz install cuda9 & cudnn7

**Comment by rgsousa88** [comment]
Hi @winroot, first of all, thanks for you time and I'm sorry for taking so long to answer. I finished the train. I had problems with installed versions of cuda/cudnn libs. I've solved this by updating libs to the newest version available.
