### ISSUE TITLE
Training and validation image pre-processing

### ISSUE THREAD

**Issue by jrabary** [davidsandberg/facenet#86]
Hi @davidsandberg, can you explain what pre-processing step do you apply during the training and the validation process. I notice that in the training code (classification) the images are not pre-whitened  and the features are not l2 normalized. This is not the case in the validation step. Is it right ?

**Comment by davidsandberg** [comment]
For training using facenet_train_classifier.py the preprocessing is done in facenet.read_and_augument_data(...) as
```
 for _ in range(nrof_preprocess_threads):
        image, label = read_images_from_disk(input_queue)
        if random_crop:
            image = tf.random_crop(image, [image_size, image_size, 3])
        else:
            image = tf.image.resize_image_with_crop_or_pad(image, image_size, image_size)
        if random_flip:
            image = tf.image.random_flip_left_right(image)
        #pylint: disable=no-member
        image.set_shape((image_size, image_size, 3))
        image = tf.image.per_image_whitening(image)
        images_and_labels.append([image, label])
```
So there is a pre-whitening step here as well.

**Comment by jrabary** [comment]
@davidsandberg thanks. I didn't find this one!

**Comment by Hamiltonsjtu** [comment]
in the training code tf.image.per_image_standardization works as pre-whiten function for inference.
