### ISSUE TITLE
AttributeError: 'SVC' object has no attribute 'probability'

### ISSUE THREAD

**Issue by qianchen94** [davidsandberg/facenet#860]
when i run real_time_face_recognition.py using windows 10,it occurred the problem 
AttributeError: 'SVC' object has no attribute 'probability'
did someone met the problem? how to slove it?
tks

**Comment by ViousGod** [comment]
Can u tell me how to solve it?

**Comment by w5688414** [comment]
I meet the same issue

**Comment by amentrak** [comment]
I also had the same error

**Comment by glennford49** [comment]
AttributeError: 'SVC' object has no attribute '_probA'

**Comment by Varat7v2** [comment]
What is the solution of this problem?

**Comment by glennford49** [comment]
I have fixed it by retraining again the classifier

**Comment by Varat7v2** [comment]
@glennford49 would you mind sharing your classifier please, if you won't have any problem?

**Comment by AbsolutelySaurabh** [comment]
Error: AttributeError: 'SVC' object has no attribute '_probA'
Solution in my case:
The version of trained model scikit-learn and prediction model scikit-learn were different.
I made them same to both 0.22.1, and things worked as expected.

**Comment by kadirdogan** [comment]
> Error: AttributeError: 'SVC' object has no attribute '_probA'
> Solution in my case:
> The version of trained model scikit-learn and prediction model scikit-learn were different.
> I made them same to both 0.22.1, and things worked as expected.

please can you explain exactly how to do this?

**Comment by Ahmedniz2** [comment]
> Error: AttributeError: 'SVC' object has no attribute '_probA'
> Solution in my case:
> The version of trained model scikit-learn and prediction model scikit-learn were different.
> I made them same to both 0.22.1, and things worked as expected.

Would love to know how you solved this issue.
Facing the same issue atm.

**Comment by amlanmohanty1** [comment]
Why would one retrain the model if you have already saved the model using pickle?

**Comment by amlanmohanty1** [comment]
> 
> 
> Error: AttributeError: 'SVC' object has no attribute '_probA'
> Solution in my case:
> The version of trained model scikit-learn and prediction model scikit-learn were different.
> I made them same to both 0.22.1, and things worked as expected.

Can you please guide us on how to do it?

**Comment by Umraz-Hussain1** [comment]
# use these two commands ur problems will be solved 

!pip uninstall scikit-learn -y

!pip install -U scikit-learn==0.24.1

enjoy...
