### ISSUE TITLE
Where should I start?

### ISSUE THREAD

**Issue by Ripppah** [davidsandberg/facenet#87]
Sorry, I am very new to tensorflow and neural network. Since there is bunch of files and folders in this repo. Where should I start? And also want to make sure that only align folder is for tensorflow/python right? I don't need to take care of other files if I only want to do anything else in python?

**Comment by davidsandberg** [comment]
It depends on what you want to do. Maybe start to evaluate a pretrained model on LFW according to https://github.com/davidsandberg/facenet/wiki/Validate-on-LFW?

**Comment by Ripppah** [comment]
I run the pre-trained model here. The output is something like this:
"""
MacBook-Pro-2:src $ python validate_on_lfw.py ~/Desktop/datasets/lfw/lfw_mtcnnpy_160 ~/Desktop/models/20161116-234200
/usr/local/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Skipped 6000 image pairs
Model directory: /Users/Cherry/Desktop/models/20161116-234200
Metagraph file: model-20161116-234200.meta
Checkpoint file: model-20161116-234200.ckpt-80000
Runnning forward pass on LFW images
Traceback (most recent call last):
  File "validate_on_lfw.py", line 109, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "validate_on_lfw.py", line 82, in main
    args.seed, actual_issame, nrof_folds=args.lfw_nrof_folds)
  File "/Users/Cherry/Desktop/facenet-master/src/lfw.py", line 40, in evaluate
    np.asarray(actual_issame), seed, nrof_folds=nrof_folds)
  File "/Users/Cherry/Desktop/facenet-master/src/facenet.py", line 496, in calculate_roc
    folds = KFold(n=nrof_pairs, n_folds=nrof_folds, shuffle=True, random_state=seed)
  File "/usr/local/lib/python2.7/site-packages/sklearn/cross_validation.py", line 338, in __init__
    super(KFold, self).__init__(n, n_folds, shuffle, random_state)
  File "/usr/local/lib/python2.7/site-packages/sklearn/cross_validation.py", line 265, in __init__
    " than the number of samples: {1}.").format(n_folds, n))
ValueError: Cannot have number of folds n_folds=10 greater than the number of samples: 0.
"""
Any idea on what's wrong with that?
Thanks!

**Comment by Ripppah** [comment]
@davidsandberg I have done the pre-processing on the LFW data. So should I start training? Do I need to do align on the Casia/Facescrub dataset?
