### ISSUE TITLE
Finished Validation instruction

### ISSUE THREAD

**Issue by Ripppah** [davidsandberg/facenet#88]
I am new and not really familiar with tensor flow and neural network. 
So I have aligned the LFW dataset and validated it just as it instructed in the wiki file. It seems work well. Is this mean that I can load a picture and identify who it is in this picture? How to do this? Where can I find the weight file?

**Comment by davidsandberg** [comment]
The easiest way, that doesn't require any retraining of the network is to compare faces in the embedding space. Small L2 distance between the embeddings means that it is likely the same person in the corresponding images. Have a look at compare.py and you will hopefully see how it's supposed to work.

**Comment by Ripppah** [comment]
@davidsandberg How can I use the result of the L2 distance to train new face and add them to the database so that whenever I show a new face, it will be remembered and the next time, the machine will know who that is?

**Comment by davidsandberg** [comment]
Closing for now. Reopen if needed.
