### ISSUE TITLE
there is no "validate" function in the "lfw.py" file.

### ISSUE THREAD

**Issue by KwakJiWon** [davidsandberg/facenet#91]
As I have seen, there is no "validate" function in the "lfw.py" file.

**Comment by davidsandberg** [comment]
Yes, this is a known problem. I'm currently rewriting facenet_train.py to run more efficiently using an input pipeline (similar to what's done in facenet_train_classifier.py). But this will also change how the model is evaluated on LFW so I will not fix this for now.
