### ISSUE TITLE
'Logits/BiasAdd:0' not exists

### ISSUE THREAD

**Issue by modanesh** [davidsandberg/facenet#918]
Hi,

I've used the `freeze_graph.py` to freeze a model. The directory of the model contains these files:

> checkpoint
> model-best.ckpt-4.data-00000-of-00001
> model-best.ckpt-7.index
> model-best.ckpt-1.data-00000-of-00001
> model-best.ckpt-4.index
> model-best.ckpt-1.index
> model-best.ckpt-7.data-00000-of-00001

After using the `freeze_graph.py`, the freezed model(`sample.pb`) is saved in the given path.

However, when I want to load the freezed model and give it a new image to get the probability of each class using the below code:
`logits = tf.get_default_graph().get_tensor_by_name("Logits/BiasAdd:0")`

it gives me the following error:
`KeyError: "The name 'Logits/BiasAdd:0' refers to a Tensor which does not exist. The operation, 'Logits/BiasAdd', does not exist in the graph."`

Any suggestions?

**Comment by ZlaaM** [comment]
i have the same error ,,,, please how can i solve it ?? help me please
