### ISSUE TITLE
Change the dtypes for data_flow_ops.FIFOQueue to tf.int64 from tf.int32. And also change the dtypes for labels_placeholder and control_placeholder to tf.int64 from tf.int32. That did it for me.

### ISSUE THREAD

**Issue by chensicheng** [davidsandberg/facenet#947]
Change the dtypes for data_flow_ops.FIFOQueue to tf.int64 from tf.int32. And also change the dtypes for labels_placeholder and control_placeholder to tf.int64 from tf.int32. That did it for me.

_Originally posted by @chensteven in https://github.com/davidsandberg/facenet/issues/806#issuecomment-406369342_

**Comment by chensicheng** [comment]
Change the dtypes for data_flow_ops.FIFOQueue to tf.int64 from tf.int32. And also change the dtypes for labels_placeholder and control_placeholder to tf.int64 from tf.int32. That did it for me.
which file I should change

**Comment by chensicheng** [comment]
![image](https://user-images.githubusercontent.com/20574853/50672845-6072ba80-1015-11e9-800b-b2581273d033.png)

**Comment by chensicheng** [comment]
58    chang code  tf.int32   to  tf.int64
66                          dtypes=[tf.string, tf.int2, tf.int32],          to      dtypes=[tf.string, tf.int64, tf.int32],

**Comment by zhenglilei** [comment]
> 58 chang code tf.int32 to tf.int64
> 66 dtypes=[tf.string, tf.int2, tf.int32], to dtypes=[tf.string, tf.int64, tf.int32],

Thanks, works for me.
