### ISSUE TITLE
Classifier training utilizes 0% of GPU power

### ISSUE THREAD

**Issue by angervision** [davidsandberg/facenet#960]
Hi All,

I'm trying to train the provided model using this guide: 
https://github.com/davidsandberg/facenet/wiki/Train-a-classifier-on-own-images.

Here is the command that I'm using:
```
python src/classifier.py TRAIN ~/datasets/train_aligned_mtcnnpy_160 ~/models/20180408-102900.pb ~/models/clf.pkl --batch_size 1000
```

During the training of the classifier I get 0% of Compute M. and 100% CPU utilization (just 1 core):
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   47C    P8     6W / 166W |   7879MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

Could you, please, point me in the right direction, what's I'm doing wrong?

Thanks a lot.

**Comment by angervision** [comment]
OK, so I've isolated an issue myself. Unfortunately, facenet classifier.py utilizes sklearn-kit for training:

```
from sklearn.svm import SVC
...
model = SVC(kernel='linear', probability=True)
model.fit(emb_array, labels)
```

Since sklearn implementation is single-threaded and works on CPU only, it is the bottleneck in this specific case. So, I suggest converting this implementation to Tensorflow or Keras, therefore it could use all the CPU\GPU power of the machine.

**Comment by taureanamir** [comment]
@davidsandberg ,
I have also met with the same issue. GPU memory is used but the computation is done only by the CPU. GPU computation is 0%.
