### ISSUE TITLE
Only one face can be aligned?

### ISSUE THREAD

**Issue by FantasyJXF** [davidsandberg/facenet#965]
I test the `[...]/src/align/align_dataset_mtcnn.py` with some pictures and notice the condition that the model can only align ** One Face ** within the picture, when their is many faces, it looks like that the model only aligns the face one the middle of the picture.
![test1](https://user-images.githubusercontent.com/16235526/51954856-c3bd0480-247c-11e9-80e9-972b81f3f4dc.png)
![tets2](https://user-images.githubusercontent.com/16235526/51954862-c881b880-247c-11e9-92e5-aec3b5217beb.jpg)
![test1](https://user-images.githubusercontent.com/16235526/51954864-cc153f80-247c-11e9-86b3-dbbc9d0b8c49.png)
![tets2](https://user-images.githubusercontent.com/16235526/51954868-cfa8c680-247c-11e9-939a-a7584a5a1a78.png)

**Comment by chaos87** [comment]
There is an option to allow for detecting multiple faces. 
See the flag --detect_multiple_faces at the bottom of the script, by default it is set to False.
If you want to detect all faces you just have to run the script like so:

[...]/src/align/align_dataset_mtcnn.py --detect_multiple_faces True

**Comment by FantasyJXF** [comment]
Thanks, I'm  going to try. 😁

发自我的 iPhone

**Comment by FantasyJXF** [comment]
Thanks again
