### ISSUE TITLE
three models in models_base_dir

### ISSUE THREAD

**Issue by hby2013** [davidsandberg/facenet#99]
Why there were three models under the models_bases_dir after I ran the classifier training program,which called the 'model-20161226-203233.ckpt-78000.data-00000-of-00001','model-20161226-203233.ckpt-79000.data-00000-of-00001' and 'model-20161226-203233.ckpt-80000.data-00000-of-00001'?And which of the models should I use to validate on the LFW?

**Comment by davidsandberg** [comment]
The numbers 78000, 79000 and 80000 is the step number for the check point. Use the last one (80000) for the latest.
